export const countriesAndCitizenshipsData = [
    { label: "AFGHAN", value: "AFGHAN", country: "AFGHANISTAN" },
    { label: "ALBANIAN", value: "ALBANIAN", country: "ALBANIA" },
    { label: "ALGERIAN", value: "ALGERIAN", country: "ALGERIA" },
    { label: "ANDORRAN", value: "ANDORRAN", country: "ANDORRA" },
    { label: "ANGOLAN", value: "ANGOLAN", country: "ANGOLA" },
    { label: "ARGENTINIAN", value: "ARGENTINIAN", country: "ARGENTINA" },
    { label: "ARMENIAN", value: "ARMENIAN", country: "ARMENIA" },
    { label: "AUSTRALIAN", value: "AUSTRALIAN", country: "AUSTRALIA" },
    { label: "AUSTRIAN", value: "AUSTRIAN", country: "AUSTRIA" },
    { label: "AZERBAIJANI", value: "AZERBAIJANI", country: "AZERBAIJAN" },
    { label: "BAHAMIAN", value: "BAHAMIAN", country: "BAHAMAS" },
    { label: "BAHRAINI", value: "BAHRAINI", country: "BAHRAIN" },
    { label: "BANGLADESHI", value: "BANGLADESHI", country: "BANGLADESH" },
    { label: "BARBADIAN", value: "BARBADIAN", country: "BARBADOS" },
    { label: "BELARUSIAN", value: "BELARUSIAN", country: "BELARUS" },
    { label: "BELGIAN", value: "BELGIAN", country: "BELGIUM" },
    { label: "BELIZEAN", value: "BELIZEAN", country: "BELIZE" },
    { label: "BENINESE", value: "BENINESE", country: "BENIN" },
    { label: "BHUTANESE", value: "BHUTANESE", country: "BHUTAN" },
    { label: "BOLIVIAN", value: "BOLIVIAN", country: "BOLIVIA" },
    { label: "BOSNIAN", value: "BOSNIAN", country: "BOSNIA AND HERZEGOVINA" },
    { label: "BRAZILIAN", value: "BRAZILIAN", country: "BRAZIL" },
    { label: "BRUNEIAN", value: "BRUNEIAN", country: "BRUNEI" },
    { label: "BULGARIAN", value: "BULGARIAN", country: "BULGARIA" },
    { label: "BURKINABE", value: "BURKINABE", country: "BURKINA FASO" },
    { label: "BURUNDIAN", value: "BURUNDIAN", country: "BURUNDI" },
    { label: "CAPE VERDEAN", value: "CAPE VERDEAN", country: "CAPE VERDE" },
    { label: "CAMBODIAN", value: "CAMBODIAN", country: "CAMBODIA" },
    { label: "CAMEROONIAN", value: "CAMEROONIAN", country: "CAMEROON" },
    { label: "CANADIAN", value: "CANADIAN", country: "CANADA" },
    { label: "CENTRAL AFRICAN", value: "CENTRAL AFRICAN", country: "CENTRAL AFRICAN REPUBLIC" },
    { label: "CHADIAN", value: "CHADIAN", country: "CHAD" },
    { label: "CHILEAN", value: "CHILEAN", country: "CHILE" },
    { label: "CHINESE", value: "CHINESE", country: "CHINA" },
    { label: "COLOMBIAN", value: "COLOMBIAN", country: "COLOMBIA" },
    { label: "COMORIAN", value: "COMORIAN", country: "COMOROS" },
    { label: "CONGOLESE", value: "CONGOLESE", country: "CONGO" },
    { label: "COSTA RICAN", value: "COSTA RICAN", country: "COSTA RICA" },
    { label: "CROATIAN", value: "CROATIAN", country: "CROATIA" },
    { label: "CUBAN", value: "CUBAN", country: "CUBA" },
    { label: "CYPRIOT", value: "CYPRIOT", country: "CYPRUS" },
    { label: "CZECH", value: "CZECH", country: "CZECH REPUBLIC" },
    { label: "DANISH", value: "DANISH", country: "DENMARK" },
    { label: "DJIBOUTIAN", value: "DJIBOUTIAN", country: "DJIBOUTI" },
    { label: "DOMINICAN", value: "DOMINICAN", country: "DOMINICA" },
    { label: "DOMINICAN", value: "DOMINICAN", country: "DOMINICAN REPUBLIC" },
    { label: "ECUADORIAN", value: "ECUADORIAN", country: "ECUADOR" },
    { label: "EGYPTIAN", value: "EGYPTIAN", country: "EGYPT" },
    { label: "EL SALVADORAN", value: "EL SALVADORAN", country: "EL SALVADOR" },
    { label: "EQUATORIAL GUINEAN", value: "EQUATORIAL GUINEAN", country: "EQUATORIAL GUINEA" },
    { label: "ERITREAN", value: "ERITREAN", country: "ERITREA" },
    { label: "ESTONIAN", value: "ESTONIAN", country: "ESTONIA" },
    { label: "ETHIOPIAN", value: "ETHIOPIAN", country: "ETHIOPIA" },
    { label: "FIJIAN", value: "FIJIAN", country: "FIJI" },
    { label: "FINNISH", value: "FINNISH", country: "FINLAND" },
    { label: "FRENCH", value: "FRENCH", country: "FRANCE" },
    { label: "GABONESE", value: "GABONESE", country: "GABON" },
    { label: "GAMBIAN", value: "GAMBIAN", country: "THE GAMBIA" },
    { label: "GEORGIAN", value: "GEORGIAN", country: "GEORGIA" },
    { label: "GERMAN", value: "GERMAN", country: "GERMANY" },
    { label: "GHANAIAN", value: "GHANAIAN", country: "GHANA" },
    { label: "GREEK", value: "GREEK", country: "GREECE" },
    { label: "GRENADIAN", value: "GRENADIAN", country: "GRENADA" },
    { label: "GUATEMALAN", value: "GUATEMALAN", country: "GUATEMALA" },
    { label: "GUINEAN", value: "GUINEAN", country: "GUINEA" },
    { label: "GUYANESE", value: "GUYANESE", country: "GUYANA" },
    { label: "HAITIAN", value: "HAITIAN", country: "HAITI" },
    { label: "HONDURAN", value: "HONDURAN", country: "HONDURA" },
    { label: "HUNGARIAN", value: "HUNGARIAN", country: "HUNGARY" },
    { label: "ICELANDER", value: "ICELANDER", country: "ICELAND" },
    { label: "INDIAN", value: "INDIAN", country: "INDIA" },
    { label: "INDONESIAN", value: "INDONESIAN", country: "INDONESIA" },
    { label: "IRANIAN", value: "IRANIAN", country: "IRAN" },
    { label: "IRAQI", value: "IRAQI", country: "IRAQ" },
    { label: "IRISH", value: "IRISH", country: "IRELAND" },
    { label: "ISRAELI", value: "ISRAELI", country: "ISRAEL" },
    { label: "ITALIAN", value: "ITALIAN", country: "ITALY" },
    { label: "JAMAICAN", value: "JAMAICAN", country: "JAMAICA" },
    { label: "JAPANESE", value: "JAPANESE", country: "JAPAN" },
    { label: "JORDANIAN", value: "JORDANIAN", country: "JORDAN" },
    { label: "KAZAKHSTANI", value: "KAZAKHSTANI", country: "KAZAKHSTAN" },
    { label: "KENYAN", value: "KENYAN", country: "KENYA" },
    { label: "KUWAITI", value: "KUWAITI", country: "KUWAIT" },
    { label: "KYRGYZSTANI", value: "KYRGYZSTANI", country: "KYRGYZSTAN" },
    { label: "LAO", value: "LAO", country: "LAOS" },
    { label: "LATVIAN", value: "LATVIAN", country: "LATVIA" },
    { label: "LEBANESE", value: "LEBANESE", country: "LEBANON" },
    { label: "BASOTHO", value: "BASOTHO", country: "LESOTHO" },
    { label: "LIBERIAN", value: "LIBERIAN", country: "LIBERIA" },
    { label: "LIBYAN", value: "LIBYAN", country: "LIBYA" },
    { label: "LIECHTENSTEINER", value: "LIECHTENSTEINER", country: "LIECHTENSTEIN" },
    { label: "LITHUANIAN", value: "LITHUANIAN", country: "LITHUANIA" },
    { label: "LUXEMBOURGER", value: "LUXEMBOURGER", country: "LUXEMBOURG" },
    { label: "MALAGASY", value: "MALAGASY", country: "MADAGASCAR" },
    { label: "MALAWIAN", value: "MALAWIAN", country: "MALAWI" },
    { label: "MALAYSIAN", value: "MALAYSIAN", country: "MALAYSIA" },
    { label: "MALDIVIAN", value: "MALDIVIAN", country: "MALDIVES" },
    { label: "MALIAN", value: "MALIAN", country: "MALI" },
    { label: "MALTESE", value: "MALTESE", country: "MALTA" },
    { label: "MARSHALLESE", value: "MARSHALLESE", country: "MARSHALL ISLANDS" },
    { label: "MAURITANIAN", value: "MAURITANIAN", country: "MAURITANIA" },
    { label: "MAURITIAN", value: "MAURITIAN", country: "MAURITIUS" },
    { label: "MEXICAN", value: "MEXICAN", country: "MEXICO" },
    { label: "MICRONESIAN", value: "MICRONESIAN", country: "MICRONESIA" },
    { label: "MOLDOVAN", value: "MOLDOVAN", country: "MOLDOVA" },
    { label: "MONACAN", value: "MONACAN", country: "MONACO" },
    { label: "MONGOLIAN", value: "MONGOLIAN", country: "MONGOLIA" },
    { label: "MONTENEGRIN", value: "MONTENEGRIN", country: "MONTENEGRO" },
    { label: "MOROCCAN", value: "MOROCCAN", country: "MOROCCO" },
    { label: "MOZAMBICAN", value: "MOZAMBICAN", country: "MOZAMBIQUE" },
    { label: "BURMESE", value: "BURMESE", country: "MYANMAR" },
    { label: "NAMIBIAN", value: "NAMIBIAN", country: "NAMIBIA" },
    { label: "NAURUAN", value: "NAURUAN", country: "NAURU" },
    { label: "NEPALESE", value: "NEPALESE", country: "NEPAL" },
    { label: "DUTCH", value: "DUTCH", country: "NETHERLANDS" },
    { label: "NEW ZEALANDER", value: "NEW ZEALANDER", country: "NEW ZERLAND" },
    { label: "NICARAGUAN", value: "NICARAGUAN", country: "NICARAGUA" },
    { label: "NIGERIAN", value: "NIGERIAN", country: "NIGERIA" },
    { label: "NORTH KOREAN", value: "NORTH KOREAN", country: "NORTH KOREA" },
    { label: "MACEDONIAN", value: "MACEDONIAN", country: "NORTH MACEDONIA" },
    { label: "NORWEGIAN", value: "NORWEGIAN", country: "NORWAY" },
    { label: "PAKISTANI", value: "PAKISTANI", country: "PAKISTAN" },
    { label: "PALAUAN", value: "PALAUAN", country: "PALAU" },
    { label: "PALESTINIAN", value: "PALESTINIAN", country: "PALESTINE" },
    { label: "PANAMANIAN", value: "PANAMANIAN", country: "PANAMA" },
    { label: "PAPUA NEW GUINEAN", value: "PAPUA NEW GUINEAN", country: "PAPUA NEW GUINEA" },
    { label: "PARAGUAYAN", value: "PARAGUAYAN", country: "PARAGUAY" },
    { label: "PERUVIAN", value: "PERUVIAN", country: "PERU" },
    { label: "FILIPINO", value: "FILIPINO", country: "PHILIPPINES" },
    { label: "POLISH", value: "POLISH", country: "POLAND" },
    { label: "PORTUGUESE", value: "PORTUGUESE", country: "PORTUGAL" },
    { label: "QATARI", value: "QATARI", country: "QATAR" },
    { label: "ROMANIAN", value: "ROMANIAN", country: "ROMANIA" },
    { label: "RUSSIAN", value: "RUSSIAN", country: "RUSSIA" },
    { label: "RWANDAN", value: "RWANDAN", country: "RWANDA" },
    { label: "KITTITIAN OR NEVISIAN", value: "KITTITIAN OR NEVISIAN", country: "SAINT KITTS AND NEVIS" },
    { label: "SAINT LUCIAN", value: "SAINT LUCIAN", country: "SAINT LUCIA" },
    { label: "SAINT VINCENTIAN", value: "SAINT VINCENTIAN", country: "SAINT VINCENT AND THE GRENADINES" },
    { label: "SAMOAN", value: "SAMOAN", country: "SAMOA" },
    { label: "SAMMARINESE", value: "SAMMARINESE", country: "SAN MARINO" },
    { label: "SAO TOMEAN", value: "SAO TOMEAN", country: "SAO TOME AND PRINCIPE" },
    { label: "SAUDI", value: "SAUDI", country: "SAUDI ARABIA" },
    { label: "SENEGALESE", value: "SENegalese", country: "SENEGAL" },
    { label: "SERBIAN", value: "SERBIAN", country: "SERBIA" },
    { label: "SIERRA LEONEAN", value: "SIERRA LEONEAN", country: "SIERRA LEONE" },
    { label: "SINGAPOREAN", value: "SINGAPOREAN", country: "SINGAPORE" },
    { label: "SLOVAK", value: "SLOVAK", country: "SLOVAKIA" },
    { label: "SLOVENIAN", value: "SLOVENIAN", country: "SLOVENIA" },
    { label: "SOLOMON ISLANDER", value: "SOLOMON ISLANDER", country: "SOLOMON ISLANDS" },
    { label: "SOMALI", value: "SOMALI", country: "SOMALIA" },
    { label: "SOUTH AFRICAN", value: "SOUTH AFRICAN", country: "SOUTH AFRICA" },
    { label: "SOUTH KOREAN", value: "SOUTH KOREAN", country: "SOUTH KOREA" },
    { label: "SOUTH SUDANESE", value: "SOUTH SUDANESE", country: "SOUTH SUDAN" },
    { label: "SPANISH", value: "SPANISH", country: "SPAIN" },
    { label: "SRI LANKAN", value: "SRI LANKAN", country: "SRI LANKA" },
    { label: "SUDANESE", value: "SUDANESE", country: "SUDAN" },
    { label: "SWEDISH", value: "SWEDISH", country: "SWEDEN" },
    { label: "SWISS", value: "SWISS", country: "SWITZERLAND" },
    { label: "SYRIAN", value: "SYRIAN", country: "SYRIA" },
    { label: "TAIWANESE", value: "TAIWANESE", country: "TAIWAN" },
    { label: "TAJIK", value: "TAJIK", country: "TAJIKISTAN" },
    { label: "TANZANIAN", value: "TANZANIAN", country: "TANZANIA" },
    { label: "THAI", value: "THAI", country: "THAILAND" },
    { label: "TIMORESE", value: "TIMORESE", country: "TIMOR-LESTE" },
    { label: "TOGOLESE", value: "TOGOLESE", country: "TOGO" },
    { label: "TONGAN", value: "TONGAN", country: "TONGA" },
    { label: "TRINIDADIAN OR TOBAGONIAN", value: "TRINIDADIAN OR TOBAGONIAN", country: "TRINIDAD AND TOBAGO" },
    { label: "TUNISIAN", value: "TUNISIAN", country: "TUNISIA" },
    { label: "TURKISH", value: "TURKISH", country: "TURKEY" },
    { label: "TURKMEN", value: "TURKMEN", country: "TURKMENISTAN" },
    { label: "UGANDAN", value: "UGANDAN", country: "UGANDA" },
    { label: "UKRAINIAN", value: "UKRAINIAN", country: "UKRAINE" },
    { label: "EMIRATI", value: "EMIRATI", country: "UNITED ARAB EMIRATES" },
    { label: "BRITISH", value: "BRITISH", country: "UNITED KINGDOM" },
    { label: "AMERICAN", value: "AMERICAN", country: "UNITED STATES OF AMERICA" },
    { label: "URUGUAYAN", value: "URUGUAYAN", country: "URUGUAY" },
    { label: "YEMENI", value: "YEMENI", country: "YEMEN" },
    { label: "ZAMBIAN", value: "ZAMBIAN", country: "ZAMBIA" },
    { label: "ZIMBABWEAN", value: "ZIMBABWEAN", country: "ZIMBABWE" }
];

export const nationalitiesData = countriesAndCitizenshipsData.map(country => ({
    label: country.value.toUpperCase(),
    value: country.value.toUpperCase()
}));