export const countryCodes = [
  { code: 'AF', name: "Afghanistan", dialCode: '+93', flag: 'https://flagsapi.com/AF/flat/32.png' },
  { code: 'AL', name: "Albania", dialCode: '+355', flag: 'https://flagsapi.com/AL/flat/32.png' },
  { code: 'DZ', name: "Algeria", dialCode: '+213', flag: 'https://flagsapi.com/DZ/flat/32.png' },
  { code: 'AS', name: "American Samoa", dialCode: '+1-684', flag: 'https://flagsapi.com/AS/flat/32.png' },
  { code: 'AD', name: "Andorra", dialCode: '+376', flag: 'https://flagsapi.com/AD/flat/32.png' },
  { code: 'AO', name: "Angola", dialCode: '+244', flag: 'https://flagsapi.com/AO/flat/32.png' },
  { code: 'AI', name: "Anguilla", dialCode: '+1-264', flag: 'https://flagsapi.com/AI/flat/32.png' },
  { code: 'AQ', name: "Antarctica", dialCode: '+672', flag: 'https://flagsapi.com/AQ/flat/32.png' },
  { code: 'AG', name: "Antigua and Barbuda", dialCode: '+1-268', flag: 'https://flagsapi.com/AG/flat/32.png' },
  { code: 'AR', name: "Argentina", dialCode: '+54', flag: 'https://flagsapi.com/AR/flat/32.png' },
  { code: 'AM', name: "Armenia", dialCode: '+374', flag: 'https://flagsapi.com/AM/flat/32.png' },
  { code: 'AW', name: "Aruba", dialCode: '+297', flag: 'https://flagsapi.com/AW/flat/32.png' },
  { code: 'AU', name: "Australia", dialCode: '+61', flag: 'https://flagsapi.com/AU/flat/32.png' },
  { code: 'AT', name: "Austria", dialCode: '+43', flag: 'https://flagsapi.com/AT/flat/32.png' },
  { code: 'AZ', name: "Azerbaijan", dialCode: '+994', flag: 'https://flagsapi.com/AZ/flat/32.png' },
  { code: 'BS', name: "Bahamas", dialCode: '+1-242', flag: 'https://flagsapi.com/BS/flat/32.png' },
  { code: 'BH', name: "Bahrain", dialCode: '+973', flag: 'https://flagsapi.com/BH/flat/32.png' },
  { code: 'BD', name: "Bangladesh", dialCode: '+880', flag: 'https://flagsapi.com/BD/flat/32.png' },
  { code: 'BB', name: "Barbados", dialCode: '+1-246', flag: 'https://flagsapi.com/BB/flat/32.png' },
  { code: 'BY', name: "Belarus", dialCode: '+375', flag: 'https://flagsapi.com/BY/flat/32.png' },
  { code: 'BE', name: "Belgium", dialCode: '+32', flag: 'https://flagsapi.com/BE/flat/32.png' },
  { code: 'BZ', name: "Belize", dialCode: '+501', flag: 'https://flagsapi.com/BZ/flat/32.png' },
  { code: 'BJ', name: "Benin", dialCode: '+229', flag: 'https://flagsapi.com/BJ/flat/32.png' },
  { code: 'BM', name: "Bermuda", dialCode: '+1-441', flag: 'https://flagsapi.com/BM/flat/32.png' },
  { code: 'BT', name: "Bhutan", dialCode: '+975', flag: 'https://flagsapi.com/BT/flat/32.png' },
  { code: 'BO', name: "Bolivia", dialCode: '+591', flag: 'https://flagsapi.com/BO/flat/32.png' },
  { code: 'BA', name: "Bosnia and Herzegovina", dialCode: '+387', flag: 'https://flagsapi.com/BA/flat/32.png' },
  { code: 'BW', name: "Botswana", dialCode: '+267', flag: 'https://flagsapi.com/BW/flat/32.png' },
  { code: 'BR', name: "Brazil", dialCode: '+55', flag: 'https://flagsapi.com/BR/flat/32.png' },
  { code: 'IO', name: "British Indian Ocean Territory", dialCode: '+246', flag: 'https://flagsapi.com/IO/flat/32.png' },
  { code: 'VG', name: "British Virgin Islands", dialCode: '+1-284', flag: 'https://flagsapi.com/VG/flat/32.png' },
  { code: 'BN', name: "Brunei", dialCode: '+673', flag: 'https://flagsapi.com/BN/flat/32.png' },
  { code: 'BG', name: "Bulgaria", dialCode: '+359', flag: 'https://flagsapi.com/BG/flat/32.png' },
  { code: 'BF', name: "Burkina Faso", dialCode: '+226', flag: 'https://flagsapi.com/BF/flat/32.png' },
  { code: 'BI', name: "Burundi", dialCode: '+257', flag: 'https://flagsapi.com/BI/flat/32.png' },
  { code: 'KH', name: "Cambodia", dialCode: '+855', flag: 'https://flagsapi.com/KH/flat/32.png' },
  { code: 'CM', name: "Cameroon", dialCode: '+237', flag: 'https://flagsapi.com/CM/flat/32.png' },
  { code: 'CA', name: "Canada", dialCode: '+1', flag: 'https://flagsapi.com/CA/flat/32.png' },
  { code: 'CV', name: "Cape Verde", dialCode: '+238', flag: 'https://flagsapi.com/CV/flat/32.png' },
  { code: 'KY', name: "Cayman Islands", dialCode: '+1-345', flag: 'https://flagsapi.com/KY/flat/32.png' },
  { code: 'CF', name: "Central African Republic", dialCode: '+236', flag: 'https://flagsapi.com/CF/flat/32.png' },
  { code: 'TD', name: "Chad", dialCode: '+235', flag: 'https://flagsapi.com/TD/flat/32.png' },
  { code: 'CL', name: "Chile", dialCode: '+56', flag: 'https://flagsapi.com/CL/flat/32.png' },
  { code: 'CN', name: "China", dialCode: '+86', flag: 'https://flagsapi.com/CN/flat/32.png' },
  { code: 'CX', name: "Christmas Island", dialCode: '+61', flag: 'https://flagsapi.com/CX/flat/32.png' },
  { code: 'CC', name: "Cocos Islands", dialCode: '+61', flag: 'https://flagsapi.com/CC/flat/32.png' },
  { code: 'CO', name: "Colombia", dialCode: '+57', flag: 'https://flagsapi.com/CO/flat/32.png' },
  { code: 'KM', name: "Comoros", dialCode: '+269', flag: 'https://flagsapi.com/KM/flat/32.png' },
  { code: 'CK', name: "Cook Islands", dialCode: '+682', flag: 'https://flagsapi.com/CK/flat/32.png' },
  { code: 'CR', name: "Costa Rica", dialCode: '+506', flag: 'https://flagsapi.com/CR/flat/32.png' },
  { code: 'HR', name: "Croatia", dialCode: '+385', flag: 'https://flagsapi.com/HR/flat/32.png' },
  { code: 'CU', name: "Cuba", dialCode: '+53', flag: 'https://flagsapi.com/CU/flat/32.png' },
  { code: 'CW', name: "Curacao", dialCode: '+599', flag: 'https://flagsapi.com/CW/flat/32.png' },
  { code: 'CY', name: "Cyprus", dialCode: '+357', flag: 'https://flagsapi.com/CY/flat/32.png' },
  { code: 'CZ', name: "Czech Republic", dialCode: '+420', flag: 'https://flagsapi.com/CZ/flat/32.png' },
  { code: 'CD', name: "Democratic Republic of the Congo", dialCode: '+243', flag: 'https://flagsapi.com/CD/flat/32.png' },
  { code: 'DK', name: "Denmark", dialCode: '+45', flag: 'https://flagsapi.com/DK/flat/32.png' },
  { code: 'DJ', name: "Djibouti", dialCode: '+253', flag: 'https://flagsapi.com/DJ/flat/32.png' },
  { code: 'DM', name: "Dominica", dialCode: '+1-767', flag: 'https://flagsapi.com/DM/flat/32.png' },
  { code: 'DO', name: "Dominican Republic", dialCode: '+1-809, +1-829, +1-849', flag: 'https://flagsapi.com/DO/flat/32.png' },
  { code: 'TL', name: "East Timor", dialCode: '+670', flag: 'https://flagsapi.com/TL/flat/32.png' },
  { code: 'EC', name: "Ecuador", dialCode: '+593', flag: 'https://flagsapi.com/EC/flat/32.png' },
  { code: 'EG', name: "Egypt", dialCode: '+20', flag: 'https://flagsapi.com/EG/flat/32.png' },
  { code: 'SV', name: "El Salvador", dialCode: '+503', flag: 'https://flagsapi.com/SV/flat/32.png' },
  { code: 'GQ', name: "Equatorial Guinea", dialCode: '+240', flag: 'https://flagsapi.com/GQ/flat/32.png' },
  { code: 'ER', name: "Eritrea", dialCode: '+291', flag: 'https://flagsapi.com/ER/flat/32.png' },
  { code: 'EE', name: "Estonia", dialCode: '+372', flag: 'https://flagsapi.com/EE/flat/32.png' },
  { code: 'ET', name: "Ethiopia", dialCode: '+251', flag: 'https://flagsapi.com/ET/flat/32.png' },
  { code: 'FK', name: "Falkland Islands", dialCode: '+500', flag: 'https://flagsapi.com/FK/flat/32.png' },
  { code: 'FO', name: "Faroe Islands", dialCode: '+298', flag: 'https://flagsapi.com/FO/flat/32.png' },
  { code: 'FJ', name: "Fiji", dialCode: '+679', flag: 'https://flagsapi.com/FJ/flat/32.png' },
  { code: 'FI', name: "Finland", dialCode: '+358', flag: 'https://flagsapi.com/FI/flat/32.png' },
  { code: 'FR', name: "France", dialCode: '+33', flag: 'https://flagsapi.com/FR/flat/32.png' },
  { code: 'PF', name: "French Polynesia", dialCode: '+689', flag: 'https://flagsapi.com/PF/flat/32.png' },
  { code: 'GA', name: "Gabon", dialCode: '+241', flag: 'https://flagsapi.com/GA/flat/32.png' },
  { code: 'GM', name: "Gambia", dialCode: '+220', flag: 'https://flagsapi.com/GM/flat/32.png' },
  { code: 'GE', name: "Georgia", dialCode: '+995', flag: 'https://flagsapi.com/GE/flat/32.png' },
  { code: 'DE', name: "Germany", dialCode: '+49', flag: 'https://flagsapi.com/DE/flat/32.png' },
  { code: 'GH', name: "Ghana", dialCode: '+233', flag: 'https://flagsapi.com/GH/flat/32.png' },
  { code: 'GI', name: "Gibraltar", dialCode: '+350', flag: 'https://flagsapi.com/GI/flat/32.png' },
  { code: 'GR', name: "Greece", dialCode: '+30', flag: 'https://flagsapi.com/GR/flat/32.png' },
  { code: 'GL', name: "Greenland", dialCode: '+299', flag: 'https://flagsapi.com/GL/flat/32.png' },
  { code: 'GD', name: "Grenada", dialCode: '+1-473', flag: 'https://flagsapi.com/GD/flat/32.png' },
  { code: 'GU', name: "Guam", dialCode: '+1-671', flag: 'https://flagsapi.com/GU/flat/32.png' },
  { code: 'GT', name: "Guatemala", dialCode: '+502', flag: 'https://flagsapi.com/GT/flat/32.png' },
  { code: 'GG', name: "Guernsey", dialCode: '+44-1481', flag: 'https://flagsapi.com/GG/flat/32.png' },
  { code: 'GN', name: "Guinea", dialCode: '+224', flag: 'https://flagsapi.com/GN/flat/32.png' },
  { code: 'GW', name: "Guinea-Bissau", dialCode: '+245', flag: 'https://flagsapi.com/GW/flat/32.png' },
  { code: 'GY', name: "Guyana", dialCode: '+592', flag: 'https://flagsapi.com/GY/flat/32.png' },
  { code: 'HT', name: "Haiti", dialCode: '+509', flag: 'https://flagsapi.com/HT/flat/32.png' },
  { code: 'HN', name: "Honduras", dialCode: '+504', flag: 'https://flagsapi.com/HN/flat/32.png' },
  { code: 'HK', name: "Hong Kong", dialCode: '+852', flag: 'https://flagsapi.com/HK/flat/32.png' },
  { code: 'HU', name: "Hungary", dialCode: '+36', flag: 'https://flagsapi.com/HU/flat/32.png' },
  { code: 'IS', name: "Iceland", dialCode: '+354', flag: 'https://flagsapi.com/IS/flat/32.png' },
  { code: 'IN', name: "India", dialCode: '+91', flag: 'https://flagsapi.com/IN/flat/32.png' },
  { code: 'ID', name: "Indonesia", dialCode: '+62', flag: 'https://flagsapi.com/ID/flat/32.png' },
  { code: 'IR', name: "Iran", dialCode: '+98', flag: 'https://flagsapi.com/IR/flat/32.png' },
  { code: 'IQ', name: "Iraq", dialCode: '+964', flag: 'https://flagsapi.com/IQ/flat/32.png' },
  { code: 'IE', name: "Ireland", dialCode: '+353', flag: 'https://flagsapi.com/IE/flat/32.png' },
  { code: 'IM', name: "Isle of Man", dialCode: '+44-1624', flag: 'https://flagsapi.com/IM/flat/32.png' },
  { code: 'IL', name: "Israel", dialCode: '+972', flag: 'https://flagsapi.com/IL/flat/32.png' },
  { code: 'IT', name: "Italy", dialCode: '+39', flag: 'https://flagsapi.com/IT/flat/32.png' },
  { code: 'CI', name: "Ivory Coast", dialCode: '+225', flag: 'https://flagsapi.com/CI/flat/32.png' },
  { code: 'JM', name: "Jamaica", dialCode: '+1-876', flag: 'https://flagsapi.com/JM/flat/32.png' },
  { code: 'JP', name: "Japan", dialCode: '+81', flag: 'https://flagsapi.com/JP/flat/32.png' },
  { code: 'JE', name: "Jersey", dialCode: '+44-1534', flag: 'https://flagsapi.com/JE/flat/32.png' },
  { code: 'JO', name: "Jordan", dialCode: '+962', flag: 'https://flagsapi.com/JO/flat/32.png' },
  { code: 'KZ', name: "Kazakhstan", dialCode: '+7', flag: 'https://flagsapi.com/KZ/flat/32.png' },
  { code: 'KE', name: "Kenya", dialCode: '+254', flag: 'https://flagsapi.com/KE/flat/32.png' },
  { code: 'KI', name: "Kiribati", dialCode: '+686', flag: 'https://flagsapi.com/KI/flat/32.png' },
  { code: 'XK', name: "Kosovo", dialCode: '+383', flag: 'https://flagsapi.com/XK/flat/32.png' },
  { code: 'KW', name: "Kuwait", dialCode: '+965', flag: 'https://flagsapi.com/KW/flat/32.png' },
  { code: 'KG', name: "Kyrgyzstan", dialCode: '+996', flag: 'https://flagsapi.com/KG/flat/32.png' },
  { code: 'LA', name: "Laos", dialCode: '+856', flag: 'https://flagsapi.com/LA/flat/32.png' },
  { code: 'LV', name: "Latvia", dialCode: '+371', flag: 'https://flagsapi.com/LV/flat/32.png' },
  { code: 'LB', name: "Lebanon", dialCode: '+961', flag: 'https://flagsapi.com/LB/flat/32.png' },
  { code: 'LS', name: "Lesotho", dialCode: '+266', flag: 'https://flagsapi.com/LS/flat/32.png' },
  { code: 'LR', name: "Liberia", dialCode: '+231', flag: 'https://flagsapi.com/LR/flat/32.png' },
  { code: 'LY', name: "Libya", dialCode: '+218', flag: 'https://flagsapi.com/LY/flat/32.png' },
  { code: 'LI', name: "Liechtenstein", dialCode: '+423', flag: 'https://flagsapi.com/LI/flat/32.png' },
  { code: 'LT', name: "Lithuania", dialCode: '+370', flag: 'https://flagsapi.com/LT/flat/32.png' },
  { code: 'LU', name: "Luxembourg", dialCode: '+352', flag: 'https://flagsapi.com/LU/flat/32.png' },
  { code: 'MO', name: "Macao", dialCode: '+853', flag: 'https://flagsapi.com/MO/flat/32.png' },
  { code: 'MK', name: "Macedonia", dialCode: '+389', flag: 'https://flagsapi.com/MK/flat/32.png' },
  { code: 'MG', name: "Madagascar", dialCode: '+261', flag: 'https://flagsapi.com/MG/flat/32.png' },
  { code: 'MW', name: "Malawi", dialCode: '+265', flag: 'https://flagsapi.com/MW/flat/32.png' },
  { code: 'MY', name: "Malaysia", dialCode: '+60', flag: 'https://flagsapi.com/MY/flat/32.png' },
  { code: 'MV', name: "Maldives", dialCode: '+960', flag: 'https://flagsapi.com/MV/flat/32.png' },
  { code: 'ML', name: "Mali", dialCode: '+223', flag: 'https://flagsapi.com/ML/flat/32.png' },
  { code: 'MT', name: "Malta", dialCode: '+356', flag: 'https://flagsapi.com/MT/flat/32.png' },
  { code: 'MH', name: "Marshall Islands", dialCode: '+692', flag: 'https://flagsapi.com/MH/flat/32.png' },
  { code: 'MR', name: "Mauritania", dialCode: '+222', flag: 'https://flagsapi.com/MR/flat/32.png' },
  { code: 'MU', name: "Mauritius", dialCode: '+230', flag: 'https://flagsapi.com/MU/flat/32.png' },
  { code: 'YT', name: "Mayotte", dialCode: '+262', flag: 'https://flagsapi.com/YT/flat/32.png' },
  { code: 'MX', name: "Mexico", dialCode: '+52', flag: 'https://flagsapi.com/MX/flat/32.png' },
  { code: 'FM', name: "Micronesia", dialCode: '+691', flag: 'https://flagsapi.com/FM/flat/32.png' },
  { code: 'MD', name: "Moldova", dialCode: '+373', flag: 'https://flagsapi.com/MD/flat/32.png' },
  { code: 'MC', name: "Monaco", dialCode: '+377', flag: 'https://flagsapi.com/MC/flat/32.png' },
  { code: 'MN', name: "Mongolia", dialCode: '+976', flag: 'https://flagsapi.com/MN/flat/32.png' },
  { code: 'ME', name: "Montenegro", dialCode: '+382', flag: 'https://flagsapi.com/ME/flat/32.png' },
  { code: 'MS', name: "Montserrat", dialCode: '+1-664', flag: 'https://flagsapi.com/MS/flat/32.png' },
  { code: 'MA', name: "Morocco", dialCode: '+212', flag: 'https://flagsapi.com/MA/flat/32.png' },
  { code: 'MZ', name: "Mozambique", dialCode: '+258', flag: 'https://flagsapi.com/MZ/flat/32.png' },
  { code: 'MM', name: "Myanmar", dialCode: '+95', flag: 'https://flagsapi.com/MM/flat/32.png' },
  { code: 'NA', name: "Namibia", dialCode: '+264', flag: 'https://flagsapi.com/NA/flat/32.png' },
  { code: 'NR', name: "Nauru", dialCode: '+674', flag: 'https://flagsapi.com/NR/flat/32.png' },
  { code: 'NP', name: "Nepal", dialCode: '+977', flag: 'https://flagsapi.com/NP/flat/32.png' },
  { code: 'NL', name: "Netherlands", dialCode: '+31', flag: 'https://flagsapi.com/NL/flat/32.png' },
  { code: 'AN', name: "Netherlands Antilles", dialCode: '+599', flag: 'https://flagsapi.com/AN/flat/32.png' },
  { code: 'NC', name: "New Caledonia", dialCode: '+687', flag: 'https://flagsapi.com/NC/flat/32.png' },
  { code: 'NZ', name: "New Zealand", dialCode: '+64', flag: 'https://flagsapi.com/NZ/flat/32.png' },
  { code: 'NI', name: "Nicaragua", dialCode: '+505', flag: 'https://flagsapi.com/NI/flat/32.png' },
  { code: 'NE', name: "Niger", dialCode: '+227', flag: 'https://flagsapi.com/NE/flat/32.png' },
  { code: 'NG', name: "Nigeria", dialCode: '+234', flag: 'https://flagsapi.com/NG/flat/32.png' },
  { code: 'NU', name: "Niue", dialCode: '+683', flag: 'https://flagsapi.com/NU/flat/32.png' },
  { code: 'KP', name: "North Korea", dialCode: '+850', flag: 'https://flagsapi.com/KP/flat/32.png' },
  { code: 'MP', name: "Northern Mariana Islands", dialCode: '+1-670', flag: 'https://flagsapi.com/MP/flat/32.png' },
  { code: 'NO', name: "Norway", dialCode: '+47', flag: 'https://flagsapi.com/NO/flat/32.png' },
  { code: 'OM', name: "Oman", dialCode: '+968', flag: 'https://flagsapi.com/OM/flat/32.png' },
  { code: 'PK', name: "Pakistan", dialCode: '+92', flag: 'https://flagsapi.com/PK/flat/32.png' },
  { code: 'PW', name: "Palau", dialCode: '+680', flag: 'https://flagsapi.com/PW/flat/32.png' },
  { code: 'PS', name: "Palestine", dialCode: '+970', flag: 'https://flagsapi.com/PS/flat/32.png' },
  { code: 'PA', name: "Panama", dialCode: '+507', flag: 'https://flagsapi.com/PA/flat/32.png' },
  { code: 'PG', name: "Papua New Guinea", dialCode: '+675', flag: 'https://flagsapi.com/PG/flat/32.png' },
  { code: 'PY', name: "Paraguay", dialCode: '+595', flag: 'https://flagsapi.com/PY/flat/32.png' },
  { code: 'PE', name: "Peru", dialCode: '+51', flag: 'https://flagsapi.com/PE/flat/32.png' },
  { code: 'PH', name: "Philippines", dialCode: '+63', flag: 'https://flagsapi.com/PH/flat/32.png' },
  { code: 'PN', name: "Pitcairn", dialCode: '+64', flag: 'https://flagsapi.com/PN/flat/32.png' },
  { code: 'PL', name: "Poland", dialCode: '+48', flag: 'https://flagsapi.com/PL/flat/32.png' },
  { code: 'PT', name: "Portugal", dialCode: '+351', flag: 'https://flagsapi.com/PT/flat/32.png' },
  { code: 'PR', name: "Puerto Rico", dialCode: '+1-787, +1-939', flag: 'https://flagsapi.com/PR/flat/32.png' },
  { code: 'QA', name: "Qatar", dialCode: '+974', flag: 'https://flagsapi.com/QA/flat/32.png' },
  { code: 'CG', name: "Republic of the Congo", dialCode: '+242', flag: 'https://flagsapi.com/CG/flat/32.png' },
  { code: 'RE', name: "Reunion", dialCode: '+262', flag: 'https://flagsapi.com/RE/flat/32.png' },
  { code: 'RO', name: "Romania", dialCode: '+40', flag: 'https://flagsapi.com/RO/flat/32.png' },
  { code: 'RU', name: "Russia", dialCode: '+7', flag: 'https://flagsapi.com/RU/flat/32.png' },
  { code: 'RW', name: "Rwanda", dialCode: '+250', flag: 'https://flagsapi.com/RW/flat/32.png' },
  { code: 'BL', name: "Saint Barthelemy", dialCode: '+590', flag: 'https://flagsapi.com/BL/flat/32.png' },
  { code: 'SH', name: "Saint Helena", dialCode: '+290', flag: 'https://flagsapi.com/SH/flat/32.png' },
  { code: 'KN', name: "Saint Kitts and Nevis", dialCode: '+1-869', flag: 'https://flagsapi.com/KN/flat/32.png' },
  { code: 'LC', name: "Saint Lucia", dialCode: '+1-758', flag: 'https://flagsapi.com/LC/flat/32.png' },
  { code: 'MF', name: "Saint Martin", dialCode: '+590', flag: 'https://flagsapi.com/MF/flat/32.png' },
  { code: 'PM', name: "Saint Pierre and Miquelon", dialCode: '+508', flag: 'https://flagsapi.com/PM/flat/32.png' },
  { code: 'VC', name: "Saint Vincent and the Grenadines", dialCode: '+1-784', flag: 'https://flagsapi.com/VC/flat/32.png' },
  { code: 'WS', name: "Samoa", dialCode: '+685', flag: 'https://flagsapi.com/WS/flat/32.png' },
  { code: 'SM', name: "San Marino", dialCode: '+378', flag: 'https://flagsapi.com/SM/flat/32.png' },
  { code: 'ST', name: "Sao Tome and Principe", dialCode: '+239', flag: 'https://flagsapi.com/ST/flat/32.png' },
  { code: 'SA', name: "Saudi Arabia", dialCode: '+966', flag: 'https://flagsapi.com/SA/flat/32.png' },
  { code: 'SN', name: "Senegal", dialCode: '+221', flag: 'https://flagsapi.com/SN/flat/32.png' },
  { code: 'RS', name: "Serbia", dialCode: '+381', flag: 'https://flagsapi.com/RS/flat/32.png' },
  { code: 'SC', name: "Seychelles", dialCode: '+248', flag: 'https://flagsapi.com/SC/flat/32.png' },
  { code: 'SL', name: "Sierra Leone", dialCode: '+232', flag: 'https://flagsapi.com/SL/flat/32.png' },
  { code: 'SG', name: "Singapore", dialCode: '+65', flag: 'https://flagsapi.com/SG/flat/32.png' },
  { code: 'SX', name: "Sint Maarten", dialCode: '+1-721', flag: 'https://flagsapi.com/SX/flat/32.png' },
  { code: 'SK', name: "Slovakia", dialCode: '+421', flag: 'https://flagsapi.com/SK/flat/32.png' },
  { code: 'SI', name: "Slovenia", dialCode: '+386', flag: 'https://flagsapi.com/SI/flat/32.png' },
  { code: 'SB', name: "Solomon Islands", dialCode: '+677', flag: 'https://flagsapi.com/SB/flat/32.png' },
  { code: 'SO', name: "Somalia", dialCode: '+252', flag: 'https://flagsapi.com/SO/flat/32.png' },
  { code: 'ZA', name: "South Africa", dialCode: '+27', flag: 'https://flagsapi.com/ZA/flat/32.png' },
  { code: 'KR', name: "South Korea", dialCode: '+82', flag: 'https://flagsapi.com/KR/flat/32.png' },
  { code: 'SS', name: "South Sudan", dialCode: '+211', flag: 'https://flagsapi.com/SS/flat/32.png' },
  { code: 'ES', name: "Spain", dialCode: '+34', flag: 'https://flagsapi.com/ES/flat/32.png' },
  { code: 'LK', name: "Sri Lanka", dialCode: '+94', flag: 'https://flagsapi.com/LK/flat/32.png' },
  { code: 'SD', name: "Sudan", dialCode: '+249', flag: 'https://flagsapi.com/SD/flat/32.png' },
  { code: 'SR', name: "Suriname", dialCode: '+597', flag: 'https://flagsapi.com/SR/flat/32.png' },
  { code: 'SJ', name: "Svalbard and Jan Mayen", dialCode: '+47', flag: 'https://flagsapi.com/SJ/flat/32.png' },
  { code: 'SZ', name: "Swaziland", dialCode: '+268', flag: 'https://flagsapi.com/SZ/flat/32.png' },
  { code: 'SE', name: "Sweden", dialCode: '+46', flag: 'https://flagsapi.com/SE/flat/32.png' },
  { code: 'CH', name: "Switzerland", dialCode: '+41', flag: 'https://flagsapi.com/CH/flat/32.png' },
  { code: 'SY', name: "Syria", dialCode: '+963', flag: 'https://flagsapi.com/SY/flat/32.png' },
  { code: 'TW', name: "Taiwan", dialCode: '+886', flag: 'https://flagsapi.com/TW/flat/32.png' },
  { code: 'TJ', name: "Tajikistan", dialCode: '+992', flag: 'https://flagsapi.com/TJ/flat/32.png' },
  { code: 'TZ', name: "Tanzania", dialCode: '+255', flag: 'https://flagsapi.com/TZ/flat/32.png' },
  { code: 'TH', name: "Thailand", dialCode: '+66', flag: 'https://flagsapi.com/TH/flat/32.png' },
  { code: 'TG', name: "Togo", dialCode: '+228', flag: 'https://flagsapi.com/TG/flat/32.png' },
  { code: 'TK', name: "Tokelau", dialCode: '+690', flag: 'https://flagsapi.com/TK/flat/32.png' },
  { code: 'TO', name: "Tonga", dialCode: '+676', flag: 'https://flagsapi.com/TO/flat/32.png' },
  { code: 'TT', name: "Trinidad and Tobago", dialCode: '+1-868', flag: 'https://flagsapi.com/TT/flat/32.png' },
  { code: 'TN', name: "Tunisia", dialCode: '+216', flag: 'https://flagsapi.com/TN/flat/32.png' },
  { code: 'TR', name: "Turkey", dialCode: '+90', flag: 'https://flagsapi.com/TR/flat/32.png' },
  { code: 'TM', name: "Turkmenistan", dialCode: '+993', flag: 'https://flagsapi.com/TM/flat/32.png' },
  { code: 'TC', name: "Turks and Caicos Islands", dialCode: '+1-649', flag: 'https://flagsapi.com/TC/flat/32.png' },
  { code: 'TV', name: "Tuvalu", dialCode: '+688', flag: 'https://flagsapi.com/TV/flat/32.png' },
  { code: 'VI', name: "U.S. Virgin Islands", dialCode: '+1-340', flag: 'https://flagsapi.com/VI/flat/32.png' },
  { code: 'UG', name: "Uganda", dialCode: '+256', flag: 'https://flagsapi.com/UG/flat/32.png' },
  { code: 'UA', name: "Ukraine", dialCode: '+380', flag: 'https://flagsapi.com/UA/flat/32.png' },
  { code: 'AE', name: "United Arab Emirates", dialCode: '+971', flag: 'https://flagsapi.com/AE/flat/32.png' },
  { code: 'GB', name: "United Kingdom", dialCode: '+44', flag: 'https://flagsapi.com/GB/flat/32.png' },
  { code: 'US', name: "United States", dialCode: '+1', flag: 'https://flagsapi.com/US/flat/32.png' },
  { code: 'UY', name: "Uruguay", dialCode: '+598', flag: 'https://flagsapi.com/UY/flat/32.png' },
  { code: 'UZ', name: "Uzbekistan", dialCode: '+998', flag: 'https://flagsapi.com/UZ/flat/32.png' },
  { code: 'VU', name: "Vanuatu", dialCode: '+678', flag: 'https://flagsapi.com/VU/flat/32.png' },
  { code: 'VA', name: "Vatican", dialCode: '+379', flag: 'https://flagsapi.com/VA/flat/32.png' },
  { code: 'VE', name: "Venezuela", dialCode: '+58', flag: 'https://flagsapi.com/VE/flat/32.png' },
  { code: 'VN', name: "Vietnam", dialCode: '+84', flag: 'https://flagsapi.com/VN/flat/32.png' },
  { code: 'WF', name: "Wallis and Futuna", dialCode: '+681', flag: 'https://flagsapi.com/WF/flat/32.png' },
  { code: 'EH', name: "Western Sahara", dialCode: '+212', flag: 'https://flagsapi.com/EH/flat/32.png' },
  { code: 'YE', name: "Yemen", dialCode: '+967', flag: 'https://flagsapi.com/YE/flat/32.png' },
  { code: 'ZM', name: "Zambia", dialCode: '+260', flag: 'https://flagsapi.com/ZM/flat/32.png' },
  { code: 'ZW', name: "Zimbabwe", dialCode: '+263', flag: 'https://flagsapi.com/ZW/flat/32.png' },
];