export const validIdLetters = {
    0: "Z",
    1: "A",
    2: "B",
    3: "C",
    4: "D",
    5: "E",
    6: "F",
    7: "G",
    8: "H",
    9: "J",
    10: "K",
    11: "L",
    12: "M",
    13: "N",
    14: "P",
    15: "Q",
    16: "R",
    17: "S",
    18: "T",
    19: "V",
    20: "W",
    21: "X",
    22: "Y",
}

export const zimDistricts = {
    "FOREIGNER": "00",
    "BEITBRIDGE": "02",
    "MBERENGWA": "03",
    "BIKITA": "04",
    "BINDURA": "05",
    "BINGA": "06",
    "BUHERA": "07",
    "BULAWAYO": "08",    
    "MUZARABANI": "11",
    "CHIPINGE": "13",
    "CHIREDZI": "14",
    "MAZOWE": "15",
    "FILABUSI": "17",
    "CHIKOMBA": "18",
    "UMZINGWANE": "19",
    "INSIZA": "21",
    "MASVINGO": "22",
    "GOKWE SOUTH": "23",
    "KADOMA": "24",
    "GOROMONZI": "25",
    "GOKWE NORTH": "26",
    "GUTU": "27",
    "GWANDA": "28",
    "GWERU": "29",
    "CHIREDZII": "31",
    "CHEGUTU": "32",
    "NYANGA": "34",
    "BUBI": "35",
    "KARIBA": "37",
    "HURUNGWE": "38",
    "MATOBO": "39",
    "LUPANE": "41",
    "MAKONI": "42",
    "MARONDERA": "43",
    "CHIMANIMANI": "44",
    "MT DARWIN": "45",
    "MUREHWA": "47",
    "MUTOKO": "48",
    "MUDZI": "49",
    "MUTASA": "50",
    "NKAYI": "53",
    "MWENEZI": "54",
    "BULILIMAMANGWE": "56",
    "KWEKWE": "58",
    "SEKE": "59",
    "RUSHINGA": "61",
    "HARARE": "63",
    "BEATRICE": "65",    
    "SHURUGWI": "66",
    "ZVISHAVANE": "67",
    "SHAMVA": "68",
    "MAKONDE": "70",
    "GURUVE": "71",
    "TSHOLOTSHO": "73",
    "MUTARE": "75",
    "MOUNT DARWIN": "76",
    "CHIRUMANZU": "77",
    "HWANGE": "79",
    "HWEDZA": "80",
    "ZAKA": "83",
    "UMGUZA": "84",
    "UZUMBA MARAMBA PFUNGWE": "85",
    "ZVIMBA": "86"
};

export const validZimDistrictCodes = Object.values(zimDistricts)

const zimDistrictsData = Object.keys(zimDistricts).map((district) => ({
    label: district, value: district
}))

export const countryDistricts = {
    "ZIMBABWE": zimDistrictsData,
    "TANZANIA": [
        { label: "ARUSHA", value: "ARUSHA" },
        { label: "BABATI", value: "BABATI" },
        { label: "KARATU", value: "KARATU" },
        { label: "LONGIDO", value: "LONGIDO" },
        { label: "MONDULI", value: "MONDULI" },
        { label: "NGORONGORO", value: "NGORONGORO" },
        { label: "ILALA", value: "ILALA" },
        { label: "KINONDONI", value: "KINONDONI" },
        { label: "TEMEKE", value: "TEMEKE" },
        { label: "UBUNGO", value: "UBUNGO" },
        { label: "KIGAMBONI", value: "KIGAMBONI" },
        { label: "BAHI", value: "BAHI" },
        { label: "CHAMWINO", value: "CHAMWINO" },
        { label: "DODOMA URBAN", value: "DODOMA URBAN" },
        { label: "KONDOA", value: "KONDOA" },
        { label: "KONGWA", value: "KONGWA" },
        { label: "MPWAPWA", value: "MPWAPWA" },
        { label: "CHEMBA", value: "CHEMBA" },
        { label: "MSALALA", value: "MSALALA" },
        { label: "BUKOMBE", value: "BUKOMBE" },
        { label: "GEITA URBAN", value: "GEITA URBAN" },
        { label: "MBOGWE", value: "MBOGWE" },
        { label: "CHATO", value: "CHATO" },
        { label: "NYANG’HWALE", value: "NYANG’HWALE" },
        { label: "IRINGA URBAN", value: "IRINGA URBAN" },
        { label: "KILOLO", value: "KILOLO" },
        { label: "MUFINDI", value: "MUFINDI" },
        { label: "NJOMBE", value: "NJOMBE" },
        { label: "MAKETE", value: "MAKETE" },
        { label: "LUDEWA", value: "LUDEWA" },
        { label: "WANGING'OMBE", value: "WANGING'OMBE" },
        { label: "BUKOBA", value: "BUKOBA" },
        { label: "KIGOMA URBAN", value: "KIGOMA URBAN" },
        { label: "KASULU", value: "KASULU" },
        { label: "KIBONDO", value: "KIBONDO" },
        { label: "UVINZA", value: "UVINZA" },
        { label: "HAI", value: "HAI" },
        { label: "KILIMANJARO URBAN", value: "KILIMANJARO URBAN" },
        { label: "SAME", value: "SAME" },
        { label: "MOSHI", value: "MOSHI" },
        { label: "ROMBO", value: "ROMBO" },
        { label: "MWANGA", value: "MWANGA" },
        { label: "KITETO", value: "KITETO" },
        { label: "MBULU", value: "MBULU" },
        { label: "SIMANJIRO", value: "SIMANJIRO" },
        { label: "BUNDA", value: "BUNDA" },
        { label: "MUSOMA URBAN", value: "MUSOMA URBAN" },
        { label: "SERENGETI", value: "SERENGETI" },
        { label: "TARIME", value: "TARIME" },
        { label: "RORYA", value: "RORYA" },
        { label: "MBEYA URBAN", value: "MBEYA URBAN" },
        { label: "MBOZI", value: "MBOZI" },
        { label: "RUNGWE", value: "RUNGWE" },
        { label: "ILEJE", value: "ILEJE" },
        { label: "CHUNYA", value: "CHUNYA" },
        { label: "SONGWE", value: "SONGWE" },
        { label: "MOROGORO URBAN", value: "MOROGORO URBAN" },
        { label: "KILOMBERO", value: "KILOMBERO" },
        { label: "MVOMERO", value: "MVOMERO" },
        { label: "ULANGA", value: "ULANGA" },
        { label: "GAIRO", value: "GAIRO" },
        { label: "MTWARA URBAN", value: "MTWARA URBAN" },
        { label: "NEWALA", value: "NEWALA" },
        { label: "TANDAHIMBA", value: "TANDAHIMBA" },
        { label: "MASASI", value: "MASASI" },
        { label: "NANYUMBU", value: "NANYUMBU" },
        { label: "MWANZA URBAN", value: "MWANZA URBAN" },
        { label: "MISUNGWI", value: "MISUNGWI" },
        { label: "ILEMELA", value: "ILEMELA" },
        { label: "KWIMBA", value: "KWIMBA" },
        { label: "MAGU", value: "MAGU" },
        { label: "SENGEREMA", value: "SENGEREMA" },
        { label: "UKEREWE", value: "UKEREWE" },
        { label: "NJOMBE URBAN", value: "NJOMBE URBAN" },
        { label: "NJOMBE RURAL", value: "NJOMBE RURAL" },
        { label: "KISARAWE", value: "KISARAWE" },
        { label: "KIBAHA URBAN", value: "KIBAHA URBAN" },
        { label: "BAGAMOYO", value: "BAGAMOYO" },
        { label: "MKURANGA", value: "MKURANGA" },
        { label: "RUFIJI", value: "RUFIJI" },
        { label: "SUMBAWANGA", value: "SUMBAWANGA" },
        { label: "KALAMBO", value: "KALAMBO" },
        { label: "NKASI", value: "NKASI" },
        { label: "MPANDA", value: "MPANDA" },
        { label: "MBINGA", value: "MBINGA" },
        { label: "NAMTUMBO", value: "NAMTUMBO" },
        { label: "NYASA", value: "NYASA" },
        { label: "TUNDURU", value: "TUNDURU" },
        { label: "SHINYANGA URBAN", value: "SHINYANGA URBAN" },
        { label: "KISHAPU", value: "KISHAPU" },
        { label: "NZEGA", value: "NZEGA" },
        { label: "BUSEGA", value: "BUSEGA" },
        { label: "MASWA", value: "MASWA" },
        { label: "MEATU", value: "MEATU" },
        { label: "SIMIYU", value: "SIMIYU" },
        { label: "SINGIDA URBAN", value: "SINGIDA URBAN" },
        { label: "IKUNGI", value: "IKUNGI" },
        { label: "MANYONI", value: "MANYONI" },
        { label: "IRAMBA", value: "IRAMBA" },
        { label: "MBOZI", value: "MBOZI" },
        { label: "MOMBA", value: "MOMBA" },
        { label: "ILEJE", value: "ILEJE" },
        { label: "TABORA URBAN", value: "TABORA URBAN" },
        { label: "URAMBO", value: "URAMBO" },
        { label: "KALIUA", value: "KALIUA" },
        { label: "TANGA URBAN", value: "TANGA URBAN" },
        { label: "PANGANI", value: "PANGANI" },
        { label: "MUHEZA", value: "MUHEZA" },
        { label: "HANDENI", value: "HANDENI" },
        { label: "KOROGWE", value: "KOROGWE" },
        { label: "LUSHOTO", value: "LUSHOTO" },
        { label: "ZANZIBAR URBAN WEST", value: "ZANZIBAR URBAN WEST" },
        { label: "ZANZIBAR NORTH", value: "ZANZIBAR NORTH" }
    ],
    "BOTSWANA": [
        { label: "CENTRAL DISTRICT", value: "CENTRAL DISTRICT" },
        { label: "CHOBE DISTRICT", value: "CHOBE DISTRICT" },
        { label: "GHANZI DISTRICT", value: "GHANZI DISTRICT" },
        { label: "KGALAGADI DISTRICT", value: "KGALAGADI DISTRICT" },
        { label: "KGATLENG DISTRICT", value: "KGATLENG DISTRICT" },
        { label: "KWENENG DISTRICT", value: "KWENENG DISTRICT" },
        { label: "LOBATSE DISTRICT", value: "LOBATSE DISTRICT" },
        { label: "NORTH EAST DISTRICT", value: "NORTH EAST DISTRICT" },
        { label: "NORTH WEST DISTRICT", value: "NORTH WEST DISTRICT" },
        { label: "SOUTHERN DISTRICT", value: "SOUTHERN DISTRICT" },
        { label: "SOUTH EAST DISTRICT", value: "SOUTH EAST DISTRICT" },
        { label: "CENTRAL CITY GABORONE DISTRICT", value: "CENTRAL CITY GABORONE DISTRICT" }
    ],
    "NAMIBIA": [
        { label: "KARAS REGION", value: "KARAS REGION" },
        { label: "ERONGO REGION", value: "ERONGO REGION" },
        { label: "HARDAP REGION", value: "HARDAP REGION" },
        { label: "KARASBURG DISTRICT", value: "KARASBURG DISTRICT" },
        { label: "KAVANGO EAST REGION", value: "KAVANGO EAST REGION" },
        { label: "KAVANGO WEST REGION", value: "KAVANGO WEST REGION" },
        { label: "KHOMAS REGION", value: "KHOMAS REGION" },
        { label: "KUNENE REGION", value: "KUNENE REGION" },
        { label: "OHANGWENA REGION", value: "OHANGWENA REGION" },
        { label: "OMAHEKE REGION", value: "OMAHEKE REGION" },
        { label: "OMUSATI REGION", value: "OMUSATI REGION" },
        { label: "OSHANA REGION", value: "OSHANA REGION" },
        { label: "OSHIKOTO REGION", value: "OSHIKOTO REGION" },
        { label: "OTJOZONDJUPA REGION", value: "OTJOZONDJUPA REGION" },
        { label: "ZAMBEZI REGION", value: "ZAMBEZI REGION" }
    ],
    "LESOTHO": [
        { label: "BEREA", value: "BEREA" },
        { label: "BUTHA-BUTHE", value: "BUTHA-BUTHE" },
        { label: "LERIBE", value: "LERIBE" },
        { label: "MAFETENG", value: "MAFETENG" },
        { label: "MOHALE'S HOEK", value: "MOHALE'S HOEK" },
        { label: "MOKHOTLONG", value: "MOKHOTLONG" },
        { label: "QACHA'S NEK", value: "QACHA'S NEK" },
        { label: "QUTHING", value: "QUTHING" },
        { label: "THABA-TSEKA", value: "THABA-TSEKA" },
        { label: "MASERU (CAPITAL CITY DISTRICT)", value: "MASERU (CAPITAL CITY DISTRICT)" }
    ],
    "SWAZILAND": [
        { label: "HHOHHO", value: "HHOHHO" },
        { label: "LUBOMBO", value: "LUBOMBO" },
        { label: "MANZINI", value: "MANZINI" },
        { label: "SHISELWENI", value: "SHISELWENI" }
    ],
    "KENYA": [
        { label: "BARINGO CENTRAL", value: "BARINGO CENTRAL" },
        { label: "BARINGO NORTH", value: "BARINGO NORTH" },
        { label: "BARINGO SOUTH", value: "BARINGO SOUTH" },
        { label: "ELDAMA RAVINE", value: "ELDAMA RAVINE" },
        { label: "MOGOTIO", value: "MOGOTIO" },
        { label: "TIATY", value: "TIATY" },
        { label: "BOMET CENTRAL", value: "BOMET CENTRAL" },
        { label: "BOMET EAST", value: "BOMET EAST" },
        { label: "CHEPALUNGU", value: "CHEPALUNGU" },
        { label: "KONOIN", value: "KONOIN" },
        { label: "SOTIK", value: "SOTIK" },
        { label: "BUMULA", value: "BUMULA" },
        { label: "KABUCHAI", value: "KABUCHAI" },
        { label: "KANDUYI", value: "KANDUYI" },
        { label: "KIMILILI", value: "KIMILILI" },
        { label: "MT. ELGON", value: "MT. ELGON" },
        { label: "TONGAREN", value: "TONGAREN" },
        { label: "WEBUYE EAST", value: "WEBUYE EAST" },
        { label: "WEBUYE WEST", value: "WEBUYE WEST" },
        { label: "BUDALANGI", value: "BUDALANGI" },
        { label: "BUTULA", value: "BUTULA" },
        { label: "MATAYOS", value: "MATAYOS" },
        { label: "NAMBALE", value: "NAMBALE" },
        { label: "SAMIA", value: "SAMIA" },
        { label: "TESO NORTH", value: "TESO NORTH" },
        { label: "TESO SOUTH", value: "TESO SOUTH" },
        { label: "CHEPKORIO", value: "CHEPKORIO" },
        { label: "KEIYO NORTH", value: "KEIYO NORTH" },
        { label: "KEIYO SOUTH", value: "KEIYO SOUTH" },
        { label: "MARAKWET EAST", value: "MARAKWET EAST" },
        { label: "MARAKWET WEST", value: "MARAKWET WEST" },
        { label: "EMBU EAST", value: "EMBU EAST" },
        { label: "EMBU NORTH", value: "EMBU NORTH" },
        { label: "EMBU WEST", value: "EMBU WEST" },
        { label: "MBEERE NORTH", value: "MBEERE NORTH" },
        { label: "MBEERE SOUTH", value: "MBEERE SOUTH" },
        { label: "FAFI", value: "FAFI" },
        { label: "GARISSA", value: "GARISSA" },
        { label: "HULUGH", value: "HULUGH" },
        { label: "IJARA", value: "IJARA" },
        { label: "LAGDERA", value: "LAGDERA" },
        { label: "BALAMBALA", value: "BALAMBALA" },
        { label: "DADAAB", value: "DADAAB" },
        { label: "GALOLE", value: "GALOLE" },
        { label: "GARSEN", value: "GARSEN" },
        { label: "KIPINI", value: "KIPINI" },
        { label: "HOMA BAY TOWN", value: "HOMA BAY TOWN" },
        { label: "KABONDO KASIPUL", value: "KABONDO KASIPUL" },
        { label: "KARACHUONY", value: "KARACHUONY" },
        { label: "KASIPUL", value: "KASIPUL" },
        { label: "MBITA", value: "MBITA" },
        { label: "NDHIWA", value: "NDHIWA" },
        { label: "RANGWE", value: "RANGWE" },
        { label: "SUBA", value: "SUBA" },
        { label: "GARBATULLA", value: "GARBATULLA" },
        { label: "ISIOL", value: "ISIOL" },
        { label: "MERTI", value: "MERTI" },
        { label: "KAJIADO CENTRAL", value: "KAJIADO CENTRAL" },
        { label: "KAJIADO EAST", value: "KAJIADO EAST" },
        { label: "KAJIADO NORTH", value: "KAJIADO NORTH" },
        { label: "KAJIADO SOUTH", value: "KAJIADO SOUTH" },
        { label: "KAJIADO WEST", value: "KAJIADO WEST" },
        { label: "BUTERE", value: "BUTERE" },
        { label: "IKOLOMANI", value: "IKOLOMANI" },
        { label: "KHWISERO", value: "KHWISERO" },
        { label: "LUGARI", value: "LUGARI" },
        { label: "LURAMBI", value: "LURAMBI" },
        { label: "MALAVA", value: "MALAVA" },
        { label: "MATUNGU", value: "MATUNGU" },
        { label: "MUMIAS EAST", value: "MUMIAS EAST" },
        { label: "MUMIAS WEST", value: "MUMIAS WEST" },
        { label: "NAVAKHOLO", value: "NAVAKHOLO" },
        { label: "AINAMOI", value: "AINAMOI" },
        { label: "BELGUT", value: "BELGUT" },
        { label: "BURETI", value: "BURETI" },
        { label: "KIPKELION EAST", value: "KIPKELION EAST" },
        { label: "KIPKELION WEST", value: "KIPKELION WEST" },
        { label: "LONDIANI", value: "LONDIANI" },
        { label: "GATUNDU NORTH", value: "GATUNDU NORTH" },
        { label: "GATUNDU SOUTH", value: "GATUNDU SOUTH" },
        { label: "GITHUNGURI", value: "GITHUNGURI" },
        { label: "JUJA", value: "JUJA" },
        { label: "KABETE", value: "KABETE" },
        { label: "KIAMBAA", value: "KIAMBAA" },
        { label: "KIKUYU", value: "KIKUYU" },
        { label: "LIMURU", value: "LIMURU" },
        { label: "LARI", value: "LARI" },
        { label: "RUIRU", value: "RUIRU" },
        { label: "THIKA EAST", value: "THIKA EAST" },
        { label: "THIKA WEST", value: "THIKA WEST" },
        { label: "GANZE", value: "GANZE" },
        { label: "KALOLENI", value: "KALOLENI" },
        { label: "KILIFI NORTH", value: "KILIFI NORTH" },
        { label: "KILIFI SOUTH", value: "KILIFI SOUTH" },
        { label: "MAGARINI", value: "MAGARINI" },
        { label: "MALINDI", value: "MALINDI" },
        { label: "RABAI", value: "RABAI" },
        { label: "MATUGA", value: "MATUGA" },
        { label: "KINANGO", value: "KINANGO" },
        { label: "LUNGALUNGA", value: "LUNGALUNGA" },
        { label: "MSAMBWENI", value: "MSAMBWENI" },
        { label: "KIRINYAGA CENTRAL", value: "KIRINYAGA CENTRAL" },
        { label: "KIRINYAGA EAST", value: "KIRINYAGA EAST" },
        { label: "KIRINYAGA WEST", value: "KIRINYAGA WEST" },
        { label: "MWEA EAST", value: "MWEA EAST" },
        { label: "MWEA WEST", value: "MWEA WEST" },
        { label: "BOBASI", value: "BOBASI" },
        { label: "BONCHARI", value: "BONCHARI" },
        { label: "BOMACHOGE BORABU", value: "BOMACHOGE BORABU" },
        { label: "BOMACHOGE CHACHE", value: "BOMACHOGE CHACHE" },
        { label: "KITUTU CHACHE NORTH", value: "KITUTU CHACHE NORTH" },
        { label: "KITUTU CHACHE SOUTH", value: "KITUTU CHACHE SOUTH" },
        { label: "NYARIBARI MASABA", value: "NYARIBARI MASABA" },
        { label: "NYARIBARI CHACHE", value: "NYARIBARI CHACHE" },
        { label: "SOUTH MUGIRANGO", value: "SOUTH MUGIRANGO" },
        { label: "KISUMU CENTRAL", value: "KISUMU CENTRAL" },
        { label: "KISUMU EAST", value: "KISUMU EAST" },
        { label: "KISUMU WEST", value: "KISUMU WEST" },
        { label: "MUHORONI", value: "MUHORONI" },
        { label: "NYAKACH", value: "NYAKACH" },
        { label: "NYANDO", value: "NYANDO" },
        { label: "SEME", value: "SEME" },
        { label: "KITUI CENTRAL", value: "KITUI CENTRAL" },
        { label: "KITUI EAST", value: "KITUI EAST" },
        { label: "KITUI RURAL", value: "KITUI RURAL" },
        { label: "KITUI SOUTH", value: "KITUI SOUTH" },
        { label: "KITUI WEST", value: "KITUI WEST" },
        { label: "MWINGI CENTRAL", value: "MWINGI CENTRAL" },
        { label: "MWINGI NORTH", value: "MWINGI NORTH" },
        { label: "MWINGI WEST", value: "MWINGI WEST" },
        { label: "KALOLENI", value: "KALOLENI" },
        { label: "MALINDI", value: "MALINDI" },
        { label: "MAGARINI", value: "MAGARINI" },
        { label: "LAMU EAST", value: "LAMU EAST" },
        { label: "LAMU WEST", value: "LAMU WEST" },
        { label: "MACHAKOS TOWN", value: "MACHAKOS TOWN" },
        { label: "KANGUNDO", value: "KANGUNDO" },
        { label: "KATHIANI", value: "KATHIANI" },
        { label: "MASINGA", value: "MASINGA" },
        { label: "MATUNGULU", value: "MATUNGULU" },
        { label: "MWALA", value: "MWALA" },
        { label: "YATTA", value: "YATTA" },
        { label: "KILOME", value: "KILOME" },
        { label: "KAITI", value: "KAITI" },
        { label: "KIBWEZI EAST", value: "KIBWEZI EAST" },
        { label: "KIBWEZI WEST", value: "KIBWEZI WEST" },
        { label: "MAKUENI", value: "MAKUENI" },
        { label: "MANDERA EAST", value: "MANDERA EAST" },
        { label: "MANDERA NORTH", value: "MANDERA NORTH" },
        { label: "MANDERA SOUTH", value: "MANDERA SOUTH" },
        { label: "MANDERA WEST", value: "MANDERA WEST" },
        { label: "LAFEY", value: "LAFEY" },
        { label: "BANISA", value: "BANISA" },
        { label: "LAISAMIS", value: "LAISAMIS" },
        { label: "MOYALE", value: "MOYALE" },
        { label: "NORTH HORR", value: "NORTH HORR" },
        { label: "SAKU", value: "SAKU" },
        { label: "BUURI", value: "BUURI" },
        { label: "CENTRAL IMENTI", value: "CENTRAL IMENTI" },
        { label: "IGEMBE CENTRAL", value: "IGEMBE CENTRAL" },
        { label: "IGEMBE NORTH", value: "IGEMBE NORTH" },
        { label: "IGEMBE SOUTH", value: "IGEMBE SOUTH" },
        { label: "NORTH IMENTI", value: "NORTH IMENTI" },
        { label: "SOUTH IMENTI", value: "SOUTH IMENTI" },
        { label: "TIGANIA EAST", value: "TIGANIA EAST" },
        { label: "TIGANIA WEST", value: "TIGANIA WEST" },
        { label: "AWENDO", value: "AWENDO" },
        { label: "KURIA EAST", value: "KURIA EAST" },
        { label: "KURIA WEST", value: "KURIA WEST" },
        { label: "NYATIKE", value: "NYATIKE" },
        { label: "RONGO", value: "RONGO" },
        { label: "SUNA EAST", value: "SUNA EAST" },
        { label: "SUNA WEST", value: "SUNA WEST" },
        { label: "URIRI", value: "URIRI" },
        { label: "CHANGAMWE", value: "CHANGAMWE" },
        { label: "JOMVU", value: "JOMVU" },
        { label: "KISAUNI", value: "KISAUNI" },
        { label: "LIKONI", value: "LIKONI" },
        { label: "MVITA", value: "MVITA" },
        { label: "NYALI", value: "NYALI" },
        { label: "GATANGA", value: "GATANGA" },
        { label: "KANGEMA", value: "KANGEMA" },
        { label: "KIGUMO", value: "KIGUMO" },
        { label: "MATHIOYA", value: "MATHIOYA" },
        { label: "MARAGUA", value: "MARAGUA" },
        { label: "KANDARA", value: "KANDARA" },
        { label: "KAMUKUNJI", value: "KAMUKUNJI" },
        { label: "EMBAKASI EAST", value: "EMBAKASI EAST" },
        { label: "EMBAKASI SOUTH", value: "EMBAKASI SOUTH" },
        { label: "EMBAKASI CENTRAL", value: "EMBAKASI CENTRAL" },
        { label: "EMBAKASI NORTH", value: "EMBAKASI NORTH" },
        { label: "EMBAKASI WEST", value: "EMBAKASI WEST" },
        { label: "KASARANI", value: "KASARANI" },
        { label: "DAGORETI NORTH", value: "DAGORETI NORTH" },
        { label: "DAGORETI SOUTH", value: "DAGORETI SOUTH" },
        { label: "KIBRA", value: "KIBRA" },
        { label: "LANGATA", value: "LANGATA" },
        { label: "MATHARE", value: "MATHARE" },
        { label: "RUARAKA", value: "RUARAKA" },
        { label: "STAREHE", value: "STAREHE" },
        { label: "WESTLANDS", value: "WESTLANDS" },
        { label: "BAHATI", value: "BAHATI" },
        { label: "GILGIL", value: "GILGIL" },
        { label: "KURESOIN NORTH", value: "KURESOIN NORTH" },
        { label: "KURESOIN SOUTH", value: "KURESOIN SOUTH" },
        { label: "MOLO", value: "MOLO" },
        { label: "NAIVASHA", value: "NAIVASHA" },
        { label: "NAKURU EAST", value: "NAKURU EAST" },
        { label: "NAKURU WEST", value: "NAKURU WEST" },
        { label: "NJORDO", value: "NJORDO" },
        { label: "RONGAI", value: "RONGAI" },
        { label: "SUBUKIA", value: "SUBUKIA" },
        { label: "ALDAI", value: "ALDAI" },
        { label: "CHESUMEI", value: "CHESUMEI" },
        { label: "EMGWEN", value: "EMGWEN" },
        { label: "MOSOP", value: "MOSOP" },
        { label: "NANDI HILLS", value: "NANDI HILLS" },
        { label: "TINDERET", value: "TINDERET" },
        { label: "NAROK EAST", value: "NAROK EAST" },
        { label: "NAROK NORTH", value: "NAROK NORTH" },
        { label: "NAROK SOUTH", value: "NAROK SOUTH" },
        { label: "NAROK WEST", value: "NAROK WEST" },
        { label: "TRANS MARA EAST", value: "TRANS MARA EAST" },
        { label: "TRANS MARA WEST", value: "TRANS MARA WEST" },
        { label: "BORABU", value: "BORABU" },
        { label: "MASABA NORTH", value: "MASABA NORTH" },
        { label: "NYAMIRA NORTH", value: "NYAMIRA NORTH" },
        { label: "NYAMIRA SOUTH", value: "NYAMIRA SOUTH" },
        { label: "KIPIPIRI", value: "KIPIPIRI" },
        { label: "KINANGOP", value: "KINANGOP" },
        { label: "NDARAGWA", value: "NDARAGWA" },
        { label: "OL JORO OROK", value: "OL JORO OROK" },
        { label: "TETU", value: "TETU" },
        { label: "KIENI EAST", value: "KIENI EAST" },
        { label: "KIENI WEST", value: "KIENI WEST" },
        { label: "MATHIRA EAST", value: "MATHIRA EAST" },
        { label: "MATHIRA WEST", value: "MATHIRA WEST" },
        { label: "MUKURWEINI", value: "MUKURWEINI" },
        { label: "NYERI TOWN", value: "NYERI TOWN" },
        { label: "SAMBURU CENTRAL", value: "SAMBURU CENTRAL" },
        { label: "SAMBURU EAST", value: "SAMBURU EAST" },
        { label: "SAMBURU NORTH", value: "SAMBURU NORTH" },
        { label: "ALEGO USONGA", value: "ALEGO USONGA" },
        { label: "BONDO", value: "BONDO" },
        { label: "GEM", value: "GEM" },
        { label: "RARIEDA", value: "RARIEDA" },
        { label: "UGENYA", value: "UGENYA" },
        { label: "UGUNJA", value: "UGUNJA" },
        { label: "MWATATE", value: "MWATATE" },
        { label: "TAVETA", value: "TAVETA" },
        { label: "VOI", value: "VOI" },
        { label: "WUNDANYI", value: "WUNDANYI" },
        { label: "BURA", value: "BURA" },
        { label: "GALOLE", value: "GALOLE" },
        { label: "GARSEN", value: "GARSEN" },
        { label: "CHUKA", value: "CHUKA" },
        { label: "IGAMBANGOMBE", value: "IGAMBANGOMBE" },
        { label: "MAARA", value: "MAARA" },
        { label: "THARAKA NORTH", value: "THARAKA NORTH" },
        { label: "THARAKA SOUTH", value: "THARAKA SOUTH" },
        { label: "CHERANGANY", value: "CHERANGANY" },
        { label: "KWANZA", value: "KWANZA" },
        { label: "ENDEBESS", value: "ENDEBESS" },
        { label: "SABOTI", value: "SABOTI" },
        { label: "TURKANA CENTRAL", value: "TURKANA CENTRAL" },
        { label: "TURKANA EAST", value: "TURKANA EAST" },
        { label: "TURKANA NORTH", value: "TURKANA NORTH" },
        { label: "TURKANA SOUTH", value: "TURKANA SOUTH" },
        { label: "TURKANA WEST", value: "TURKANA WEST" },
        { label: "LOIMA", value: "LOIMA" },
        { label: "AINABKOI", value: "AINABKOI" },
        { label: "KESSES", value: "KESSES" },
        { label: "MOIBEN", value: "MOIBEN" },
        { label: "SOY", value: "SOY" },
        { label: "TURBO", value: "TURBO" },
        { label: "SABATIA", value: "SABATIA" },
        { label: "HAMISI", value: "HAMISI" },
        { label: "EMUHAYA", value: "EMUHAYA" },
        { label: "LUANDA", value: "LUANDA" },
        { label: "ELDAS", value: "ELDAS" },
        { label: "TARBAJ", value: "TARBAJ" },
        { label: "WAJIR EAST", value: "WAJIR EAST" },
        { label: "WAJIR NORTH", value: "WAJIR NORTH" },
        { label: "WAJIR SOUTH", value: "WAJIR SOUTH" },
        { label: "WAJIR WEST", value: "WAJIR WEST" },
        { label: "CHEPARERIA", value: "CHEPARERIA" },
        { label: "POKOT CENTRAL", value: "POKOT CENTRAL" },
        { label: "POKOT NORTH", value: "POKOT NORTH" },
        { label: "POKOT SOUTH", value: "POKOT SOUTH" },
        { label: "WEST POKOT", value: "WEST POKOT" }
    ],
    "MALAWI": [
        { label: "BALAKA", value: "BALAKA" },
        { label: "BLANTYRE", value: "BLANTYRE" },
        { label: "CHIKWAWA", value: "CHIKWAWA" },
        { label: "CHIRADZULU", value: "CHIRADZULU" },
        { label: "CHITIPA", value: "CHITIPA" },
        { label: "DEDZA", value: "DEDZA" },
        { label: "DOWA", value: "DOWA" },
        { label: "KARONGA", value: "KARONGA" },
        { label: "KASUNGU", value: "KASUNGU" },
        { label: "LIKOMA", value: "LIKOMA" },
        { label: "LILONGWE", value: "LILONGWE" },
        { label: "MACHINGA", value: "MACHINGA" },
        { label: "MANGOCHI", value: "MANGOCHI" },
        { label: "MCHINJI", value: "MCHINJI" },
        { label: "MULANJE", value: "MULANJE" },
        { label: "MWANZA", value: "MWANZA" },
        { label: "MZIMBA", value: "MZIMBA" },
        { label: "NENO", value: "NENO" },
        { label: "NKHATA BAY", value: "NKHATA BAY" },
        { label: "NKHOTAKOTA", value: "NKHOTAKOTA" },
        { label: "NSANJE", value: "NSANJE" },
        { label: "NTCHEU", value: "NTCHEU" },
        { label: "NTCHISI", value: "NTCHISI" },
        { label: "PHALOMBE", value: "PHALOMBE" },
        { label: "RUMPHI", value: "RUMPHI" },
        { label: "SALIMA", value: "SALIMA" },
        { label: "THYOLO", value: "THYOLO" },
        { label: "ZOMBA", value: "ZOMBA" }
    ],
    "ZAMBIA": [
        { label: "CHIBOMBO", value: "CHIBOMBO" },
        { label: "CHISAMBA", value: "CHISAMBA" },
        { label: "CHITAMBO", value: "CHITAMBO" },
        { label: "KABWE", value: "KABWE" },
        { label: "KAPIRI MPOSHI", value: "KAPIRI MPOSHI" },
        { label: "LUANO", value: "LUANO" },
        { label: "MKUSHI", value: "MKUSHI" },
        { label: "MUMBWA", value: "MUMBWA" },
        { label: "NGABWE", value: "NGABWE" },
        { label: "SERENJE", value: "SERENJE" },
        { label: "SHIBUYUNJI", value: "SHIBUYUNJI" },
        { label: "CHILILABOMBWE", value: "CHILILABOMBWE" },
        { label: "CHINGOLA", value: "CHINGOLA" },
        { label: "KALULUSHI", value: "KALULUSHI" },
        { label: "KITWE", value: "KITWE" },
        { label: "LUANSHYA", value: "LUANSHYA" },
        { label: "LUFWANYAMA", value: "LUFWANYAMA" },
        { label: "MASAITI", value: "MASAITI" },
        { label: "MPONGWE", value: "MPONGWE" },
        { label: "MUFULIRA", value: "MUFULIRA" },
        { label: "NDOLA", value: "NDOLA" },
        { label: "CHADIZA", value: "CHADIZA" },
        { label: "CHAMA", value: "CHAMA" },
        { label: "CHASEFU", value: "CHASEFU" },
        { label: "CHIPANGALI", value: "CHIPANGALI" },
        { label: "CHIPATA", value: "CHIPATA" },
        { label: "KASENENGWA", value: "KASENENGWA" },
        { label: "KATETE", value: "KATETE" },
        { label: "LUMEZI", value: "LUMEZI" },
        { label: "LUNDAZI", value: "LUNDAZI" },
        { label: "LUSANGAZI", value: "LUSANGAZI" },
        { label: "MAMBWE", value: "MAMBWE" },
        { label: "NYIMBA", value: "NYIMBA" },
        { label: "PETAUKE", value: "PETAUKE" },
        { label: "SINDA", value: "SINDA" },
        { label: "VUBWI", value: "VUBWI" },
        { label: "CHEMBE", value: "CHEMBE" },
        { label: "CHIENGI", value: "CHIENGI" },
        { label: "CHIFUNABULI", value: "CHIFUNABULI" },
        { label: "CHIPILI", value: "CHIPILI" },
        { label: "KAWAMBWA", value: "KAWAMBWA" },
        { label: "LUNGA", value: "LUNGA" },
        { label: "MANSA", value: "MANSA" },
        { label: "MILENGE", value: "MILENGE" },
        { label: "MWANSABOMBWE", value: "MWANSABOMBWE" },
        { label: "MWENSE", value: "MWENSE" },
        { label: "NCHELENGE", value: "NCHELENGE" },
        { label: "SAMFYA", value: "SAMFYA" },
        { label: "CHILANGA", value: "CHILANGA" },
        { label: "CHONGWE", value: "CHONGWE" },
        { label: "KAFUE", value: "KAFUE" },
        { label: "LUANGWA", value: "LUANGWA" },
        { label: "LUSAKA", value: "LUSAKA" },
        { label: "RUFUNSA", value: "RUFUNSA" },
        { label: "CHINSALI", value: "CHINSALI" },
        { label: "ISOKA", value: "ISOKA" },
        { label: "KANCHIBIYA", value: "KANCHIBIYA" },
        { label: "LAVUSHIMANDA", value: "LAVUSHIMANDA" },
        { label: "MAFINGA", value: "MAFINGA" },
        { label: "MPIKA", value: "MPIKA" },
        { label: "NAKONDE", value: "NAKONDE" },
        { label: "SHIWANG'ANDU", value: "SHIWANG'ANDU" },
        { label: "CHILUBI", value: "CHILUBI" },
        { label: "KAPUTA", value: "KAPUTA" },
        { label: "KASAMA", value: "KASAMA" },
        { label: "LUNTE", value: "LUNTE" },
        { label: "LUPOSOSHI", value: "LUPOSOSHI" },
        { label: "LUWINGU", value: "LUWINGU" },
        { label: "MBALA", value: "MBALA" },
        { label: "MPOROKOSO", value: "MPOROKOSO" },
        { label: "MPULUNGU", value: "MPULUNGU" },
        { label: "MUNGWI", value: "MUNGWI" },
        { label: "NSAMA", value: "NSAMA" },
        { label: "SENGA", value: "SENGA" },
        { label: "CHAVUMA", value: "CHAVUMA" },
        { label: "IKELENGE", value: "IKELENGE" },
        { label: "KABOMPO", value: "KABOMPO" },
        { label: "KASEMPA", value: "KASEMPA" },
        { label: "KALUMBILA", value: "KALUMBILA" },
        { label: "MANYINGA", value: "MANYINGA" },
        { label: "MUFUMBWE", value: "MUFUMBWE" },
        { label: "MUSHINDAMO", value: "MUSHINDAMO" },
        { label: "MWINILUNGA", value: "MWINILUNGA" },
        { label: "SOLWEZI", value: "SOLWEZI" },
        { label: "ZAMBEZI", value: "ZAMBEZI" },
        { label: "CHIKANKATA", value: "CHIKANKATA" },
        { label: "CHIRUNDU", value: "CHIRUNDU" },
        { label: "CHOMA", value: "CHOMA" },
        { label: "GWEMBE", value: "GWEMBE" },
        { label: "ITEZHI-TEZHI", value: "ITEZHI-TEZHI" },
        { label: "KALOMO", value: "KALOMO" },
        { label: "KAZUNGULA", value: "KAZUNGULA" },
        { label: "LIVINGSTONE", value: "LIVINGSTONE" },
        { label: "MAZABUKA", value: "MAZABUKA" },
        { label: "MONZE", value: "MONZE" },
        { label: "NAMWALA", value: "NAMWALA" },
        { label: "PEMBA", value: "PEMBA" },
        { label: "SIAVONGA", value: "SIAVONGA" },
        { label: "SINAZONGWE", value: "SINAZONGWE" },
        { label: "ZIMBA", value: "ZIMBA" },
        { label: "KALABO", value: "KALABO" },
        { label: "KAOMA", value: "KAOMA" },
        { label: "LIMULUNGA", value: "LIMULUNGA" },
        { label: "LUAMPA", value: "LUAMPA" },
        { label: "LUKULU", value: "LUKULU" },
        { label: "MITETE", value: "MITETE" },
        { label: "MONGU", value: "MONGU" },
        { label: "MULOBEZI", value: "MULOBEZI" },
        { label: "MWANDI", value: "MWANDI" },
        { label: "NALOLO", value: "NALOLO" },
        { label: "NKEYEMA", value: "NKEYEMA" },
        { label: "SENANGA", value: "SENANGA" },
        { label: "SESHKE", value: "SESHKE" },
        { label: "SHANGOMBO", value: "SHANGOMBO" },
        { label: "SIKONGO", value: "SIKONGO" },
        { label: "SIOMA", value: "SIOMA" }
    ],
    "SOUTH AFRICA": [
        { label: "ALFRED NZO", value: "ALFRED NZO" },
        { label: "AMATHOLE", value: "AMATHOLE" },
        { label: "CHRIS HANI", value: "CHRIS HANI" },
        { label: "JOE GQABI", value: "JOE GQABI" },
        { label: "OR TAMBO", value: "OR TAMBO" },
        { label: "SARAH BAARTMAN", value: "SARAH BAARTMAN" },
        { label: "FEZILE DABI", value: "FEZILE DABI" },
        { label: "LEJWELEPUTSWA", value: "LEJWELEPUTSWA" },
        { label: "MANGAUNG", value: "MANGAUNG" },
        { label: "THABO MOFUTSANYANA", value: "THABO MOFUTSANYANA" },
        { label: "XHARIEP", value: "XHARIEP" },
        { label: "CITY OF EKURHULENI", value: "CITY OF EKURHULENI" },
        { label: "CITY OF JOHANNESBURG", value: "CITY OF JOHANNESBURG" },
        { label: "CITY OF TSHWANE", value: "CITY OF TSHWANE" },
        { label: "SEDIBENG", value: "SEDIBENG" },
        { label: "WEST RAND", value: "WEST RAND" },
        { label: "AMAJUBA", value: "AMAJUBA" },
        { label: "ETHEKWINI", value: "ETHEKWINI" },
        { label: "HARRY GWALA", value: "HARRY GWALA" },
        { label: "ILEMBE", value: "ILEMBE" },
        { label: "KING CETSHWAYO", value: "KING CETSHWAYO" },
        { label: "UGU", value: "UGU" },
        { label: "UMGUNGUNDLOVU", value: "UMGUNGUNDLOVU" },
        { label: "UMKHANYAKUDE", value: "UMKHANYAKUDE" },
        { label: "UMZINYATHI", value: "UMZINYATHI" },
        { label: "UTHUKELA", value: "UTHUKELA" },
        { label: "ZULULAND", value: "ZULULAND" },
        { label: "CAPRICORN", value: "CAPRICORN" },
        { label: "MOPANI", value: "MOPANI" },
        { label: "SEKHUKHUNE", value: "SEKHUKHUNE" },
        { label: "VHEMBE", value: "VHEMBE" },
        { label: "WATERBERG", value: "WATERBERG" },
        { label: "EHLANZENI", value: "EHLANZENI" },
        { label: "GERT SIBANDE", value: "GERT SIBANDE" },
        { label: "NKANGALA", value: "NKANGALA" },
        { label: "BOJANALA PLATINUM", value: "BOJANALA PLATINUM" },
        { label: "DR KENNETH KAUNDA", value: "DR KENNETH KAUNDA" },
        { label: "DR RUTH SEGOMOTSI MOMPATI", value: "DR RUTH SEGOMOTSI MOMPATI" },
        { label: "NGAKA MODIRI MOLEMA", value: "NGAKA MODIRI MOLEMA" },
        { label: "FRANCES BAARD", value: "FRANCES BAARD" },
        { label: "JOHN TAOLO GAETSEWE", value: "JOHN TAOLO GAETSEWE" },
        { label: "NAMAKWA", value: "NAMAKWA" },
        { label: "PIXLEY KA SEME", value: "PIXLEY KA SEME" },
        { label: "ZF MGCWAW", value: "ZF MGCWAW" },
        { label: "CAPE WINELANDS", value: "CAPE WINELANDS" },
        { label: "CENTRAL KAROO", value: "CENTRAL KAROO" },
        { label: "CITY OF CAPE TOWN", value: "CITY OF CAPE TOWN" },
        { label: "GARDEN ROUTE", value: "GARDEN ROUTE" },
        { label: "OVERBERG", value: "OVERBERG" },
        { label: "WEST COAST", value: "WEST COAST" }
    ]
}


export const zimDistrictsShortNames = {
    "BULAWAYO": "BYO",
    "ARCTURUS": "ARC",
    "BEITBRIDGE": "BBG",
    "BUCHWA": "BCW",
    "BINGA": "BGA",
    "BUHERA": "BHR",
    "BINDURA": "BIN",
    
    "BANKET": "BNK",
    "BEATRICE": "BTC",
    "CHECHECHE": "CHE",
    "CHEGUTU": "CHG",
    "CHIVI": "CHI",
    "CHIMANIMANI": "CHM",
    "CHINHOYI": "CHN",
    "CHIPINGE": "CHP",
    "CHIREDZI": "CHR",
    "CHITUNGWIZA": "CHT",
    "CHIRUNDU": "CHU",
    "CHIVHU": "CHV",
    "CIF": "CIF",
    "CHAKARI": "CKI",
    "COLLENBORN": "COL",
    "CONCESSION": "CON",
    
    "CHATSWORTH": "CTW",
    "DOROWA": "DOR",
    "DARWENDALE": "DWD",
    "FILABUSI": "FIL",
    "GOROMONZI": "GMZ",
    "GLENDALE": "GND",
    "GOKWE": "GOK",
    
    "GURUVE": "GUR",
    "GUTU": "GUT",
    
    "GWANDA": "GWA",
    "GWERU": "GWE",
    "HEADLANDS": "HDL",
    "HARARE": "HRE",
    "HOWARD": "HWD",
    "HWANGE": "HWG",
    "INDIA": "IN",
    "JERERA": "JER",
    "JURU": "JRU",
    "KADOMA": "KAD",
    "KARIBA": "KAR",
    "KEZI": "KEZ",
    "KAROI": "KRI",
    "KWEKWE": "KWE",
    "LUPANI": "LUP",
    "MACHEKE": "MAC",
    "MAGUNJE": "MAG",
    "MAMINA": "MAM",
    "MARONDERA": "MAR",
    "MASVINGO": "MAS",
    "MATAGA": "MAT",
    "MBERENGWA": "MBE",
    "MURAMBINDA": "MDA",
    
    "MHANGURA": "MHA",
    "MHONDORO": "MHD",
    "MASHOKO": "MKO",
    "MPANDAWANA": "MPA",
    "MUROMBEDZI": "MRD",
    "MT DARWIN": "MTD",
    "MUTOKO": "MTK",
    "MUTORASHANGA": "MTS",
    "MUTAWATAWA": "MTW",
    "MUREHWA": "MUR",
    "MUTARE": "MUT",
    "MVURWI": "MVR",
    "MVUMA": "MVU",
    "MWENEZI": "MWE",
    "MUZARABANI": "MZB",
    "MUDZI": "MZI",
    "MAZOWE": "MZW",
    "NHEDZIWA": "NHD",
    "NKAYI": "NKA",
    "NORTON": "NTN",
    "NYANYADZI": "NYD",
    "NYANGA": "NYG",
    "NYIKA": "NYK",
    "NZVIMBO": "NZV",
    "PLUMTREE": "PLU",
    "RAFFINGORA": "RAF",
    "REDCLIFF": "RED",
    "RUSHINGA": "RGA",
    "RUSAPE": "RUS",
    "RUWA": "RUW",
    "SADZA": "SAD",
    "SELOUS": "SEL",
    "SHANGANI": "SHA",
    "SHURUGWI": "SHU",
    "SHAMVA": "SMV",
    "TENGWE": "TGW",
    "TRELAWNEY": "TRY",
    "TSHOLOTSHO": "TSH",
    "VICTORIA FALLS": "VIC",
    "WANKIE": "WAN",
    "WEDZA": "WED",
    "ZVISHAVANE": "ZVS"
};