export const zimDistricts = {
    "FOREIGNER": "00",
    "BEITBRIDGE": "02",
    "MBERENGWA": "03",
    "BIKITA": "04",
    "BINDURA": "05",
    "BINGA": "06",
    "BUHERA": "07",
    "BULAWAYO": "08",    
    "MUZARABANI": "11",
    "CHIPINGE": "13",
    "CHIREDZI": "14",
    "MAZOWE": "15",
    "FILABUSI": "17",
    "CHIKOMBA": "18",
    "UMZINGWANE": "19",
    "INSIZA": "21",
    "MASVINGO": "22",
    "GOKWE SOUTH": "23",
    "KADOMA": "24",
    "GOROMONZI": "25",
    "GOKWE NORTH": "26",
    "GUTU": "27",
    "GWANDA": "28",
    "GWERU": "29",
    "CHIREDZII": "31",
    "CHEGUTU": "32",
    "NYANGA": "34",
    "BUBI": "35",
    "KARIBA": "37",
    "HURUNGWE": "38",
    "MATOBO": "39",
    "LUPANE": "41",
    "MAKONI": "42",
    "MARONDERA": "43",
    "CHIMANIMANI": "44",
    "MT DARWIN": "45",
    "MUREHWA": "47",
    "MUTOKO": "48",
    "MUDZI": "49",
    "MUTASA": "50",
    "NKAYI": "53",
    "MWENEZI": "54",
    "BULILIMAMANGWE": "56",
    "KWEKWE": "58",
    "SEKE": "59",
    "RUSHINGA": "61",
    "HARARE": "63",
    "BEATRICE": "65",    
    "SHURUGWI": "66",
    "ZVISHAVANE": "67",
    "SHAMVA": "68",
    "MAKONDE": "70",
    "GURUVE": "71",
    "TSHOLOTSHO": "73",
    "MUTARE": "75",
    "MOUNT DARWIN": "76",
    "CHIRUMANZU": "77",
    "HWANGE": "79",
    "HWEDZA": "80",
    "ZAKA": "83",
    "UMGUZA": "84",
    "UZUMBA MARAMBA PFUNGWE": "85",
    "ZVIMBA": "86"
};
