
export const identificationTypes = [
    { label: "NATIONAL ID", value: "NATIONAL ID" },
    { label: "PASSPORT", value: "PASSPORT" }
];

export const genderList = [
    { label: "MALE", value: "MALE" },
    { label: "FEMALE", value: "FEMALE" }
];

export const races = [
    { label: "BLACK", value: "BLACK" },
    { label: "CAUCASIAN", value: "CAUCASIAN" },
    { label: "MIXED RACE", value: "MIXED RACE" },
    { label: "ASIAN", value: "ASIAN" },
    { label: "ARAB OR MIDDLE EASTERN", value: "ARAB_OR_MIDDLE_EASTERN" },
    { label: "LATINO", value: "LATINO" },
    { label: "HISPANIC", value: "HISPANIC" },
    { label: "ROMANI", value: "ROMANI" },
    { label: "BIRACIAL", value: "BIRACIAL" },
    { label: "MULTIRACIAL", value: "MULTIRACIAL" },
];

export const citizenshipStatuses = [
    { label: 'CITIZEN', value: 'CITIZEN' },
    { label: 'PERMANENT RESIDENT', value: 'PERMANENT RESIDENT' },
    { label: 'TEMPORARY RESIDENT', value: 'TEMPORARY RESIDENT' },
    { label: 'REFUGEE', value: 'REFUGEE' },
    { label: 'STATELESS', value: 'STATELESS' },
    { label: 'NATURALIZED CITIZEN', value: 'NATURALIZED CITIZEN' },
    { label: 'VISA HOLDER', value: 'VISA HOLDER' },
];

export const languagesList = [
    { label: 'ENGLISH', value: 'ENGLISH' },
    { label: 'SHONA', value: 'SHONA' },
    { label: 'NDEBELE', value: 'NDEBELE' },
    { label: 'CHINESE', value: 'CHINESE' },
    { label: 'AFRIKAANS', value: 'AFRIKAANS' },
    { label: 'FRENCH', value: 'FRENCH' },
    { label: 'PORTUGUESE', value: 'PORTUGUESE' },
    { label: 'HINDI', value: 'HINDI' },
    { label: 'ARABIC', value: 'ARABIC' },
    { label: 'SPANISH', value: 'SPANISH' },
    { label: 'GERMAN', value: 'GERMAN' },
    { label: 'ITALIAN', value: 'ITALIAN' },
    { label: 'RUSSIAN', value: 'RUSSIAN' },
    { label: 'DUTCH', value: 'DUTCH' },
    { label: 'JAPANESE', value: 'JAPANESE' },
    { label: 'KOREAN', value: 'KOREAN' },
    { label: 'TURKISH', value: 'TURKISH' },
    { label: 'VIETNAMESE', value: 'VIETNAMESE' },
    { label: 'THAI', value: 'THAI' },
    { label: 'SWAHILI', value: 'SWAHILI' },
    { label: 'BENGALI', value: 'BENGALI' },
    { label: 'PERSIAN', value: 'PERSIAN' },
    { label: 'HEBREW', value: 'HEBREW' },
    { label: 'UKRAINIAN', value: 'UKRAINIAN' },
    { label: 'CZECH', value: 'CZECH' },
    { label: 'SWEDISH', value: 'SWEDISH' },
    { label: 'DANISH', value: 'DANISH' },
    { label: 'NORWEGIAN', value: 'NORWEGIAN' },
    { label: 'FINNISH', value: 'FINNISH' },
    { label: 'ITALIAN', value: 'ITALIAN' },
    { label: 'OTHER', value: 'OTHER' },
];

export const hobbiesList = [
    { label: 'FOOTBALL', value: 'FOOTBALL' },
    { label: 'READING', value: 'READING' },
    { label: 'TRAVELING', value: 'TRAVELING' },
    { label: 'COOKING', value: 'COOKING' },
    { label: 'GARDENING', value: 'GARDENING' },
    { label: 'PHOTOGRAPHY', value: 'PHOTOGRAPHY' },
    { label: 'PAINTING', value: 'PAINTING' },
    { label: 'PLAYING SPORTS', value: 'PLAYING SPORTS' },
    { label: 'MUSIC', value: 'MUSIC' },
    { label: 'WRITING', value: 'WRITING' },
    { label: 'HIKING', value: 'HIKING' },
    { label: 'CRAFTING', value: 'CRAFTING' },
    { label: 'FISHING', value: 'FISHING' },
    { label: 'DANCING', value: 'DANCING' },
    { label: 'GAMING', value: 'GAMING' },
    { label: 'VOLUNTEERING', value: 'VOLUNTEERING' },
    { label: 'SKATING', value: 'SKATING' },
    { label: 'SWIMMING', value: 'SWIMMING' },
    { label: 'CYCLING', value: 'CYCLING' },
    { label: 'RUNNING', value: 'RUNNING' },
    { label: 'YOGA', value: 'YOGA' },
    { label: 'MEDITATION', value: 'MEDITATION' },
    { label: 'SCULPTING', value: 'SCULPTING' },
    { label: 'BIRD WATCHING', value: 'BIRD WATCHING' },
    { label: 'STAMP COLLECTING', value: 'STAMP COLLECTING' },
    { label: 'COIN COLLECTING', value: 'COIN COLLECTING' },
    { label: 'MODEL BUILDING', value: 'MODEL BUILDING' },
    { label: 'POTTERY', value: 'POTTERY' },
    { label: 'WOODWORKING', value: 'WOODWORKING' },
    { label: 'JOURNALING', value: 'JOURNALING' },
    { label: 'CALLIGRAPHY', value: 'CALLIGRAPHY' },
    { label: 'LEARNING LANGUAGES', value: 'LEARNING LANGUAGES' },
    { label: 'FASHION DESIGN', value: 'FASHION DESIGN' },
    { label: 'ANIMAL CARE', value: 'ANIMAL CARE' },
    { label: 'DIY PROJECTS', value: 'DIY PROJECTS' },
    { label: 'CARPENTRY', value: 'CARPENTRY' },
    { label: 'CROCHETING', value: 'CROCHETING' },
    { label: 'KNITTING', value: 'KNITTING' },
    { label: 'BEADING', value: 'BEADING' },
    { label: 'LEGO BUILDING', value: 'LEGO BUILDING' },
    { label: 'SOAP MAKING', value: 'SOAP MAKING' },
    { label: 'CANDLE MAKING', value: 'CANDLE MAKING' },
    { label: 'GOURMET COOKING', value: 'GOURMET COOKING' },
    { label: 'CHEESE MAKING', value: 'CHEESE MAKING' },
    { label: 'WINEMAKING', value: 'WINEMAKING' },
    { label: 'ROCK CLIMBING', value: 'ROCK CLIMBING' },
    { label: 'SKYDIVING', value: 'SKYDIVING' },
    { label: 'SURFING', value: 'SURFING' },
    { label: 'PADDLE BOARDING', value: 'PADDLE BOARDING' },
    { label: 'DIVING', value: 'DIVING' },
    { label: 'PARAGLIDING', value: 'PARAGLIDING' },
    { label: 'ORIGAMI', value: 'ORIGAMI' },
    { label: 'ARCHERY', value: 'ARCHERY' },
    { label: 'VOLLEYBALL', value: 'VOLLEYBALL' },
    { label: 'BADMINTON', value: 'BADMINTON' },
    { label: 'TABLE TENNIS', value: 'TABLE TENNIS' },
    { label: 'FENCING', value: 'FENCING' },
    { label: 'KARATE', value: 'KARATE' },
    { label: 'TAEKWONDO', value: 'TAEKWONDO' },
    { label: 'BOXING', value: 'BOXING' },
    { label: 'MMA', value: 'MMA' },
    { label: 'GARDEN DESIGN', value: 'GARDEN DESIGN' },
    { label: 'NATURE PHOTOGRAPHY', value: 'NATURE PHOTOGRAPHY' },
    { label: 'ANIME', value: 'ANIME' },
    { label: 'COSPLAY', value: 'COSPLAY' },
    { label: 'BOARD GAMES', value: 'BOARD GAMES' },
    { label: 'CARD GAMES', value: 'CARD GAMES' },
    { label: 'PUZZLES', value: 'PUZZLES' },
    { label: 'ESPORTS', value: 'ESPORTS' },
    { label: 'COMIC COLLECTING', value: 'COMIC COLLECTING' },
    { label: 'NOSTALGIA', value: 'NOSTALGIA' },
    { label: 'SOAP CARVING', value: 'SOAP CARVING' },
    { label: 'FURNITURE UPHOLSTERY', value: 'FURNITURE UPHOLSTERY' },
    { label: 'BEEKEEPING', value: 'BEEKEEPING' },
    { label: 'HIKING WITH DOGS', value: 'HIKING WITH DOGS' },
    { label: 'MUSICAL INSTRUMENTS', value: 'MUSICAL INSTRUMENTS' },
    { label: 'SINGING', value: 'SINGING' },
    { label: 'SPORE COLLECTING', value: 'SPORE COLLECTING' },
    { label: 'PERSUASIVE WRITING', value: 'PERSUASIVE WRITING' },
    { label: 'MAGIC TRICKS', value: 'MAGIC TRICKS' },
    { label: 'BEEKEEPING', value: 'BEEKEEPING' },
    { label: 'CLAY MODELING', value: 'CLAY MODELING' },
    { label: 'SIGN LANGUAGE', value: 'SIGN LANGUAGE' },
    { label: 'KITE FLYING', value: 'KITE FLYING' },
    { label: 'TAIKO DRUMMING', value: 'TAIKO DRUMMING' },
    { label: 'FURRY COSTUMING', value: 'FURRY COSTUMING' },
    { label: 'WHISTLING', value: 'WHISTLING' },
    { label: 'FOSSIL HUNTING', value: 'FOSSIL HUNTING' },
    { label: 'RUG MAKING', value: 'RUG MAKING' },
    { label: 'GHOST HUNTING', value: 'GHOST HUNTING' },
    { label: 'HISTORY REENACTMENT', value: 'HISTORY REENACTMENT' },
    { label: 'LARPING', value: 'LARPING' },
    { label: 'STUNT PERFORMING', value: 'STUNT PERFORMING' },
    { label: 'AEROMODELING', value: 'AEROMODELING' },
    { label: 'BASKET WEAVING', value: 'BASKET WEAVING' },
    { label: 'NUTRITION COOKING', value: 'NUTRITION COOKING' },
    { label: 'QUILTING', value: 'QUILTING' },
    { label: 'SANDCASTLE BUILDING', value: 'SANDCASTLE BUILDING' },
    { label: 'VINTAGE COLLECTING', value: 'VINTAGE COLLECTING' },
    { label: 'PUPPETRY', value: 'PUPPETRY' },
    { label: 'PARKOUR', value: 'PARKOUR' },
    { label: 'GHOST WRITING', value: 'GHOST WRITING' },
    { label: 'SKETCHING', value: 'SKETCHING' },
    { label: 'WRESTLING', value: 'WRESTLING' },
    { label: 'ASTRONOMY', value: 'ASTRONOMY' },
    { label: 'ASTROPHOTOGRAPHY', value: 'ASTROPHOTOGRAPHY' },
    { label: 'PODCASTING', value: 'PODCASTING' },
    { label: 'YOUTUBING', value: 'YOUTUBING' },
    { label: 'VLOGGING', value: 'VLOGGING' },
    { label: 'RESEARCHING', value: 'RESEARCHING' },
    { label: 'CREATIVE WRITING', value: 'CREATIVE WRITING' },
    { label: 'NATURE WALKING', value: 'NATURE WALKING' },
    { label: 'NATURE CONSERVATION', value: 'NATURE CONSERVATION' },
    { label: 'FISH TANK MAINTENANCE', value: 'FISH TANK MAINTENANCE' },
    { label: 'ANT FARMING', value: 'ANT FARMING' },
    { label: 'PILATES', value: 'PILATES' },
    { label: 'HOME BREWING', value: 'HOME BREWING' },
    { label: 'BIRD KEEPNG', value: 'BIRD KEEPING' },
    { label: 'GENEALOGY', value: 'GENEALOGY' },
    { label: 'MYTHOLOGY STUDY', value: 'MYTHOLOGY STUDY' },
    { label: 'ANTIQUE RESTORATION', value: 'ANTIQUE RESTORATION' },
    { label: 'MURALS', value: 'MURALS' },
    { label: 'LEADERSHIP TRAINING', value: 'LEADERSHIP TRAINING' },
    { label: 'MARTIAL ARTS', value: 'MARTIAL ARTS' },
    { label: 'CIRCUS ARTS', value: 'CIRCUS ARTS' },
    { label: 'FLORAL ARRANGING', value: 'FLORAL ARRANGING' },
    { label: 'LEATHER CRAFTING', value: 'LEATHER CRAFTING' },
    { label: 'FANTASY SPORTS', value: 'FANTASY SPORTS' },
    { label: 'FISHING TACKLE MAKING', value: 'FISHING TACKLE MAKING' },
    { label: 'CANDLE MAKING', value: 'CANDLE MAKING' },
    { label: 'PILLOW MAKING', value: 'PILLOW MAKING' },
    { label: 'MODEL RAILROADING', value: 'MODEL RAILROADING' },
    { label: 'SLEIGHT OF HAND', value: 'SLEIGHT OF HAND' },
    { label: 'GEOCACHING', value: 'GEOCACHING' },
    { label: 'SPEECH WRITING', value: 'SPEECH WRITING' },
    { label: 'RHYTHMIC GYMNASTICS', value: 'RHYTHMIC GYMNASTICS' },
    { label: 'SQUASH', value: 'SQUASH' },
    { label: 'SKIING', value: 'SKIING' },
    { label: 'SNOWBOARDING', value: 'SNOWBOARDING' },
    { label: 'HIKING WITH KIDS', value: 'HIKING WITH KIDS' },
    { label: 'PARENTING', value: 'PARENTING' },
    { label: 'FAMILY REUNION PLANNING', value: 'FAMILY REUNION PLANNING' },
    { label: 'SOCIAL NETWORKING', value: 'SOCIAL NETWORKING' },
    { label: 'SCHOOL CLUBS', value: 'SCHOOL CLUBS' },
    { label: 'FRATERNITIES/SORORITIES', value: 'FRATERNITIES/SORORITIES' },
    { label: 'STREET ART', value: 'STREET ART' },
    { label: 'KAYAKING', value: 'KAYAKING' },
    { label: 'BIRD FEEDING', value: 'BIRD FEEDING' },
    { label: 'WILDLIFE PHOTOGRAPHY', value: 'WILDLIFE PHOTOGRAPHY' },
    { label: 'HIKING WITH FRIENDS', value: 'HIKING WITH FRIENDS' },
    { label: 'COSTUME DESIGN', value: 'COSTUME DESIGN' },
    { label: 'VIRTUAL REALITY GAMING', value: 'VIRTUAL REALITY GAMING' },
    { label: 'BIG DATA ANALYSIS', value: 'BIG DATA ANALYSIS' },
    { label: 'WINE TASTING', value: 'WINE TASTING' },
    { label: 'SPIRITS TASTING', value: 'SPIRITS TASTING' },
    { label: 'GOURMET TASTING', value: 'GOURMET TASTING' },
    { label: 'FESTIVAL PLANNING', value: 'FESTIVAL PLANNING' },
    { label: 'EVENT PLANNING', value: 'EVENT PLANNING' },
    { label: 'STORYTELLING', value: 'STORYTELLING' },
    { label: 'DIY FURNITURE', value: 'DIY FURNITURE' },
    { label: 'PARK CLEANUP', value: 'PARK CLEANUP' },
    { label: 'COMMUNITY SERVICE', value: 'COMMUNITY SERVICE' },
    { label: 'CIVIC ENGAGEMENT', value: 'CIVIC ENGAGEMENT' },
    { label: 'MENTORING', value: 'MENTORING' },
    { label: 'EXPLORING CITIES', value: 'EXPLORING CITIES' },
    { label: 'CULTURAL STUDY', value: 'CULTURAL STUDY' },
    { label: 'LANGUAGE EXCHANGE', value: 'LANGUAGE EXCHANGE' },
    { label: 'THEATER ARTS', value: 'THEATER ARTS' },
    { label: 'SKETCHING', value: 'SKETCHING' },
    { label: 'GRAFFITI ART', value: 'GRAFFITI ART' },
    { label: 'WINTER SPORTS', value: 'WINTER SPORTS' },
    { label: 'SUMMER SPORTS', value: 'SUMMER SPORTS' },
    { label: 'MAGAZINE CREATION', value: 'MAGAZINE CREATION' },
    { label: 'TRAVEL BLOGGING', value: 'TRAVEL BLOGGING' },
    { label: 'COMMUNITY THEATER', value: 'COMMUNITY THEATER' },
    { label: 'MOUNTANEERING', value: 'MOUNTANEERING' },
    { label: 'CROSS-STITCHING', value: 'CROSS-STITCHING' },
    { label: 'NATURE SOUND RECORDING', value: 'NATURE SOUND RECORDING' },
    { label: 'SCHOOL CLUB ADVISOR', value: 'SCHOOL CLUB ADVISOR' },
    { label: 'CAMPING', value: 'CAMPING' },
    { label: 'MUSEUM VISITING', value: 'MUSEUM VISITING' },
    { label: 'URBAN EXPLORATION', value: 'URBAN EXPLORATION' },
    { label: 'CINEMA APPRECIATION', value: 'CINEMA APPRECIATION' },
    { label: 'OTHER', value: 'OTHER' },
];

export const relationshipTypes = [
    { label: "NEXT OF KIN", value: "NEXT OF KIN" },
    { label: "SPOUSE", value: "SPOUSE" },
];

export const salutations = [
    { label: "MR", value: "MR" },
    { label: "MRS", value: "MRS" },
    { label: "MISS", value: "MISS" },
    { label: "MS", value: "MS" },
    // { label: "DR", value: "DR" },
    // { label: "ENGINEER", value: "ENGINEER" },
    // { label: "HONOURABLE", value: "HONOURABLE" },
    // { label: "PROFFESSOR", value: "PROFFESSOR" },
];

export const maritalStatuses = [
    { label: "SINGLE", value: "SINGLE" },
    { label: "MARRIED", value: "MARRIED" },
    { label: "DIVORCED", value: "DIVORCED" },
    { label: "SEPARATED", value: "SEPARATED" },
    { label: "WIDOWED", value: "WIDOWED" },
    { label: "OTHER", value: "OTHER" },
];

export const religions = [
    { label: "CHRISTIANITY", value: "CHRISTIANITY" },
    { label: "ISLAM", value: "ISLAM" },
    { label: "HINDUISM", value: "HINDUISM" },
    { label: "BUDDHISM", value: "BUDDHISM" },
    { label: "JUDAISM", value: "JUDAISM" },
    { label: "SIKHISM", value: "SIKHISM" },
    { label: "BAHA'I", value: "BAHA'I" },
    { label: "TAOISM", value: "TAOISM" },
    { label: "CONFUCIANISM", value: "CONFUCIANISM" },
    { label: "AFRICAN TRADITIONAL RELIGION", value: "AFRICAN TRADITIONAL RELIGION" },
];

export const addressTypes = [
    { label: "RESIDENTIAL", value: "RESIDENTIAL" },
    { label: "POSTAL", value: "POSTAL" }
]

export const homeOwnershipTypes = [
    { label: "OWNED", value: "OWNED" },
    { label: "RENTED", value: "RENTED" },
    { label: "LIVING WITH PARENTS", value: "LIVING WITH PARENTS" },
    { label: "COMPANY PROVIDED", value: "COMPANY PROVIDED" },
];

export const jobTitles = [
    { label: "DIRECTOR", value: "DIRECTOR" },
    { label: "SOFTWARE ENGINEER", value: "SOFTWARE ENGINEER" },
    { label: "DATA SCIENTIST", value: "DATA SCIENTIST" },
    { label: "PRODUCT MANAGER", value: "PRODUCT MANAGER" },
    { label: "GRAPHIC DESIGNER", value: "GRAPHIC DESIGNER" },
    { label: "MARKETING SPECIALIST", value: "MARKETING SPECIALIST" },
    { label: "SALES EXECUTIVE", value: "SALES EXECUTIVE" },
    { label: "CUSTOMER SUPPORT", value: "CUSTOMER SUPPORT" },
    { label: "HR MANAGER", value: "HR MANAGER" },
    { label: "WEB DEVELOPER", value: "WEB DEVELOPER" },
    { label: "BUSINESS ANALYST", value: "BUSINESS ANALYST" },
    { label: "DEVOPS ENGINEER", value: "DEVOPS ENGINEER" },
    { label: "UX/UI DESIGNER", value: "UX/UI DESIGNER" },
    { label: "NETWORK ADMINISTRATOR", value: "NETWORK ADMINISTRATOR" },
    { label: "PROJECT COORDINATOR", value: "PROJECT COORDINATOR" },
    { label: "CONTENT WRITER", value: "CONTENT WRITER" },
    { label: "SEO SPECIALIST", value: "SEO SPECIALIST" },
    { label: "DATABASE ADMINISTRATOR", value: "DATABASE ADMINISTRATOR" },
    { label: "FINANCIAL ANALYST", value: "FINANCIAL ANALYST" },
    { label: "OPERATIONS MANAGER", value: "OPERATIONS MANAGER" },
    { label: "MOBILE APP DEVELOPER", value: "MOBILE APP DEVELOPER" },
    { label: "SYSTEMS ANALYST", value: "SYSTEMS ANALYST" },
];

export const customerRiskLevels = [
    { label: "HIGH", value: "HIGH" },
    { label: "MEDIUM", value: "MEDIUM" },
    { label: "LOW", value: "LOW" },
];

export const employerTypes = [
    { label: "GOVERNMENT", value: "GOVERNMENT" },
    { label: "LOCAL COMPANY", value: "LOCAL COMPANY" },
    { label: "MULTI NATIONAL", value: "MULTI NATIONAL" },
];

export const employmentTypes = [
    { label: "PERMANENT", value: "PERMANENT" },
    { label: "TEMPORARY", value: "TEMPORARY" },
    { label: "PART TIME", value: "PART TIME" },
    { label: "SELF EMPLOYED", value: "SELF EMPLOYED" },
    { label: "RETIRED PENSIONER", value: "RETIRED PENSIONER" },
    { label: "RETIRED NON-PENSIONER", value: "RETIRED NON-PENSIONER" },
    { label: "UNEMPLOYED", value: "UNEMPLOYED" },
    { label: "STUDENT", value: "STUDENT" }
]

export const communicationMethods = [
    { label: "EMAIL", value: "EMAIL" },
    { label: "PHONE CALL", value: "PHONE CALL" },
    { label: "WHATSAPP", value: "WHATSAPP" },
    { label: "SMS", value: "SMS" }
]

export const companyTypes = [
    { label: "SOLE PROPRIETORSHIP", value: "SOLE PROPRIETORSHIP" },
    { label: "PARTNERSHIP", value: "PARTNERSHIP" },
    { label: "CORPORATION", value: "CORPORATION" },
    { label: "LIMITED LIABILITY COMPANY (LLC)", value: "LLC" },
    { label: "NON-PROFIT ORGANIZATION", value: "NON-PROFIT" },
    { label: "COOPERATIVE", value: "COOPERATIVE" },
    { label: "FRANCHISE", value: "FRANCHISE" }
];


export const industrySubCategories = {
    "INFORMATION TECHNOLOGY": [
        { label: "SOFTWARE DEVELOPMENT", value: "SOFTWARE" },
        { label: "CYBERSECURITY", value: "CYBERSECURITY" },
        { label: "CLOUD COMPUTING", value: "CLOUD" },
        { label: "DATA SCIENCE", value: "DATASCIENCE" },
        { label: "IT CONSULTING", value: "ITCONSULTING" },
        { label: "NETWORKING", value: "NETWORKING" },
        { label: "MOBILE APP DEVELOPMENT", value: "MOBILEAPP" },
        { label: "WEB DEVELOPMENT", value: "WEBDEV" },
        { label: "AI AND MACHINE LEARNING", value: "AI" },
        { label: "BLOCKCHAIN TECHNOLOGY", value: "BLOCKCHAIN" }
    ],
    "HEALTHCARE": [
        { label: "HOSPITALS", value: "HOSPITALS" },
        { label: "PHARMACEUTICALS", value: "PHARMA" },
        { label: "MEDICAL DEVICES", value: "MEDICALDEVICES" },
        { label: "HEALTH INSURANCE", value: "HEALTHINSURANCE" },
        { label: "TELEMEDICINE", value: "TELEMEDICINE" },
        { label: "DIAGNOSTIC LABS", value: "DIAGNOSTICLABS" },
        { label: "REHABILITATION SERVICES", value: "REHAB" },
        { label: "HOME HEALTHCARE", value: "HOMEHEALTHCARE" },
        { label: "MENTAL HEALTH SERVICES", value: "MENTALHEALTH" },
        { label: "PUBLIC HEALTH", value: "PUBLICHEALTH" }
    ],
    "FINANCE": [
        { label: "BANKING", value: "BANKING" },
        { label: "INVESTMENT", value: "INVESTMENT" },
        { label: "INSURANCE", value: "INSURANCE" },
        { label: "FINTECH", value: "FINTECH" },
        { label: "ACCOUNTING", value: "ACCOUNTING" },
        { label: "PERSONAL FINANCE", value: "PERSONALFINANCE" },
        { label: "MORTGAGE LENDING", value: "MORTGAGE" },
        { label: "ASSET MANAGEMENT", value: "ASSETMANAGEMENT" },
        { label: "PRIVATE EQUITY", value: "PRIVATEEQUITY" },
        { label: "CREDIT UNIONS", value: "CREDITUNIONS" }
    ],
    "RETAIL": [
        { label: "E-COMMERCE", value: "ECOMMERCE" },
        { label: "BRICK AND MORTAR", value: "BRICKANDMORTAR" },
        { label: "WHOLESALE", value: "WHOLESALE" },
        { label: "FASHION RETAIL", value: "FASHIONRETAIL" },
        { label: "GROCERY", value: "GROCERY" },
        { label: "CONVENIENCE STORES", value: "CONVENIENCESTORES" },
        { label: "SPECIALTY STORES", value: "SPECIALTY" },
        { label: "DISCOUNT STORES", value: "DISCOUNT" },
        { label: "DEPARTMENT STORES", value: "DEPARTMENT" },
        { label: "AUTOMOTIVE RETAIL", value: "AUTORETAIL" }
    ],
    "MANUFACTURING": [
        { label: "AUTOMOBILE", value: "AUTOMOBILE" },
        { label: "ELECTRONICS", value: "ELECTRONICS" },
        { label: "TEXTILES", value: "TEXTILES" },
        { label: "FOOD PROCESSING", value: "FOODPROCESSING" },
        { label: "MACHINERY", value: "MACHINERY" },
        { label: "AEROSPACE", value: "AEROSPACE" },
        { label: "CHEMICAL MANUFACTURING", value: "CHEMICAL" },
        { label: "PHARMACEUTICAL MANUFACTURING", value: "PHARMMANUFACTURING" },
        { label: "PLASTICS", value: "PLASTICS" },
        { label: "PACKAGING", value: "PACKAGING" }
    ],
    "EDUCATION": [
        { label: "K-12 EDUCATION", value: "K12" },
        { label: "HIGHER EDUCATION", value: "HIGHERED" },
        { label: "ONLINE LEARNING", value: "ONLINELEARNING" },
        { label: "VOCATIONAL TRAINING", value: "VOCATIONAL" },
        { label: "EDUCATIONAL TECHNOLOGY", value: "EDTECH" },
        { label: "LANGUAGE INSTITUTES", value: "LANGUAGE" },
        { label: "TEST PREPARATION", value: "TESTPREP" },
        { label: "TUTORING SERVICES", value: "TUTORING" },
        { label: "SPECIAL EDUCATION", value: "SPECEducation" },
        { label: "ADULT EDUCATION", value: "ADULTED" }
    ],
    "CONSTRUCTION": [
        { label: "RESIDENTIAL", value: "RESIDENTIAL" },
        { label: "COMMERCIAL", value: "COMMERCIAL" },
        { label: "INFRASTRUCTURE", value: "INFRASTRUCTURE" },
        { label: "CONTRACTING", value: "CONTRACTING" },
        { label: "PROJECT MANAGEMENT", value: "PROJECTMANAGEMENT" },
        { label: "CIVIL ENGINEERING", value: "CIVILENGINEERING" },
        { label: "ELECTRICAL CONTRACTING", value: "ELECTRICAL" },
        { label: "PLUMBING", value: "PLUMBING" },
        { label: "ROOFING", value: "ROOFING" },
        { label: "LANDSCAPING", value: "LANDSCAPING" }
    ],
    "HOSPITALITY": [
        { label: "HOTELS", value: "HOTELS" },
        { label: "RESTAURANTS", value: "RESTAURANTS" },
        { label: "TRAVEL SERVICES", value: "TRAVELSERVICES" },
        { label: "EVENT MANAGEMENT", value: "EVENTMANAGEMENT" },
        { label: "CATERING", value: "CATERING" },
        { label: "TOURISM", value: "TOURISM" },
        { label: "CRUISES", value: "CRUISES" },
        { label: "RESORTS", value: "RESORTS" },
        { label: "FOOD TRUCKS", value: "FOODTRUCKS" },
        { label: "CONFERENCE PLANNING", value: "CONFERENCEPLANNING" }
    ],
    "TRANSPORTATION": [
        { label: "LOGISTICS", value: "LOGISTICS" },
        { label: "SHIPPING", value: "SHIPPING" },
        { label: "PUBLIC TRANSPORT", value: "PUBLICTRANSPORT" },
        { label: "FREIGHT", value: "FREIGHT" },
        { label: "RIDE SHARING", value: "RIDESHARING" },
        { label: "COURIER SERVICES", value: "COURIER" },
        { label: "TRUCKING", value: "TRUCKING" },
        { label: "RAIL TRANSPORTATION", value: "RAIL" },
        { label: "AVIATION", value: "AVIATION" },
        { label: "MARITIME", value: "MARITIME" }
    ],
    "REAL ESTATE": [
        { label: "RESIDENTIAL REAL ESTATE", value: "RESIDENTIALREALESTATE" },
        { label: "COMMERCIAL REAL ESTATE", value: "COMMERCIALREALESTATE" },
        { label: "PROPERTY MANAGEMENT", value: "PROPERTYMANAGEMENT" },
        { label: "REAL ESTATE INVESTMENT", value: "REALESTATEINVESTMENT" },
        { label: "REAL ESTATE DEVELOPMENT", value: "REALESTATEDEVELOPMENT" },
        { label: "REAL ESTATE APPRAISAL", value: "APPRAISAL" },
        { label: "REAL ESTATE BROKERAGE", value: "BROKERAGE" },
        { label: "LAND DEVELOPMENT", value: "LANDDEVELOPMENT" },
        { label: "RENTAL SERVICES", value: "RENTAL" },
        { label: "FORECLOSURE SERVICES", value: "FORECLOSURE" }
    ],
    "TELECOMMUNICATIONS": [
        { label: "MOBILE SERVICES", value: "MOBILESERVICES" },
        { label: "INTERNET SERVICES", value: "INTERNETSERVICES" },
        { label: "SATELLITE COMMUNICATIONS", value: "SATELLITE" },
        { label: "NETWORK INFRASTRUCTURE", value: "NETWORKINFRASTRUCTURE" },
        { label: "VOIP SERVICES", value: "VOIP" },
        { label: "BROADBAND SERVICES", value: "BROADBAND" },
        { label: "TELECOM EQUIPMENT", value: "EQUIPMENT" },
        { label: "CELLULAR NETWORKS", value: "CELLULAR" },
        { label: "CABLE SERVICES", value: "CABLE" },
        { label: "FIBER OPTIC SERVICES", value: "FIBEROPTIC" }
    ],
    "ENERGY": [
        { label: "RENEWABLE ENERGY", value: "RENEWABLE" },
        { label: "FOSSIL FUELS", value: "FOSSILFUELS" },
        { label: "ENERGY MANAGEMENT", value: "ENERGYMANAGEMENT" },
        { label: "UTILITIES", value: "UTILITIES" },
        { label: "NUCLEAR ENERGY", value: "NUCLEAR" },
        { label: "SOLAR ENERGY", value: "SOLAR" },
        { label: "WIND ENERGY", value: "WIND" },
        { label: "GAS AND OIL", value: "GASANDOIL" },
        { label: "GEOTHERMAL ENERGY", value: "GEOTHERMAL" },
        { label: "HYDROPOWER", value: "HYDROPOWER" }
    ],
    "AGRICULTURE": [
        { label: "CROP PRODUCTION", value: "CROPPRODUCTION" },
        { label: "LIVESTOCK", value: "LIVESTOCK" },
        { label: "AGRICULTURAL TECHNOLOGY", value: "AGRITECH" },
        { label: "ORGANIC FARMING", value: "ORGANICFARMING" },
        { label: "AQUACULTURE", value: "AQUACULTURE" },
        { label: "AGROFORESTRY", value: "AGROFORESTRY" },
        { label: "HORTICULTURE", value: "HORTICULTURE" },
        { label: "AGRICULTURAL SUPPLIES", value: "AGRISUPPLIES" },
        { label: "SOIL MANAGEMENT", value: "SOILMANAGEMENT" },
        { label: "AGRICULTURAL RESEARCH", value: "AGRESEARCH" }
    ],
    "PHARMACEUTICALS": [
        { label: "RESEARCH AND DEVELOPMENT", value: "R&D" },
        { label: "MANUFACTURING", value: "MANUFACTURING" },
        { label: "DISTRIBUTION", value: "DISTRIBUTION" },
        { label: "CLINICAL TRIALS", value: "CLINICALTRIALS" },
        { label: "REGULATORY AFFAIRS", value: "REGULATORYAFFAIRS" },
        { label: "BIOTECHNOLOGY", value: "BIOTECH" },
        { label: "VACCINE DEVELOPMENT", value: "VACCINES" },
        { label: "GENETIC RESEARCH", value: "GENETICS" },
        { label: "PHARMACOVIGILANCE", value: "PHARMACOVIGILANCE" },
        { label: "PHARMACEUTICAL MARKETING", value: "PHARMAMARKETING" }
    ],
    "ENTERTAINMENT": [
        { label: "FILM PRODUCTION", value: "FILM" },
        { label: "TELEVISION", value: "TELEVISION" },
        { label: "MUSIC", value: "MUSIC" },
        { label: "GAMING", value: "GAMING" },
        { label: "STREAMING SERVICES", value: "STREAMING" },
        { label: "THEATER", value: "THEATER" },
        { label: "COMEDY", value: "COMEDY" },
        { label: "LIVE EVENTS", value: "LIVEEVENTS" },
        { label: "PODCASTING", value: "PODCASTING" },
        { label: "ANIMATION", value: "ANIMATION" }
    ],
    "MEDIA": [
        { label: "DIGITAL MEDIA", value: "DIGITALMEDIA" },
        { label: "BROADCASTING", value: "BROADCASTING" },
        { label: "PRINT MEDIA", value: "PRINTMEDIA" },
        { label: "ADVERTISING", value: "ADVERTISING" },
        { label: "PUBLIC RELATIONS", value: "PR" },
        { label: "SOCIAL MEDIA", value: "SOCIALMEDIA" },
        { label: "CONTENT CREATION", value: "CONTENTCREATION" },
        { label: "NEWS MEDIA", value: "NEWS" },
        { label: "MARKETING", value: "MARKETING" },
        { label: "MEDIA ANALYSIS", value: "MEDIAANALYSIS" }
    ],
    "INSURANCE": [
        { label: "LIFE INSURANCE", value: "LIFE" },
        { label: "HEALTH INSURANCE", value: "HEALTH" },
        { label: "PROPERTY INSURANCE", value: "PROPERTY" },
        { label: "CASUALTY INSURANCE", value: "CASUALTY" },
        { label: "REINSURANCE", value: "REINSURANCE" },
        { label: "AUTO INSURANCE", value: "AUTO" },
        { label: "BUSINESS INSURANCE", value: "BUSINESS" },
        { label: "TRAVEL INSURANCE", value: "TRAVEL" },
        { label: "PET INSURANCE", value: "PET" },
        { label: "LIABILITY INSURANCE", value: "LIABILITY" }
    ],
    "LEGAL SERVICES": [
        { label: "CORPORATE LAW", value: "CORPORATE" },
        { label: "CRIMINAL LAW", value: "CRIMINAL" },
        { label: "FAMILY LAW", value: "FAMILY" },
        { label: "INTELLECTUAL PROPERTY", value: "IP" },
        { label: "IMMIGRATION LAW", value: "IMMIGRATION" },
        { label: "ENVIRONMENTAL LAW", value: "ENVIRONMENTAL" },
        { label: "TAX LAW", value: "TAX" },
        { label: "PERSONAL INJURY LAW", value: "PERSONALINJURY" },
        { label: "BANKRUPTCY LAW", value: "BANKRUPTCY" },
        { label: "CONTRACT LAW", value: "CONTRACT" }
    ],
    "NON-PROFIT": [
        { label: "CHARITABLE ORGANIZATIONS", value: "CHARITY" },
        { label: "FOUNDATIONS", value: "FOUNDATIONS" },
        { label: "ADVOCACY GROUPS", value: "ADVOCACY" },
        { label: "COMMUNITY SERVICES", value: "COMMUNITY" },
        { label: "INTERNATIONAL NGOS", value: "INGO" },
        { label: "ENVIRONMENTAL ORGANIZATIONS", value: "ENVIRONMENTAL" },
        { label: "CULTURAL ORGANIZATIONS", value: "CULTURAL" },
        { label: "EDUCATIONAL NON-PROFITS", value: "EDUCATIONAL" },
        { label: "HEALTHCARE NON-PROFITS", value: "HEALTHCARE" },
        { label: "HUMAN RIGHTS ORGANIZATIONS", value: "HUMANRIGHTS" }
    ],
    "CONSULTING": [
        { label: "MANAGEMENT CONSULTING", value: "MANAGEMENT" },
        { label: "STRATEGY CONSULTING", value: "STRATEGY" },
        { label: "HUMAN RESOURCES CONSULTING", value: "HR" },
        { label: "IT CONSULTING", value: "IT" },
        { label: "FINANCIAL CONSULTING", value: "FINANCE" },
        { label: "MARKETING CONSULTING", value: "MARKETING" },
        { label: "OPERATIONS CONSULTING", value: "OPERATIONS" },
        { label: "SUPPLY CHAIN CONSULTING", value: "SUPPLYCHAIN" },
        { label: "RISK MANAGEMENT CONSULTING", value: "RISK" },
        { label: "CHANGE MANAGEMENT CONSULTING", value: "CHANGE" }
    ],
    "FASHION": [
        { label: "APPAREL", value: "APPAREL" },
        { label: "ACCESSORIES", value: "ACCESSORIES" },
        { label: "FOOTWEAR", value: "FOOTWEAR" },
        { label: "COSMETICS", value: "COSMETICS" },
        { label: "FASHION DESIGN", value: "FASHIONDESIGN" },
        { label: "TEXTILE DESIGN", value: "TEXTILEDESIGN" },
        { label: "FASHION RETAIL", value: "FASHIONRETAIL" },
        { label: "FASHION MARKETING", value: "FASHIONMARKETING" },
        { label: "BRAND MANAGEMENT", value: "BRANDMANAGEMENT" },
        { label: "FASHION PHOTOGRAPHY", value: "FASHIONPHOTOGRAPHY" }
    ],
    "FOOD AND BEVERAGE": [
        { label: "RESTAURANTS", value: "RESTAURANTS" },
        { label: "CATERING", value: "CATERING" },
        { label: "FOOD PROCESSING", value: "FOODPROCESSING" },
        { label: "BEVERAGE PRODUCTION", value: "BEVERAGEPRODUCTION" },
        { label: "RETAIL FOOD SALES", value: "RETAILFOOD" },
        { label: "FOOD TRUCKS", value: "FOODTRUCKS" },
        { label: "BAKERY", value: "BAKERY" },
        { label: "WINERIES", value: "WINERIES" },
        { label: "BREWERIES", value: "BREWERIES" },
        { label: "SPICE PRODUCTION", value: "SPICEPRODUCTION" }
    ],
    "AEROSPACE": [
        { label: "AIRCRAFT MANUFACTURING", value: "AIRCRAFT" },
        { label: "SPACE EXPLORATION", value: "SPACE" },
        { label: "DEFENSE CONTRACTING", value: "DEFENSE" },
        { label: "AVIONICS", value: "AVIONICS" },
        { label: "ROCKET PROPULSION", value: "ROCKET" }
    ],
    "BIOTECHNOLOGY": [
        { label: "GENE THERAPY", value: "GENETHERAPY" },
        { label: "PHARMACEUTICAL BIOTECH", value: "PHARMBIO" },
        { label: "AGRICULTURAL BIOTECH", value: "AGRICULTURALBIO" },
        { label: "BIOINFORMATICS", value: "BIOINFORMATICS" },
        { label: "MOLECULAR DIAGNOSTICS", value: "MOLECULAR" }
    ],
    "ENVIRONMENTAL SERVICES": [
        { label: "WASTE MANAGEMENT", value: "WASTEMANAGEMENT" },
        { label: "RECYCLING SERVICES", value: "RECYCLING" },
        { label: "POLLUTION CONTROL", value: "POLLUTIONCONTROL" },
        { label: "ECOSYSTEM RESTORATION", value: "ECOSYSTEM" },
        { label: "SUSTAINABILITY CONSULTING", value: "SUSTAINABILITY" }
    ],
    "REAL ESTATE DEVELOPMENT": [
        { label: "COMMERCIAL DEVELOPMENT", value: "COMMERCIALDEV" },
        { label: "RESIDENTIAL DEVELOPMENT", value: "RESIDENTIALDEV" },
        { label: "URBAN PLANNING", value: "URBANPLANNING" },
        { label: "RETAIL DEVELOPMENT", value: "RETAILDEV" },
        { label: "INSTITUTIONAL DEVELOPMENT", value: "INSTITUTIONALDEV" }
    ],
    "MEDIA AND ENTERTAINMENT": [
        { label: "TELEVISION PRODUCTION", value: "TELEVISON" },
        { label: "RADIO BROADCASTING", value: "RADIO" },
        { label: "DIGITAL CONTENT CREATION", value: "DIGITALCONTENT" },
        { label: "EVENT PLANNING", value: "EVENTPLANNING" },
        { label: "LIVE ENTERTAINMENT", value: "LIVEENTERTAINMENT" }
    ],
    "TRANSPORTATION SERVICES": [
        { label: "TAXI SERVICES", value: "TAXISERVICES" },
        { label: "SHUTTLE SERVICES", value: "SHUTTLESERVICES" },
        { label: "CAR RENTAL", value: "CARRENTAL" },
        { label: "BICYCLE RENTAL", value: "BICYLRENTAL" },
        { label: "AIRLINE SERVICES", value: "AIRLINESERVICES" }
    ],
    "FARMING AND AGRICULTURE": [
        { label: "CROP FARMING", value: "CROPFARMING" },
        { label: "DAIRY FARMING", value: "DAIRYFARMING" },
        { label: "POULTRY FARMING", value: "POULTRYFARMING" },
        { label: "AGRICULTURAL EQUIPMENT", value: "AGRICULTURALEQUIPMENT" },
        { label: "HORTICULTURE", value: "HORTICULTURE" }
    ],
    "PHOTOGRAPHY AND GRAPHIC DESIGN": [
        { label: "COMMERCIAL PHOTOGRAPHY", value: "COMMERCIALPHOTOGRAPHY" },
        { label: "PORTRAIT PHOTOGRAPHY", value: "PORTRAITPHOTOGRAPHY" },
        { label: "WEDDING PHOTOGRAPHY", value: "WEDDINGPHOTOGRAPHY" },
        { label: "GRAPHIC DESIGN", value: "GRAPHICDESIGN" },
        { label: "ILLUSTRATION", value: "ILLUSTRATION" }
    ],
    "SPORTS AND RECREATION": [
        { label: "PROFESSIONAL SPORTS", value: "PROFESSIONALSPORTS" },
        { label: "AMATEUR SPORTS", value: "AMATEURSPORTS" },
        { label: "FITNESS TRAINING", value: "FITNESSTRAINING" },
        { label: "OUTDOOR RECREATION", value: "OUTDOORRECREATION" },
        { label: "SPORTS MANAGEMENT", value: "SPORTSMANAGEMENT" }
    ],
    "TOURISM AND TRAVEL": [
        { label: "TRAVEL AGENCIES", value: "TRAVELAGENCIES" },
        { label: "TOUR OPERATORS", value: "TOUROPERATORS" },
        { label: "DESTINATION MARKETING", value: "DESTINATIONMARKETING" },
        { label: "TRAVEL INSURANCE", value: "TRAVELINSURANCE" },
        { label: "ADVENTURE TOURISM", value: "ADVENTURETOURISM" }
    ],
}

export const industriesList = Object.keys(industrySubCategories).map((industry) => (
    { label: industry, value: industry }
))

export const jobTitlesLookup = {
    "INFORMATION TECHNOLOGY": [
        { label: "SOFTWARE ENGINEER", value: "SOFTWAREENGINEER" },
        { label: "DATA SCIENTIST", value: "DATASCIENTIST" },
        { label: "CYBERSECURITY ANALYST", value: "CYBERSECURITYANALYST" },
        { label: "IT CONSULTANT", value: "ITCONSULTANT" },
        { label: "SYSTEM ADMINISTRATOR", value: "SYSTEMADMINISTRATOR" },
        { label: "NETWORK ENGINEER", value: "NETWORKENGINEER" },
        { label: "DEVOPS ENGINEER", value: "DEVOPSENGINEER" },
        { label: "WEB DEVELOPER", value: "WEBDEVELOPER" },
        { label: "MOBILE APP DEVELOPER", value: "MOBILEAPPDEVELOPER" },
        { label: "AI RESEARCHER", value: "AIRESEARCHER" },
    ],
    "HEALTHCARE": [
        { label: "DOCTOR", value: "DOCTOR" },
        { label: "NURSE", value: "NURSE" },
        { label: "PHARMACIST", value: "PHARMACIST" },
        { label: "MEDICAL TECHNICIAN", value: "MEDICALTECHNICIAN" },
        { label: "HEALTHCARE ADMINISTRATOR", value: "HEALTHCAREADMINISTRATOR" },
        { label: "PHYSICAL THERAPIST", value: "PHYSICALTHERAPIST" },
        { label: "MEDICAL RESEARCHER", value: "MEDICALRESEARCHER" },
        { label: "PUBLIC HEALTH OFFICIAL", value: "PUBLICHEALTHOFFICIAL" },
        { label: "DIETITIAN", value: "DIETITIAN" },
        { label: "TELEMEDICINE SPECIALIST", value: "TELEMEDICINESPECIALIST" },
    ],
    "FINANCE": [
        { label: "FINANCIAL ANALYST", value: "FINANCIALANALYST" },
        { label: "ACCOUNTANT", value: "ACCOUNTANT" },
        { label: "INVESTMENT BANKER", value: "INVESTMENTBANKER" },
        { label: "FINANCIAL CONSULTANT", value: "FINANCIALCONSULTANT" },
        { label: "AUDITOR", value: "AUDITOR" },
        { label: "RISK MANAGER", value: "RISKMANAGER" },
        { label: "TAX SPECIALIST", value: "TAXSPECIALIST" },
        { label: "WEALTH MANAGER", value: "WEALTHMANAGER" },
        { label: "COMPLIANCE OFFICER", value: "COMPLIANCEOFFICER" },
        { label: "FINTECH SPECIALIST", value: "FINTECHSPECIALIST" },
    ],
    "RETAIL": [
        { label: "STORE MANAGER", value: "STOREMANAGER" },
        { label: "SALES ASSOCIATE", value: "SALESASSOCIATE" },
        { label: "MERCHANDISER", value: "MERCHANDISER" },
        { label: "E-COMMERCE MANAGER", value: "ECOMMERCEMANAGER" },
        { label: "MARKETING COORDINATOR", value: "MARKETINGCOORDINATOR" },
        { label: "CUSTOMER SERVICE REPRESENTATIVE", value: "CUSTOMERSERVICEREP" },
        { label: "SUPPLY CHAIN MANAGER", value: "SUPPLYCHAINMANAGER" },
        { label: "VISUAL MERCHANDISER", value: "VISUALMERCHANDISER" },
        { label: "BUYER", value: "BUYER" },
        { label: "LOGISTICS COORDINATOR", value: "LOGISTICSCOORDINATOR" },
    ],
    "MANUFACTURING": [
        { label: "PRODUCTION MANAGER", value: "PRODUCTIONMANAGER" },
        { label: "QUALITY CONTROL INSPECTOR", value: "QUALITYCONTROLINSPECTOR" },
        { label: "MANUFACTURING ENGINEER", value: "MANUFACTURINGENGINEER" },
        { label: "MATERIALS MANAGER", value: "MATERIALSMANAGER" },
        { label: "PROCESS ENGINEER", value: "PROCESSENGINEER" },
        { label: "ELECTRICAL ENGINEER", value: "ELECTRICALENGINEER" },
        { label: "SUPPLY CHAIN ANALYST", value: "SUPPLYCHAINANALYST" },
        { label: "FACILITIES MANAGER", value: "FACILITIESMANAGER" },
        { label: "LOGISTICS MANAGER", value: "LOGISTICSMANAGER" },
        { label: "HEAVY MACHINERY OPERATOR", value: "HEAVYMACHINERYOPERATOR" },
    ],
    "EDUCATION": [
        { label: "TEACHER", value: "TEACHER" },
        { label: "PROFESSOR", value: "PROFESSOR" },
        { label: "SCHOOL ADMINISTRATOR", value: "SCHOOLADMINISTRATOR" },
        { label: "EDUCATIONAL CONSULTANT", value: "EDUCATIONALCONSULTANT" },
        { label: "COUNSELOR", value: "COUNSELOR" },
        { label: "TRAINER", value: "TRAINER" },
        { label: "CURRICULUM DEVELOPER", value: "CURRICULUMDEVELOPER" },
        { label: "LIBRARIAN", value: "LIBRARIAN" },
        { label: "EDUCATIONAL TECHNOLOGIST", value: "EDUCATIONALTECHNOLOGIST" },
        { label: "TUTOR", value: "TUTOR" },
    ],
    "CONSTRUCTION": [
        { label: "CONSTRUCTION MANAGER", value: "CONSTRUCTIONMANAGER" },
        { label: "ARCHITECT", value: "ARCHITECT" },
        { label: "CIVIL ENGINEER", value: "CIVILENGINEER" },
        { label: "SITE SUPERVISOR", value: "SITESUPERVISOR" },
        { label: "ELECTRICAL ENGINEER", value: "ELECTRICALENGINEER" },
        { label: "PLUMBING CONTRACTOR", value: "PLUMBINGCONTRACTOR" },
        { label: "HEAVY EQUIPMENT OPERATOR", value: "HEAVYEQUIPMENTOPERATOR" },
        { label: "SAFETY MANAGER", value: "SAFETYMANAGER" },
        { label: "DRAFTSPERSON", value: "DRAFTSPERSON" },
        { label: "CARPENTER", value: "CARPENTER" },
    ],
    "HOSPITALITY": [
        { label: "HOTEL MANAGER", value: "HOTELMANAGER" },
        { label: "RESTAURANT MANAGER", value: "RESTAURANTMANAGER" },
        { label: "FRONT DESK AGENT", value: "FRONTDESKAGENT" },
        { label: "EVENT COORDINATOR", value: "EVENTCOORDINATOR" },
        { label: "CATERING MANAGER", value: "CATERINGMANAGER" },
        { label: "HOUSEKEEPING SUPERVISOR", value: "HOUSEKEEPINGSUPERVISOR" },
        { label: "BARTENDER", value: "BARTENDER" },
        { label: "CHEF", value: "CHEF" },
        { label: "CONCIERGE", value: "CONCIERGE" },
        { label: "ROOM SERVICE ATTENDANT", value: "ROOMSERVICEATTENDANT" },
    ],
    "TRANSPORTATION": [
        { label: "LOGISTICS MANAGER", value: "LOGISTICSMANAGER" },
        { label: "FREIGHT BROKER", value: "FREIGHTBROKER" },
        { label: "SHIPPING COORDINATOR", value: "SHIPPINGCOORDINATOR" },
        { label: "PUBLIC TRANSPORT OPERATOR", value: "PUBLICTRANSPORTOPERATOR" },
        { label: "RIDE SHARE DRIVER", value: "RIDESHAREDRIVER" },
        { label: "TRUCK DRIVER", value: "TRUCKDRIVER" },
        { label: "AIRLINE PILOT", value: "AIRLINEPILOT" },
        { label: "RAILROAD OPERATIONS MANAGER", value: "RAILROADOPERATIONS" },
        { label: "MARINE CAPTAIN", value: "MARINECAPTAIN" },
        { label: "COURIER DRIVER", value: "COURIERDRIVER" },
    ],
    "REAL ESTATE": [
        { label: "REAL ESTATE AGENT", value: "REALESTATEAGENT" },
        { label: "PROPERTY MANAGER", value: "PROPERTYMANAGER" },
        { label: "REAL ESTATE APPRAISER", value: "REALESTATEAPPRAISER" },
        { label: "REAL ESTATE ANALYST", value: "REALESTATEANALYST" },
        { label: "REAL ESTATE DEVELOPER", value: "REALESTATEDEVELOPER" },
        { label: "LEASING AGENT", value: "LEASINGAGENT" },
        { label: "CLOSING AGENT", value: "CLOSINGAGENT" },
        { label: "COMMERCIAL REAL ESTATE BROKER", value: "COMMERCIALBROKER" },
        { label: "REAL ESTATE MARKETER", value: "REALESTATEMARKETER" },
        { label: "HOA MANAGER", value: "HOAMANAGER" },
    ],
    "TELECOMMUNICATIONS": [
        { label: "NETWORK ENGINEER", value: "NETWORKENGINEER" },
        { label: "TELECOM TECHNICIAN", value: "TELECOMTECHNICIAN" },
        { label: "BROADBAND INSTALLER", value: "BROADBANDINSTALLER" },
        { label: "SALES REPRESENTATIVE", value: "SALESREPRESENTATIVE" },
        { label: "CUSTOMER SERVICE REPRESENTATIVE", value: "CUSTOMERSERVICEREP" },
        { label: "PRODUCT MANAGER", value: "PRODUCTMANAGER" },
        { label: "TELECOM ANALYST", value: "TELECOMANALYST" },
        { label: "FIELD SERVICE TECHNICIAN", value: "FIELDSERVICETECHNICIAN" },
        { label: "MARKETING COORDINATOR", value: "MARKETINGCOORDINATOR" },
        { label: "RESEARCH ANALYST", value: "RESEARCHANALYST" },
    ],
    "ENERGY": [
        { label: "ENERGY ANALYST", value: "ENERGYANALYST" },
        { label: "RENEWABLE ENERGY ENGINEER", value: "RENEWABLEENERGYENGINEER" },
        { label: "POWER PLANT OPERATOR", value: "POWERPLANTOPERATOR" },
        { label: "OIL AND GAS ENGINEER", value: "OILGASENGINEER" },
        { label: "SOLAR INSTALLER", value: "SOLARINSTALLER" },
        { label: "WIND TURBINE TECHNICIAN", value: "WINDTURBINETECHNICIAN" },
        { label: "ELECTRICAL ENGINEER", value: "ELECTRICALENGINEER" },
        { label: "FOSSIL FUEL ANALYST", value: "FOSSILFUELANALYST" },
        { label: "ENERGY AUDITOR", value: "ENERGYAUDITOR" },
        { label: "UTILITY MANAGER", value: "UTILITYMANAGER" },
    ],
    "AGRICULTURE": [
        { label: "FARM MANAGER", value: "FARMMANAGER" },
        { label: "AGRONOMIST", value: "AGRONOMIST" },
        { label: "CROP SPECIALIST", value: "CROPSPECIALIST" },
        { label: "LIVESTOCK SPECIALIST", value: "LIVESTOCKSPECIALIST" },
        { label: "AGRICULTURAL ENGINEER", value: "AGRICULTURALENGINEER" },
        { label: "SOIL SCIENTIST", value: "SOILSCIENTIST" },
        { label: "HORTICULTURIST", value: "HORTICULTURIST" },
        { label: "AGRICULTURAL TECHNICIAN", value: "AGRICULTURALTECHNICIAN" },
        { label: "VETERINARIAN", value: "VETERINARIAN" },
        { label: "AQUACULTURE MANAGER", value: "AQUACULTUREMANAGER" },
    ],
    "PHARMACEUTICALS": [
        { label: "PHARMACIST", value: "PHARMACIST" },
        { label: "RESEARCH SCIENTIST", value: "RESEARCHSCIENTIST" },
        { label: "CLINICAL TRIAL MANAGER", value: "CLINICALTRIALMANAGER" },
        { label: "REGULATORY AFFAIRS SPECIALIST", value: "REGULATORYAFFAIRS" },
        { label: "QUALITY ASSURANCE OFFICER", value: "QUALITYASSURANCEOFFICER" },
        { label: "PRODUCTION SUPERVISOR", value: "PRODUCTIONSUPERVISOR" },
        { label: "MEDICAL SCIENCE LIAISON", value: "MEDICALSCIENCELIAISON" },
        { label: "PHARMACEUTICAL SALES REPRESENTATIVE", value: "PHARMACEUTICALSALESREP" },
        { label: "BIOSTATISTICIAN", value: "BIOSTATISTICIAN" },
        { label: "FORMULATION SCIENTIST", value: "FORMULATIONSCIENTIST" },
    ],
    "ENTERTAINMENT": [
        { label: "FILM DIRECTOR", value: "FILMDIRECTOR" },
        { label: "PRODUCER", value: "PRODUCER" },
        { label: "SCREENWRITER", value: "SCREENWRITER" },
        { label: "ACTOR", value: "ACTOR" },
        { label: "MUSICIAN", value: "MUSICIAN" },
        { label: "EVENT PLANNER", value: "EVENTPLANNER" },
        { label: "MARKETING MANAGER", value: "MARKETINGMANAGER" },
        { label: "STAGE MANAGER", value: "STAGEMANAGER" },
        { label: "SET DESIGNER", value: "SETDESIGNER" },
        { label: "COSTUME DESIGNER", value: "COSTUMEDESIGNER" },
    ],
    "MEDIA": [
        { label: "JOURNALIST", value: "JOURNALIST" },
        { label: "EDITOR", value: "EDITOR" },
        { label: "GRAPHIC DESIGNER", value: "GRAPHICDESIGNER" },
        { label: "DIGITAL CONTENT CREATOR", value: "DIGITALCONTENTCREATOR" },
        { label: "SOCIAL MEDIA MANAGER", value: "SOCIALMEDIAMANAGER" },
        { label: "PUBLIC RELATIONS SPECIALIST", value: "PUBLICRELATIONSSPECIALIST" },
        { label: "COPYWRITER", value: "COPYWRITER" },
        { label: "MARKETING ANALYST", value: "MARKETINGANALYST" },
        { label: "BROADCAST TECHNICIAN", value: "BROADCASTTECHNICIAN" },
        { label: "FILM EDITOR", value: "FILMEDITOR" },
    ],
    "INSURANCE": [
        { label: "INSURANCE AGENT", value: "INSURANCEAGENT" },
        { label: "CLAIMS ADJUSTER", value: "CLAIMSADJUSTER" },
        { label: "UNDERWRITER", value: "UNDERWRITER" },
        { label: "RISK ANALYST", value: "RISKANALYST" },
        { label: "LOSS CONTROL SPECIALIST", value: "LOSSCONTROLSPECIALIST" },
        { label: "ACTUARY", value: "ACTUARY" },
        { label: "CUSTOMER SERVICE REPRESENTATIVE", value: "CUSTOMERSERVICEREP" },
        { label: "PRODUCT MANAGER", value: "PRODUCTMANAGER" },
        { label: "COMPLIANCE OFFICER", value: "COMPLIANCEOFFICER" },
        { label: "MARKETING MANAGER", value: "MARKETINGMANAGER" },
    ],
    "LEGAL SERVICES": [
        { label: "LAWYER", value: "LAWYER" },
        { label: "LEGAL ASSISTANT", value: "LEGALASSISTANT" },
        { label: "PARALEGAL", value: "PARALEGAL" },
        { label: "CORPORATE COUNSEL", value: "CORPORATECOUNSEL" },
        { label: "INTELLECTUAL PROPERTY SPECIALIST", value: "INTELLECTUALPROPERTYSPECIALIST" },
        { label: "FAMILY LAW ATTORNEY", value: "FAMILYLAWATTORNEY" },
        { label: "CRIMINAL DEFENSE ATTORNEY", value: "CRIMINALDEFENSEATTORNEY" },
        { label: "REAL ESTATE ATTORNEY", value: "REALESTATEATTORNEY" },
        { label: "LITIGATION SPECIALIST", value: "LITIGATIONSPECIALIST" },
        { label: "MEDIATOR", value: "MEDIATOR" },
    ],
    "NON-PROFIT": [
        { label: "PROGRAM DIRECTOR", value: "PROGRAMDIRECTOR" },
        { label: "FUNDRAISING COORDINATOR", value: "FUNDRAISINGCOORDINATOR" },
        { label: "GRANT WRITER", value: "GRANTWRITER" },
        { label: "COMMUNITY OUTREACH SPECIALIST", value: "COMMUNITYOUTREACHSPECIALIST" },
        { label: "VOLUNTEER COORDINATOR", value: "VOLUNTEERCOORDINATOR" },
        { label: "NON-PROFIT ADMINISTRATOR", value: "NONPROFITADMINISTRATOR" },
        { label: "ADVOCACY DIRECTOR", value: "ADVOCACYDIRECTOR" },
        { label: "RESEARCH ANALYST", value: "RESEARCHANALYST" },
        { label: "EVENT PLANNER", value: "EVENTPLANNER" },
        { label: "MARKETING DIRECTOR", value: "MARKETINGDIRECTOR" },
        { label: "COMMUNICATIONS MANAGER", value: "COMMUNICATIONSMANAGER" },
    ],
    "CONSULTING": [
        { label: "MANAGEMENT CONSULTANT", value: "MANAGEMENTCONSULTANT" },
        { label: "STRATEGY CONSULTANT", value: "STRATEGYCONSULTANT" },
        { label: "HR CONSULTANT", value: "HRCONSULTANT" },
        { label: "IT CONSULTANT", value: "ITCONSULTANT" },
        { label: "MARKETING CONSULTANT", value: "MARKETINGCONSULTANT" },
        { label: "OPERATIONS CONSULTANT", value: "OPERATIONSCONSULTANT" },
        { label: "FINANCIAL CONSULTANT", value: "FINANCIALCONSULTANT" },
        { label: "SUPPLY CHAIN CONSULTANT", value: "SUPPLYCHAINCONSULTANT" },
        { label: "CHANGE MANAGEMENT CONSULTANT", value: "CHANGEMANAGEMENTCONSULTANT" },
        { label: "DATA ANALYTICS CONSULTANT", value: "DATAANALYTICSCONSULTANT" },
    ],
    "FASHION": [
        { label: "FASHION DESIGNER", value: "FASHIONDESIGNER" },
        { label: "TEXTILE DESIGNER", value: "TEXTILEDESIGNER" },
        { label: "MERCHANDISE BUYER", value: "MERCHANDISEBUYER" },
        { label: "FASHION STYLIST", value: "FASHIONSTYLIST" },
        { label: "MARKETING MANAGER", value: "MARKETINGMANAGER" },
        { label: "FASHION PHOTOGRAPHER", value: "FASHIONPHOTOGRAPHER" },
        { label: "PRODUCTION MANAGER", value: "PRODUCTIONMANAGER" },
        { label: "BRAND MANAGER", value: "BRANDMANAGER" },
        { label: "RETAIL MANAGER", value: "RETAILMANAGER" },
        { label: "FASHION WRITER", value: "FASHIONWRITER" },
        { label: "OTHER", value: "OTHER" }
    ],
    "FOOD AND BEVERAGE": [
        { label: "FOOD SERVICE MANAGER", value: "FOODSERVICEMANAGER" },
        { label: "SOMMELIER", value: "SOMMELIER" },
        { label: "CATERING MANAGER", value: "CATERINGMANAGER" },
        { label: "RESEARCH CHEF", value: "RESEARCHCHEF" },
        { label: "FOOD PRODUCT DEVELOPER", value: "FOODPRODUCTDEVELOPER" },
        { label: "NUTRITIONIST", value: "NUTRITIONIST" },
        { label: "BAKER", value: "BAKER" },
        { label: "SERVICE STAFF", value: "SERVICESTAFF" },
        { label: "COOK", value: "COOK" },
        { label: "FOOD SAFETY SPECIALIST", value: "FOODSAFETYSPECIALIST" },
    ],
    "AEROSPACE": [
        { label: "AEROSPACE ENGINEER", value: "AEROSPACEENGINEER" },
        { label: "FLIGHT TEST ENGINEER", value: "FLIGHTTESTENGINEER" },
        { label: "AVIONICS TECHNICIAN", value: "AVIONICSTECHNICIAN" },
        { label: "DEFENSE ANALYST", value: "DEFENSEANALYST" },
        { label: "SPACECRAFT OPERATOR", value: "SPACECRAFTOPERATOR" },
    ],
    "BIOTECHNOLOGY": [
        { label: "BIOTECH RESEARCHER", value: "BIOTECHRESEARCHER" },
        { label: "LAB TECHNICIAN", value: "LABTECHNICIAN" },
        { label: "BIOINFORMATICIAN", value: "BIOINFORMATICIAN" },
        { label: "REGULATORY AFFAIRS SPECIALIST", value: "REGULATORYAFFAIRS" },
        { label: "QUALITY CONTROL ANALYST", value: "QUALITYCONTROL" },
    ],
    "ENVIRONMENTAL SERVICES": [
        { label: "ENVIRONMENTAL SCIENTIST", value: "ENVIRONMENTALSCIENTIST" },
        { label: "WASTE MANAGEMENT SPECIALIST", value: "WASTEMANAGEMENTSPECIALIST" },
        { label: "RECYCLING COORDINATOR", value: "RECYCLINGCOORDINATOR" },
        { label: "POLLUTION CONTROL ENGINEER", value: "POLLUTIONCONTROLENGINEER" },
        { label: "SUSTAINABILITY CONSULTANT", value: "SUSTAINABILITYCONSULTANT" },
    ],
    "REAL ESTATE DEVELOPMENT": [
        { label: "COMMERCIAL REAL ESTATE BROKER", value: "COMMERCIALBROKER" },
        { label: "RESIDENTIAL REAL ESTATE AGENT", value: "RESIDENTIALAGENT" },
        { label: "REAL ESTATE PROJECT MANAGER", value: "PROJECTMANAGER" },
        { label: "REAL ESTATE INVESTMENT ANALYST", value: "INVESTMENTANALYST" },
        { label: "PROPERTY DEVELOPMENT ANALYST", value: "PROPERTYDEVELOPMENTANALYST" },
    ],
    "MEDIA AND ENTERTAINMENT": [
        { label: "SCRIPTWRITER", value: "SCRIPTWRITER" },
        { label: "MUSIC PRODUCER", value: "MUSICPRODUCER" },
        { label: "VIDEO EDITOR", value: "VIDEOEDITOR" },
        { label: "SOUND ENGINEER", value: "SOUNDENGINEER" },
        { label: "MARKETING COORDINATOR", value: "MARKETINGCOORDINATOR" },
    ],
    "TRANSPORTATION SERVICES": [
        { label: "DISPATCHER", value: "DISPATCHER" },
        { label: "LOGISTICS COORDINATOR", value: "LOGISTICSCOORDINATOR" },
        { label: "FLEET MANAGER", value: "FLEETMANAGER" },
        { label: "TRANSPORTATION PLANNER", value: "TRANSPORTATIONPLANNER" },
        { label: "SALES REPRESENTATIVE", value: "SALESREPRESENTATIVE" },
    ],
    "FARMING AND AGRICULTURE": [
        { label: "FARM EQUIPMENT OPERATOR", value: "FARMEQUIPMENTOPERATOR" },
        { label: "AGRICULTURAL RESEARCHER", value: "AGRICULTURALRESEARCHER" },
        { label: "CROP INSPECTOR", value: "CROPINSPECTOR" },
        { label: "HATCHERY MANAGER", value: "HATCHERYMANAGER" },
        { label: "AGRICULTURAL ECONOMIST", value: "AGRICULTURALECONOMIST" },
    ],
    "PHOTOGRAPHY AND GRAPHIC DESIGN": [
        { label: "FASHION PHOTOGRAPHER", value: "FASHIONPHOTOGRAPHER" },
        { label: "PRODUCT PHOTOGRAPHER", value: "PRODUCTPHOTOGRAPHER" },
        { label: "EDITORIAL PHOTOGRAPHER", value: "EDITORIALPHOTOGRAPHER" },
        { label: "ADVERTISING DESIGNER", value: "ADVERTISINGDESIGNER" },
        { label: "DIGITAL ILLUSTRATOR", value: "DIGITALILLUSTRATOR" },
    ],
    "SPORTS AND RECREATION": [
        { label: "ATHLETIC DIRECTOR", value: "ATHLETICDIRECTOR" },
        { label: "SPORTS COACH", value: "SPORTSCOACH" },
        { label: "SPORTS THERAPIST", value: "SPORTSTHERAPIST" },
        { label: "RECREATION DIRECTOR", value: "RECREATIONDIRECTOR" },
        { label: "FITNESS INSTRUCTOR", value: "FITNESSINSTRUCTOR" },
    ],
    "TOURISM AND TRAVEL": [
        { label: "TOUR GUIDE", value: "TOURGUIDE" },
        { label: "TRAVEL WRITER", value: "TRAVELWRITER" },
        { label: "DESTINATION MANAGER", value: "DESTINATIONMANAGER" },
        { label: "TRAVEL CONSULTANT", value: "TRAVELCONSULTANT" },
        { label: "ADVENTURE TOUR GUIDE", value: "ADVENTURETOURGUIDE" },
    ]
}

export const accountTypes = [
    { label: "INDIVIDUAL", value: "INDIVIDUAL" },
    { label: "JOINT", value: "JOINT" },
]

export const bankAccountTypes = [
    { label: "CURRENT ACCOUNT", value: "CURRENT ACCOUNT" },
    { label: "SAVINGS ACCOUNT", value: "SAVINGS ACCOUNT" },
]

export const currencTypes = [
    { label: "USD", value: "USD" },
    { label: "ZWG", value: "ZWG" },
    { label: "ZAR", value: "ZAR" },
]

export const sourcesOfFunds = [
    { label: "BUSINESS INCOME", value: "BUSINESS INCOME" },
    { label: "INVESTMENT EARNINGS", value: "INVESTMENT EARNINGS" },
    { label: "INHERITANCE", value: "INHERITANCE" },
    { label: "LOAN PROCEEDS", value: "LOAN PROCEEDS" },
    { label: "PENSION", value: "PENSION" },
    { label: "RENTAL INCOME", value: "RENTAL INCOME" },
    { label: "ALLOWANCE", value: "ALLOWANCE" },
    { label: "OTHER", value: "OTHER" },
];

export const timeIntervals = [
    { label: "MONTHLY", value: "MONTHLY" },
    { label: "QUARTERLY", value: "QUARTERLY" },
    { label: "YEARLY", value: "YEARLY" },
]

export const yesNoOptions = [
    { label: "YES", value: "YES" },
    { label: "NO", value: "NO" },
]

export const colors = [
    { label: "BLACK", value: "BLACK" },
    { label: "WHITE", value: "WHITE" },
    { label: "SILVER", value: "SILVER" },
    { label: "GRAY", value: "GRAY" },
    { label: "RED", value: "RED" },
    { label: "BLUE", value: "BLUE" },
    { label: "GREEN", value: "GREEN" },
    { label: "YELLOW", value: "YELLOW" },
    { label: "BROWN", value: "BROWN" },
    { label: "ORANGE", value: "ORANGE" },
    { label: "PURPLE", value: "PURPLE" },
    { label: "GOLD", value: "GOLD" },
    { label: "PINK", value: "PINK" },
    { label: "BEIGE", value: "BEIGE" },
    { label: "TEAL", value: "TEAL" },
    { label: "MAROON", value: "MAROON" },
    { label: "TURQUOISE", value: "TURQUOISE" },
    { label: "LAVENDER", value: "LAVENDER" },
    { label: "CREAM", value: "CREAM" },
    { label: "BURGUNDY", value: "BURGUNDY" },
    { label: "SKY BLUE", value: "SKY BLUE" },
    { label: "MINT GREEN", value: "MINT GREEN" },
    { label: "COPPER", value: "COPPER" },
    { label: "CHARCOAL", value: "CHARCOAL" },
    { label: "IVORY", value: "IVORY" }
];

export const educationLevels = [
    { label: 'PRIMARY EDUCATION', value: 'PRIMARY EDUCATION' },
    { label: 'O-LEVEL', value: 'O-LEVEL' },
    { label: 'A-LEVEL', value: 'A-LEVEL' },
    { label: 'TERTIARY EDUCATION', value: 'TERTIARY EDUCATION' },
    { label: 'MASTERS DEGREE', value: 'MASTERS DEGREE' },
    { label: 'DOCTORATE', value: 'DOCTORATE' },
];

// allDocumentLookup lists the documents types that can be uploaded for each document category
export const allDocumentsLookup = {
    "PROFILE": [
        { label: "PROFILE IMAGE", value: "PROFILE IMAGE" },
    ],
    "SPECIMEN SIGNATURE": [
        { label: "SPECIMEN SIGNATURE", value: "SPECIMEN SIGNATURE" },
    ],
    "PROOF OF IDENTITY": [
        { label: "NATIONAL ID", value: "NATIONAL ID" },
        { label: "PASSPORT", value: "PASSPORT" },
        { label: "DRIVERS LICENSE", value: "DRIVERS LICENSE" },
        { label: "BIRTH CERTIFICATE", value: "BIRTH CERTIFICATE" },
    ],
    "PROOF OF RESIDENCE": [
        { label: "PROOF OF RESIDENCE", value: "PROOF OF RESIDENCE" },
    ],
    "PROOF OF INCOME": [
        { label: "PAYSLIP", value: "PAYSLIP" },
        { label: "BANK STATEMENT", value: "BANK STATEMENT" },
        { label: "EMPLOYMENT VERIFICATION LETTER", value: "EMPLOYMENT VERIFICATION LETTER" },
    ],
    "APPLICATION FORM": [
        { label: "ACCOUNT APPLICATION FORM", value: "ACCOUNT APPLICATION FORM" },
    ],
    "VEHICLE IDENTITY": [
        { label: "VEHICLE IMAGE", value: "VEHICLE IMAGE" },
        { label: "VEHICLE REGISTRATION DOCUMENT", value: "VEHICLE REGISTRATION DOCUMENT" },
    ],
    "BUSINESS PROFILE": [
        { label: "COMPANY LOGO", value: "COMPANY LOGO" },
        { label: "BUSINESS PROFILE DOCUMENT", value: "BUSINESS PROFILE DOCUMENT" },
    ],
    "BUSINESS PROOF OF IDENTITY": [
        { label: "COMPANY REGISTRATION DOCUMENT", value: "COMPANY REGISTRATION DOCUMENT" },
        { label: "TAX IDENTIFICATION NUMBER (TIN)", value: "TAX IDENTIFICATION NUMBER (TIN)" },
    ],
    "BUSINESS FINANCIAL DOCUMENTS": [
        { label: "FINANCIAL STATEMENTS", value: "FINANCIAL STATEMENTS" },
        { label: "TAX RETURNS", value: "TAX RETURNS" },
        { label: "INVOICES", value: "INVOICES" },
    ],
    "BUSINESS LEGAL DOCUMENTS": [
        { label: "CONTRACTS", value: "CONTRACTS" },
        { label: "NON-DISCLOSURE AGREEMENT", value: "NON-DISCLOSURE AGREEMENT" },
    ],
}

export const documentTypes = [
    { label: "IMAGE", value: "IMAGE" },
    { label: "PDF", value: "PDF" }
]

export const industriesLookup = {
    "TECHNOLOGY": [
        { label: "SOFTWARE DEVELOPMENT", value: "SOFTWARE DEVELOPMENT" },
        { label: "INFORMATION TECHNOLOGY SERVICES", value: "IT SERVICES" },
        { label: "CYBERSECURITY", value: "CYBERSECURITY" },
        { label: "ARTIFICIAL INTELLIGENCE", value: "ARTIFICIAL INTELLIGENCE" },
    ],
    "FINANCE": [
        { label: "BANKING", value: "BANKING" },
        { label: "INVESTMENT SERVICES", value: "INVESTMENT SERVICES" },
        { label: "INSURANCE", value: "INSURANCE" },
        { label: "ACCOUNTING", value: "ACCOUNTING" },
    ],
    "HEALTHCARE": [
        { label: "PHARMACEUTICALS", value: "PHARMACEUTICALS" },
        { label: "MEDICAL DEVICES", value: "MEDICAL DEVICES" },
        { label: "HEALTH INSURANCE", value: "HEALTH INSURANCE" },
        { label: "HEALTHCARE SERVICES", value: "HEALTHCARE SERVICES" },
    ],
    "MANUFACTURING": [
        { label: "AUTOMOTIVE", value: "AUTOMOTIVE" },
        { label: "ELECTRONICS", value: "ELECTRONICS" },
        { label: "TEXTILES", value: "TEXTILES" },
        { label: "FOOD PROCESSING", value: "FOOD PROCESSING" },
    ],
    "RETAIL": [
        { label: "E-COMMERCE", value: "E-COMMERCE" },
        { label: "SUPERMARKETS", value: "SUPERMARKETS" },
        { label: "CLOTHING STORES", value: "CLOTHING STORES" },
        { label: "CONSUMER ELECTRONICS", value: "CONSUMER ELECTRONICS" },
    ],
    "EDUCATION": [
        { label: "HIGHER EDUCATION", value: "HIGHER EDUCATION" },
        { label: "K-12 EDUCATION", value: "K-12 EDUCATION" },
        { label: "ONLINE LEARNING", value: "ONLINE LEARNING" },
        { label: "VOCATIONAL TRAINING", value: "VOCATIONAL TRAINING" },
    ],
    "CONSTRUCTION": [
        { label: "RESIDENTIAL CONSTRUCTION", value: "RESIDENTIAL CONSTRUCTION" },
        { label: "COMMERCIAL CONSTRUCTION", value: "COMMERCIAL CONSTRUCTION" },
        { label: "INFRASTRUCTURE DEVELOPMENT", value: "INFRASTRUCTURE DEVELOPMENT" },
        { label: "RENOVATION AND REMODELING", value: "RENOVATION AND REMODELING" },
    ],
    "HOSPITALITY": [
        { label: "HOTELS", value: "HOTELS" },
        { label: "RESTAURANTS", value: "RESTAURANTS" },
        { label: "TRAVEL SERVICES", value: "TRAVEL SERVICES" },
        { label: "EVENT PLANNING", value: "EVENT PLANNING" },
    ],
    "AGRICULTURE": [
        { label: "CROP PRODUCTION", value: "CROP PRODUCTION" },
        { label: "LIVESTOCK FARMING", value: "LIVESTOCK FARMING" },
        { label: "AQUACULTURE", value: "AQUACULTURE" },
        { label: "AGRICULTURAL TECHNOLOGY", value: "AGRICULTURAL TECHNOLOGY" },
    ],
    "OTHER": [
        { label: "OTHER", value: "OTHER" },
    ],
};

export const allMonthsLookup = {
    0: "Jan",
    1: "Feb",
    2: "Mar",
    3: "Apr",
    4: "May",
    5: "Jun",
    6: "Jul",
    7: "Aug",
    8: "Sep",
    9: "Oct",
    10: "Nov",
    11: "Dec",
};

export const relationshipsList = [
    { label: "BROTHER", value: "BROTHER" },
    { label: "SISTER", value: "SISTER" },
    { label: "FATHER", value: "FATHER" },
    { label: "MOTHER", value: "MOTHER" },
    { label: "SON", value: "SON" },
    { label: "DAUGHTER", value: "DAUGHTER" },
    { label: "UNCLE", value: "UNCLE" },
    { label: "AUNT", value: "AUNT" },
    { label: "COUSIN", value: "COUSIN" },
    { label: "GRANDPARENT", value: "GRANDPARENT" },
    { label: "FRIEND", value: "FRIEND" }
];

export const branches = [
    { label: "VIRTUAL BRANCH", value: "VIRTUAL_BRANCH" },
    { label: "8TH AVENUE", value: "8TH_AVENUE" },
    { label: "ABC BULAWAYO", value: "ABC_BULAWAYO" },
    { label: "ABC HARARE", value: "ABC_HARARE" },
    { label: "AIRPORT AGENCY", value: "AIRPORT_AGENCY" },
    { label: "AVONDALE", value: "AVONDALE" },
    { label: "BEITBRIDGE", value: "BEITBRIDGE" },
    { label: "BELMONT", value: "BELMONT" },
    { label: "BINDURA", value: "BINDURA" },
    { label: "BOKA TOBACCO AGENCY", value: "BOKA_TOBACCO_AGENCY" },
    { label: "BORROWDALE", value: "BORROWDALE" },
    { label: "BULAWAYO CCD", value: "BULAWAYO_CCD" },
    { label: "CHECHECHE", value: "CHECHECHE" },
    { label: "CHEGUTU", value: "CHEGUTU" },
    { label: "CHIMANIMANI", value: "CHIMANIMANI" },
    { label: "CHINHOYI", value: "CHINHOYI" },
    { label: "CHIPINGE", value: "CHIPINGE" },
    { label: "CHIREDZI", value: "CHIREDZI" },
    { label: "CHIRUNDU", value: "CHIRUNDU" },
    { label: "CHITUNGWIZA MAKONI BRANCH", value: "CHITUNGWIZA_MAKONI_BRANCH" },
    { label: "CHIVHU", value: "CHIVHU" },
    { label: "CRIPPS ROAD BRANCH", value: "CRIPPS_ROAD_BRANCH" },
    { label: "FIFE STREET", value: "FIFE_STREET" },
    { label: "GOKWE", value: "GOKWE" },
    { label: "GUTU", value: "GUTU" },
    { label: "GWANDA", value: "GWANDA" },
    { label: "GWERU", value: "GWERU" },
    { label: "HARARE CCD", value: "HARARE_CCD" },
    { label: "HIGHFIELD", value: "HIGHFIELD" },
    { label: "JOSHUA NKOMO AIRPORT BRANCH", value: "JOSHUA_NKOMO_AIRPORT_BRANCH" },
    { label: "KADOMA BRANCH", value: "KADOMA_BRANCH" },
    { label: "KARIBA", value: "KARIBA" },
    { label: "KAROI", value: "KAROI" },
    { label: "KWAME NKURUMAH", value: "KWAME_NKURUMAH" },
    { label: "KWEKWE", value: "KWEKWE" },
    { label: "MARONDERA", value: "MARONDERA" },
    { label: "MASVINGO", value: "MASVINGO" },
    { label: "MSASA", value: "MSASA" },
    { label: "MTC AGENCY", value: "MTC_AGENCY" },
    { label: "MUREHWA", value: "MUREHWA" },
    { label: "MUTARE", value: "MUTARE" },
    { label: "MUTOKO AGENCY", value: "MUTOKO_AGENCY" },
    { label: "MVURWI", value: "MVURWI" },
    { label: "NEMBUDZIYA", value: "NEMBUDZIYA" },
    { label: "NORTON", value: "NORTON" },
    { label: "NYANGA", value: "NYANGA" },
    { label: "NYIKA", value: "NYIKA" },
    { label: "REDCLIFF SUB BRANCH", value: "REDCLIFF_SUB_BRANCH" },
    { label: "ROBERT MUGABE", value: "ROBERT_MUGABE" },
    { label: "RUSAPE", value: "RUSAPE" },
    { label: "SAMORA MACHEL", value: "SAMORA_MACHEL" },
    { label: "SAPPHIRE HOUSE", value: "SAPPHIRE_HOUSE" },
    { label: "SELOUS AVE BRANCH", value: "SELOUS_AVE_BRANCH" },
    { label: "SOUTHERTON", value: "SOUTHERTON" },
    { label: "TSF TOBACCO AGENCY", value: "TSF_TOBACCO_AGENCY" },
    { label: "UNIVERSITY OF ZIMBABWE AGENCY", value: "UNIVERSITY_OF_ZIMBABWE_AGENCY" },
    { label: "VICTORIA FALLS", value: "VICTORIA_FALLS" },
    { label: "WEALTH MANAGEMENT SUITE", value: "WEALTH_MANAGEMENT_SUITE" },
    { label: "WESTGATE", value: "WESTGATE" },
    { label: "ZVISHAVANE", value: "ZVISHAVANE" },
];


export const BANKS_ZIMBABWE = [
    { value: 'AGRIBANK', label: 'AGRIBANK' },
    { value: 'BANCABC', label: 'BANCABC' },
    { value: 'FIRSTCAP', label: 'FIRSTCAP' },
    { value: 'CBZ', label: 'CBZ' },
    { value: 'ECOBANK', label: 'ECOBANK' },
    { value: 'FBC', label: 'FBC' },
    { value: 'NEDBANK', label: 'NEDBANK' },
    { value: 'METBANK', label: 'METBANK' },
    { value: 'NMB', label: 'NMB' },
    { value: 'STANBIC', label: 'STANBIC' },
    { value: 'STANCHART', label: 'STANCHART' },
    { value: 'STEWARD', label: 'STEWARD' },
    { value: 'ZB', label: 'ZB' },
    { value: 'CABS', label: 'CABS' },
    { value: 'FBCBS', label: 'FBCBS' },
    { value: 'NBS', label: 'NBS' },
    { value: 'POSB', label: 'POSB' },
    { value: 'EMPOWERBANK', label: 'EMPOWERBANK' },
    { value: 'GETBUCKS', label: 'GETBUCKS' },
    { value: 'INNBUCKS', label: 'INNBUCKS' },
    { value: 'LIONMF', label: 'LIONMF' },
    { value: 'SUCCESSMF', label: 'SUCCESSMF' },
    { value: 'ZWMB', label: 'ZWMB' },
    { value: 'IDBZ', label: 'IDBZ' },
    { value: 'SMEDCO', label: 'SMEDCO' },
    { value: 'AFCBANK', label: 'AFCBANK' }
  ] ;
  
  
  