export const insuranceCompanies = [
  'Old Mutual Zimbabwe',
  'Zimnat Insurance',
  'NicozDiamond Insurance',
  'First Mutual Life Assurance',
  'Econet Life',
  'Alliance Insurance',
  'Sanlam Zimbabwe',
  'ZB Life Assurance',
  'CBZ Life',
  'Evolution Insurance',
  'Moovah Insurance',
  'Premier Service Medical Aid Society (PSMAS)',
  'First Mutual Health',
  'Cimas Health Group',
  'Generation Health',
  'Zimbabwe Reinsurance Company (ZimRe)',
  'FBC Reinsurance',
  'Baobab Reinsurance',
  'Credsure',
  'Minerva Risk Advisors',
  'Heritage Insurance Brokers',
  'Risk Management Services',
  'Marsh Zimbabwe'
];
