export const programs = [
  'Bachelor of Accounting (Honours)',
  'Bachelor of Agricultural Sciences (Honours) in Agricultural Economics',
  'Bachelor of Agricultural Sciences (Honours) in Animal Science and Rangeland Management',
  'Bachelor of Agricultural Sciences (Honours) in Crop Science',
  'Bachelor of Agricultural Sciences (Honours) in Forest Resources Management',
  'Bachelor of Agricultural Sciences (Honours) in Horticulture and Landscaping',
  'Bachelor of Agricultural Sciences (Honours) in Soil Science',
  'Bachelor of Agricultural Sciences (Honours) in Wildlife Resources Management',
  'Bachelor of Agricultural Sciences (Special Honours) in Animal Science',
  'Bachelor of Agricultural Sciences (Special Honours) in Crop Science',
  'Bachelor of Arts (Honours) in Chaplaincy',
  'Bachelor of Arts (Honours) in Development Studies',
  'Bachelor of Arts (Honours) in Development Studies (ZEGU)',
  'Bachelor of Arts (Honours) in English and Communication Studies',
  'Bachelor of Arts (Honours) in Gender and Cultural Studies',
  'Bachelor of Arts (Honours) in History',
  'Bachelor of Arts (Honours) in Humanities',
  'Bachelor of Arts (Honours) in Inclusive Education',
  'Bachelor of Arts (Honours) in Language and Literature',
  'Bachelor of Arts (Honours) in Linguistics',
  'Bachelor of Arts (Honours) in Media and Journalism',
  'Bachelor of Arts (Honours) in Ndebele',
  'Bachelor of Arts (Honours) in Peace and Conflict Studies',
  'Bachelor of Arts (Honours) in Philosophy',
  'Bachelor of Arts (Honours) in Religious Studies',
  'Bachelor of Arts (Honours) in Shona',
  'Bachelor of Arts (Honours) in Social Sciences',
  'Bachelor of Arts (Honours) in Social Work (ZEGU)',
  'Bachelor of Arts (Honours) in Theology',
  'Bachelor of Arts (Honours) in Theology and Religious Studies',
  'Bachelor of Arts (Honours) in Theology for Social Development',
  'Bachelor of Arts (Honours) in Transformational Leadership',
  'Bachelor of Arts (Honours) in Translation and Interpretation in Language',
  'Bachelor of Arts (Honours) with Education (various)',
  'Bachelor of Arts (Honours) with Education in English',
  'Bachelor of Arts (Honours) with Education in Geography',
  'Bachelor of Arts (Honours) with Education in History',
  'Bachelor of Arts (Honours) with Education in Music',
  'Bachelor of Arts (Honours) with Education in Religious Studies',
  'Bachelor of Business Administration (Honours) in Accounting',
  'Bachelor of Business Administration (Honours) in Finance',
  'Bachelor of Business Administration (Honours) in Management',
  'Bachelor of Business Administration (Honours) in Marketing',
  'Bachelor of Business Management and Information Technology (Honours)',
  'Bachelor of Business Studies (Honours) in Management',
  'Bachelor of Business Studies (Honours) in Marketing',
  'Bachelor of Commerce (Honours) in Accounting',
  'Bachelor of Commerce (Honours) in Accounting and Finance',
  'Bachelor of Commerce (Honours) in Accounting and Management',
  'Bachelor of Commerce (Honours) in Banking and Finance',
  'Bachelor of Commerce (Honours) in Business Management',
  'Bachelor of Commerce (Honours) in Economics',
  'Bachelor of Commerce (Honours) in Electronic Commerce',
  'Bachelor of Commerce (Honours) in Entrepreneurship',
  'Bachelor of Commerce (Honours) in Fiscal Studies',
  'Bachelor of Commerce (Honours) in Human Resource Management',
  'Bachelor of Commerce (Honours) in Information Systems',
  'Bachelor of Commerce (Honours) in Marketing',
  'Bachelor of Commerce (Honours) in Marketing Management',
  'Bachelor of Commerce (Honours) in Real Estate Management',
  'Bachelor of Commerce (Honours) in Supply Chain Management',
  'Bachelor of Commerce (Special Honours) in Digital Marketing',
  'Bachelor of Commerce (Special Honours) in Procurement and Supply Chain Management',
  'Bachelor of Dental Surgery (BDS)',
  'Bachelor of Divinity (Honours)',
  'Bachelor of Education (Honours)',
  'Bachelor of Education (Honours) in Agriculture',
  'Bachelor of Education (Honours) in Business',
  'Bachelor of Education (Honours) in Clothing and Textiles',
  'Bachelor of Education (Honours) in Early Childhood Development',
  'Bachelor of Education (Honours) in English',
  'Bachelor of Education (Honours) in Environmental Science',
  'Bachelor of Education (Honours) in Family and Consumer Science',
  'Bachelor of Education (Honours) in Food and Nutrition',
  'Bachelor of Education (Honours) in History',
  'Bachelor of Education (Honours) in Inclusive Education',
  'Bachelor of Education (Honours) in Mathematics',
  'Bachelor of Education (Honours) in Philosophy',
  'Bachelor of Education (Honours) in Psychology',
  'Bachelor of Education (Honours) in Religious Studies',
  'Bachelor of Education (Honours) in Secondary Education',
  'Bachelor of Education (Honours) in Sociology',
  'Bachelor of Engineering (Honours) in Environmental Engineering',
  'Bachelor of Engineering (Honours) in Fuels and Energy Engineering',
  'Bachelor of Engineering (Honours) in Mechatronic Engineering',
  'Bachelor of Engineering (Honours) in Production Engineering',
  'Bachelor of Laws (Honours) (MSU)',
  'Bachelor of Laws (LLB) (Honours)',
  'Bachelor of Medicine and Bachelor of Surgery (MBChB)',
  'Bachelor of Science (Honours) in Accountancy',
  'Bachelor of Science (Honours) in Aeronautical Engineering',
  'Bachelor of Science (Honours) in Agribusiness',
  'Bachelor of Science (Honours) in Agribusiness Management',
  'Bachelor of Science (Honours) in Agricultural Development and Communication Systems',
  'Bachelor of Science (Honours) in Agricultural Engineering (Irrigation)',
  'Bachelor of Science (Honours) in Agricultural Engineering (Mechanisation)',
  'Bachelor of Science (Honours) in Agricultural Equipment Design and Manufacturing Systems',
  'Bachelor of Science (Honours) in Agricultural Informatics',
  'Bachelor of Science (Honours) in Agricultural Processing Plant Design and Systems Engineering',
  'Bachelor of Science (Honours) in Agricultural and Environmental Monitoring Systems',
  'Bachelor of Science (Honours) in Agricultural and Natural Resource Economics',
  'Bachelor of Science (Honours) in Agriculture and Community Development',
  'Bachelor of Science (Honours) in Agriculture and Natural Resources',
  'Bachelor of Science (Honours) in Agriculture with Education',
  'Bachelor of Science (Honours) in Animal Health Science and Technology',
  'Bachelor of Science (Honours) in Animal Production and Technology',
  'Bachelor of Science (Honours) in Applied Biotechnology',
  'Bachelor of Science (Honours) in Applied Biotechnology and Biochemistry',
  'Bachelor of Science (Honours) in Applied Environmental Sciences and Technology',
  'Bachelor of Science (Honours) in Architecture',
  'Bachelor of Science (Honours) in Artificial Intelligence',
  'Bachelor of Science (Honours) in Audiology',
  'Bachelor of Science (Honours) in Automotive Engineering',
  'Bachelor of Science (Honours) in Biology',
  'Bachelor of Science (Honours) in Biomedical Engineering',
  'Bachelor of Science (Honours) in Biomedical Informatics',
  'Bachelor of Science (Honours) in Biomedical Sciences',
  'Bachelor of Science (Honours) in Biotechnology',
  'Bachelor of Science (Honours) in Business Computing',
  'Bachelor of Science (Honours) in Business Management and Entrepreneurship',
  'Bachelor of Science (Honours) in Chemical Engineering',
  'Bachelor of Science (Honours) in Chemistry',
  'Bachelor of Science (Honours) in Civil Engineering',
  'Bachelor of Science (Honours) in Climate Science Resilience and Livelihoods',
  'Bachelor of Science (Honours) in Clothing Fashion Design',
  'Bachelor of Science (Honours) in Clothing and Textile Education',
  'Bachelor of Science (Honours) in Clothing and Textiles',
  'Bachelor of Science (Honours) in Computer Engineering (HIT)',
  'Bachelor of Science (Honours) in Computer Information Systems',
  'Bachelor of Science (Honours) in Computer Science',
  'Bachelor of Science (Honours) in Computer Science (GSU)',
  'Bachelor of Science (Honours) in Computer Science (HIT)',
  'Bachelor of Science (Honours) in Computer Studies with Education',
  'Bachelor of Science (Honours) in Construction Engineering and Quantity Surveying',
  'Bachelor of Science (Honours) in Correctional Service Management',
  'Bachelor of Science (Honours) in Counselling',
  'Bachelor of Science (Honours) in Creative Art and Industrial Design',
  'Bachelor of Science (Honours) in Crop Improvement and Seed Systems',
  'Bachelor of Science (Honours) in Crop Science and Technology',
  'Bachelor of Science (Honours) in Crop and Animal Science',
  'Bachelor of Science (Honours) in Cyber Security and Forensic Auditing',
  'Bachelor of Science (Honours) in Data Science and Informatics',
  'Bachelor of Science (Honours) in Defence Logistics',
  'Bachelor of Science (Honours) in Drug Discovery and Therapeutics',
  'Bachelor of Science (Honours) in Economics',
  'Bachelor of Science (Honours) in Electrical and Electronic Engineering',
  'Bachelor of Science (Honours) in Energy and Power Systems Engineering',
  'Bachelor of Science (Honours) in Environmental Conservation and Geo-informatics',
  'Bachelor of Science (Honours) in Environmental Health',
  'Bachelor of Science (Honours) in Environmental Science',
  'Bachelor of Science (Honours) in Environmental Science and Natural Resources Management',
  'Bachelor of Science (Honours) in Environmental Sciences',
  'Bachelor of Science (Honours) in Environmental Sciences and Technology',
  'Bachelor of Science (Honours) in Events Management',
  'Bachelor of Science (Honours) in Fine Art',
  'Bachelor of Science (Honours) in Food Engineering',
  'Bachelor of Science (Honours) in Food Processing and Value Addition',
  'Bachelor of Science (Honours) in Food Science and Agricultural Processing',
  'Bachelor of Science (Honours) in Food Science and Technology',
  'Bachelor of Science (Honours) in Food Security and Sustainable Agriculture',
  'Bachelor of Science (Honours) in Food and Agricultural Products Processing',
  'Bachelor of Science (Honours) in Food and Nutrition',
  'Bachelor of Science (Honours) in Food and Nutrition with Education',
  'Bachelor of Science (Honours) in Forensic Medicine',
  'Bachelor of Science (Honours) in Freshwater and Fishery Science',
  'Bachelor of Science (Honours) in Gastronomy and Culinary Arts',
  'Bachelor of Science (Honours) in Geomatics Engineering',
  'Bachelor of Science (Honours) in Health Services Management',
  'Bachelor of Science (Honours) in Horticulture and Plantation Sciences',
  'Bachelor of Science (Honours) in Hospitality and Tourism',
  'Bachelor of Science (Honours) in Industrial Engineering',
  'Bachelor of Science (Honours) in Information Communication Technology',
  'Bachelor of Science (Honours) in Information Technology',
  'Bachelor of Science (Honours) in International Marketing',
  'Bachelor of Science (Honours) in International Relations',
  'Bachelor of Science (Honours) in International Relations and Diplomacy',
  'Bachelor of Science (Honours) in International Studies',
  'Bachelor of Science (Honours) in Irrigation Engineering',
  'Bachelor of Science (Honours) in Irrigation and Water Engineering',
  'Bachelor of Science (Honours) in Land Water and Waste Management Systems',
  'Bachelor of Science (Honours) in Livestock Improvement and Genetic Conservation',
  'Bachelor of Science (Honours) in Livestock Production and Nutrition Sciences',
  'Bachelor of Science (Honours) in Materials Technology and Engineering',
  'Bachelor of Science (Honours) in Mathematics',
  'Bachelor of Science (Honours) in Mathematics and Statistics',
  'Bachelor of Science (Honours) in Meat and Dairy Sciences and Technology',
  'Bachelor of Science (Honours) in Mechanical Engineering',
  'Bachelor of Science (Honours) in Mechatronics',
  'Bachelor of Science (Honours) in Medical Laboratory Sciences',
  'Bachelor of Science (Honours) in Medical Laboratory Sciences (NUST)',
  'Bachelor of Science (Honours) in Medical Laboratory Sciences (generic)',
  'Bachelor of Science (Honours) in Metallurgical Engineering',
  'Bachelor of Science (Honours) in Mining and Geological Engineering',
  'Bachelor of Science (Honours) in Mining and Mineral Processing Engineering',
  'Bachelor of Science (Honours) in Natural Resource Management',
  'Bachelor of Science (Honours) in Natural Resources Management',
  'Bachelor of Science (Honours) in Network Engineering',
  'Bachelor of Science (Honours) in Nursing',
  'Bachelor of Science (Honours) in Nursing Science',
  'Bachelor of Science (Honours) in Nursing Science (NUST)',
  'Bachelor of Science (Honours) in Nursing Science (generic)',
  'Bachelor of Science (Honours) in Nutrition and Dietetics',
  'Bachelor of Science (Honours) in Occupational Therapy',
  'Bachelor of Science (Honours) in Occupational and Environmental Health',
  'Bachelor of Science (Honours) in Optometry',
  'Bachelor of Science (Honours) in Pharmacy',
  'Bachelor of Science (Honours) in Pharmacy and Drug Discovery',
  'Bachelor of Science (Honours) in Physics',
  'Bachelor of Science (Honours) in Physiotherapy',
  'Bachelor of Science (Honours) in Plant Production Science and Technology',
  'Bachelor of Science (Honours) in Public Administration and Management',
  'Bachelor of Science (Honours) in Radiography',
  'Bachelor of Science (Honours) in Radiography (Diagnostic)',
  'Bachelor of Science (Honours) in Rangeland Science and Livestock Production Ecology',
  'Bachelor of Science (Honours) in Real Estate',
  'Bachelor of Science (Honours) in Retail Operations and Management',
  'Bachelor of Science (Honours) in Social Work',
  'Bachelor of Science (Honours) in Software Engineering',
  'Bachelor of Science (Honours) in Software Engineering (HIT)',
  'Bachelor of Science (Honours) in Soil Science and Land Management',
  'Bachelor of Science (Honours) in Spatial Planning and Management',
  'Bachelor of Science (Honours) in Speech Therapy',
  'Bachelor of Science (Honours) in Supply Chain Management',
  'Bachelor of Science (Honours) in Travel, Leisure and Recreation',
  'Bachelor of Science (Honours) in Value Chain Development and Agricultural Marketing',
  'Bachelor of Science (Honours) in Visual Communication and Multimedia Design',
  'Bachelor of Science (Honours) in Water Resources and Irrigation Engineering',
  'Bachelor of Science (Honours) in Wildlife Ecology and Conservation',
  'Bachelor of Science (Honours) in Wildlife and Fisheries Conservation',
  'Bachelor of Science (Honours) with Education (various)',
  'Bachelor of Science (Honours) with Education in Business/Commerce',
  'Bachelor of Social Science (Honours) in Social Work',
  'Bachelor of Social Sciences (Honours) in Human Resources Management',
  'Bachelor of Social Sciences (Honours) in Psychology',
  'Bachelor of Social Sciences (Honours) in Sociology',
  'Bachelor of Technology (Honours) in Hotel, Catering and Tourism Management',
  'Bachelor of Theology (Honours)',
  'Certificate in Education and Leadership (Executive)',
  'Certificate in Sugarcane Agriculture',
  'Diploma in Agribusiness',
  'Diploma in Science Education',
  'Diploma in Sugarcane Agriculture',
  'Doctor of Philosophy',
  'Doctor of Philosophy (Agriculture)',
  'Doctor of Philosophy (Business and Commerce)',
  'Doctor of Philosophy (HIT)',
  'Doctor of Philosophy (Tourism)',
  'Doctor of Philosophy (WUA)',
  'Doctor of Philosophy (ZOU)',
  'Doctor of Philosophy in Agriculture (MSU)',
  'Doctor of Philosophy in Agriculture and Natural Sciences',
  'Doctor of Philosophy in Child Rights, Childhood and Family Studies',
  'Doctor of Philosophy in Intellectual Property',
  'Doctor of Philosophy in Peace, Leadership and Governance',
  'Doctor of Philosophy in Philosophy',
  'Doctor of Philosophy in Public Health',
  'Executive Master in Peace and Governance',
  'Executive Master of Business Administration',
  'Graduate Diploma in Human Rights, Peace and Development',
  'Graduate Diploma in Peace and Governance',
  'Graduate Diploma in Public Policy and Governance',
  'Master in Intellectual Property',
  'Master in Peace, Leadership and Governance',
  'Master of Arts in Defence and Security Studies',
  'Master of Arts in Development Studies',
  'Master of Arts in Literary Studies',
  'Master of Arts in Philosophy',
  'Master of Arts in Religious Studies',
  'Master of Arts in Theology',
  'Master of Arts in Theology and Religious Studies (ZEGU)',
  'Master of Business Administration',
  'Master of Business Administration (MSU)',
  'Master of Business Leadership',
  'Master of Commerce in Applied Accounting',
  'Master of Commerce in Economics',
  'Master of Commerce in Finance',
  'Master of Commerce in Information Systems',
  'Master of Commerce in Marketing Management',
  'Master of Commerce in Strategic Management',
  'Master of Commerce in Supply Chain Management',
  'Master of Development Finance',
  'Master of Education in Educational Leadership, Management and Development',
  'Master of Education in Educational Management',
  'Master of Education in Educational Technology',
  'Master of Education in English Language and Literature',
  'Master of Laws (LLM)',
  'Master of Philosophy',
  'Master of Philosophy (Agriculture)',
  'Master of Philosophy (Business and Commerce)',
  'Master of Philosophy (HIT)',
  'Master of Philosophy (Tourism)',
  'Master of Philosophy (WUA)',
  'Master of Philosophy (ZOU)',
  'Master of Philosophy in Agriculture (MSU)',
  'Master of Philosophy in Agriculture and Natural Sciences',
  'Master of Philosophy in Philosophy',
  'Master of Philosophy in Public Health',
  'Master of Philosophy in Supply Chain Management',
  'Master of Public Health',
  'Master of Public Sector Management',
  'Master of Science (Honours) in Food and Nutrition',
  'Master of Science Education in Biology',
  'Master of Science Education in Chemistry',
  'Master of Science Education in Curriculum Studies',
  'Master of Science Education in Geography',
  'Master of Science Education in Mathematics',
  'Master of Science Education in Measurement, Assessment and Evaluation',
  'Master of Science Education in Physics',
  'Master of Science in Accounting and Finance (MUAST)',
  'Master of Science in Agribusiness',
  'Master of Science in Agricultural Administration Policy and Trade',
  'Master of Science in Agricultural Informatics and Data Analytics',
  'Master of Science in Agricultural and Applied Economics',
  'Master of Science in Agronomy',
  'Master of Science in Animal Production and Technology',
  'Master of Science in Applied Accounting',
  'Master of Science in Applied Entrepreneurship',
  'Master of Science in Architecture and Heritage Conservation',
  'Master of Science in Biodiversity Conservation',
  'Master of Science in Child Rights and Childhood Studies',
  'Master of Science in Climate Change and Sustainable Development',
  'Master of Science in Clothing and Textiles',
  'Master of Science in Cloud Computing and Internet of Things',
  'Master of Science in Communication Engineering',
  'Master of Science in Computer Engineering',
  'Master of Science in Computer Science',
  'Master of Science in Computer Science (HIT)',
  'Master of Science in Conflict Prevention and Early Warning Mechanisms',
  'Master of Science in Crop Production',
  'Master of Science in Crop Protection and Post-Harvest Technology',
  'Master of Science in Crop Science',
  'Master of Science in Cyber Security',
  'Master of Science in Development Studies (ZEGU)',
  'Master of Science in Electrical Power Engineering',
  'Master of Science in Entrepreneurship',
  'Master of Science in Entrepreneurship, Innovation and Creativity',
  'Master of Science in Food Safety and Port Health',
  'Master of Science in Geomatics Engineering',
  'Master of Science in Geotechnical Engineering',
  'Master of Science in Hospitality and Tourism',
  'Master of Science in Hospitality and Tourism (MSUAS)',
  'Master of Science in Human Resource Management (MUAST)',
  'Master of Science in Industrial Electronics Technology',
  'Master of Science in International Relations',
  'Master of Science in International Relations and Diplomacy',
  'Master of Science in International Studies',
  'Master of Science in Manufacturing Systems Engineering',
  'Master of Science in Mechatronics and Artificial Intelligence',
  'Master of Science in Migration, Citizenship and Refugee Protection',
  'Master of Science in Mining Engineering',
  'Master of Science in Mobile and Wireless Communication',
  'Master of Science in Negotiation and Mediation',
  'Master of Science in Network Engineering',
  'Master of Science in One Health',
  'Master of Science in Organisational Psychology',
  'Master of Science in Post-Harvest Science and Technology',
  'Master of Science in Real Estate Management',
  'Master of Science in Renewable Energy',
  'Master of Science in Spatial Planning Systems',
  'Master of Science in Strategic Management',
  'Master of Science in Structural Engineering',
  'Master of Science in Supply Chain Management',
  'Master of Science in Supply Chain Management (MUAST)',
  'Master of Science in Sustainable Livelihoods and Technologies',
  'Master of Science in Telecommunications Engineering',
  'Master of Science in Transport and Logistics',
  'Master of Science in Water Resources Engineering and Infrastructure Management',
  'Master of Social Science in Child and Family Studies',
  'Master of Theological Studies',
  'Master’s in Human Rights, Peace and Development',
  'Master’s in Public Policy and Governance',
  'Post Graduate Diploma in Higher Education (MSUAS)',
  'Post-Basic Bachelor of Science in Nursing',
  'Post-Graduate in Theology and Religious Research',
  'Postgraduate Diploma in Business Administration',
  'Postgraduate Diploma in Digital Marketing',
  'Postgraduate Diploma in Education',
  'Postgraduate Diploma in Education (CUZ)',
  'Postgraduate Diploma in Education (ZOU)',
  'Postgraduate Diploma in Entrepreneurship',
  'Postgraduate Diploma in Higher Education',
  'Postgraduate Diploma in Obstetrics and Gynaecology Imaging (CT)',
  'Postgraduate Diploma in Obstetrics and Gynaecology Imaging (Ultrasound)',
  'Postgraduate Diploma in Palliative Care'
];