export const universities = [
  'Africa University',
  'Arrupe Jesuit University',
  'Bindura University of Science Education (BUSE)',
  'Catholic University in Zimbabwe (CUZ)',
  'Chinhoyi University of Technology (CUT)',
  'Great Zimbabwe University (GZU)',
  'Gwanda State University (GSU)',
  'Harare Institute of Technology (HIT)',
  'Lupane State University (LSU)',
  'Manicaland State University of Applied Sciences',
  'Marondera University of Agricultural Science & Technology (MUAST)',
  'Midlands State University (MSU)',
  'National University of Science and Technology (NUST)',
  'Reformed Church University',
  'Solusi University',
  'Southern Africa Methodist University (SAMU)',
  'University of Zimbabwe (UZ)',
  'Womens University in Africa (WUA)',
  'Zimbabwe Ezekiel Guti University (ZEGU)',
  'Zimbabwe Open University (ZOU)',
  'Bulawayo Polytechnic',
  'Mutare Polytechnic',
  'Joshua Mqabuko Nkomo Polytechnic',
  'Gweru Polytechnic',
  'Kwekwe Polytechnic',
  'Masvingo Polytechnic',
  'Kushinga Phikelela Polytechnic',
  'Harare Polytechnic',
  'School of Hospitality & Tourism',
  'Blended Education College of Southern Africa (BECSA), Bulawayo',
  'Belvedere Technical Teachers College',
  'Bondolfi Teachers College',
  'Hillside Teachers College',
  'Gweru Polytechnic (Teacher Training)',
  'Joshua Mqabuko Nkomo Polytechnic (Teacher Training)',
  'Madziva Teachers College',
  'Marymount Teachers College',
  'Masvingo Teachers College',
  'Morgan ZINTEC College',
  'Mkoba Teachers College (Gweru)',
  'University of Zimbabwe (Nursing Programmes)',
  'National University of Science and Technology (NUST) - Nursing',
  'Midlands State University (MSU) - Nursing',
  'Africa University (Nursing)',
  'Bindura University of Science Education (BUSE) - Nursing',
  'Great Zimbabwe University (GZU) - Nursing',
];